Repository doxygen/doxygen, pull requests merged in 2018-10, with the labels that each got.

#6546 Numbers in comment disappear
  src/fortranscanner.l
Labels: Fortran, bug

#6551 Fix travis mac build
  .travis.yml
Labels: bug

#6548 issue_6547 Call graph missing due to ALIASES
  src/doxygen.cpp
Labels: bug

#6545 Bold text terminated by plus sign
  src/markdown.cpp
Labels: bug

#6535 issue_6524: Markdown formats missing in doxygen outputs.
  doc/markdown.doc
  src/markdown.cpp
Labels: enhancement

#6552 Bug 710654 - <img> on a \page does not copy the image to the html output folder
  src/docparser.cpp
Labels: HTML, enhancement

#6553 Bug 719541 - Error with inserting images to PDF with Markdown
  src/markdown.cpp
Labels: DocBook, LaTeX, RTF, enhancement

#6544 Add python function annotations support
  src/pyscanner.l
Labels: Python, enhancement

#6564 Remove obsolete line from README.md
  README.md
Labels: documentation, enhancement

#6565 Bug 749049 - Doxygen not creating call graphs for C# methods if namespace contains the classname
  src/code.l
  src/scanner.l
Labels: C#, bug

#6570 issue_6566: INHERIT_DOCS not working for python
  src/doxygen.cpp
Labels: Python, bug

#6569 Wrong separator in index for a.o. Python, C#
  src/memberdef.cpp
Labels: C#, DocBook, LaTeX, Python, RTF, bug

#6563 Enable comma as separator in configuration lists
  src/configimpl.l
Labels: enhancement

#6567 Handling Fortran functions in call graphs
  src/fortrancode.l
Labels: Fortran, bug

#6470 Issue 6469: Java method calls are ignored in generating call/caller graph with Graphviz
  src/code.l
Labels: Java, bug

#6536 Bug 677092 - single quote in HTML section of PHP breaks doxygen
  src/scanner.l
Labels: PHP, bug

#6486 Extending tests with extra possibilities
  testing/README.txt
  testing/runtests.py
Labels: enhancement, install/build

#6463 Correction of some coloring of code comments in VHDL, adding data type 'positive'
  src/vhdlcode.l
  src/vhdldocgen.cpp
Labels: VHDL, bug

#6561 Remove obsolete definitions from scanner
  src/scanner.l
Labels: bug

#6460 Issue_6456 Using # in links causes errors in PDF generation
  src/latexdocvisitor.cpp
  src/latexgen.cpp
  src/util.cpp
  src/util.h
Labels: LaTeX, bug

#6577 Documentation internet addresses
  doc/changelog.doc
  doc/docblocks.doc
  doc/features.doc
  doc/install.doc
  doc/markdown.doc
  doc/searching.doc
  doc/starting.doc
  src/config.xml
Labels: bug, documentation

#6439 Bug 748927 - Navigation incorrect with escaped symbols
  src/commentscan.l
Labels: enhancement

#6542 Bug 751700 - Main page absent in TOC of CHM, if PROJECT_NAME is empty
  src/config.h
  src/configimpl.h
  src/configimpl.l
Labels: bug

#6435 Possibility to have a \image command inside a <A> tag
  src/docparser.cpp
Labels: enhancement

#6459 File list creation performance improvement.
  src/doxygen.cpp
Labels: enhancement

#6466 Correcting warning messages and echoing unknown command
  src/docparser.cpp
  src/docparser.h
  src/doctokenizer.h
  src/doctokenizer.l
Labels: bug

#6579 RTF layout regarding References and Referenced by
  src/rtfgen.cpp
Labels: RTF, enhancement

#6572 Fortran scanner abort message
  src/fortranscanner.l
Labels: Fortran, enhancement

#6560 Remove old obsolete docbook generator
  src/docbookgen.cpp
  src/docbookgen.h
  src/doxygen.cpp
Labels: DocBook, bug

#6549 issue_6533: PHP: Namespaced typehints in deprecated methods not handled correctly
  src/reflist.cpp
Labels: PHP, bug

#6438 Correcting labels for citations
  src/docparser.cpp
  src/xmldocvisitor.cpp
  testing/012/citelist.xml
Labels: RTF, XML, bug

#6396 Bug 520975 - Unnamed parameters parsed incorrectly
  src/defargs.l
Labels: C/C++, bug

#6448 Markdown list wrong displayed
  src/markdown.cpp
Labels: bug

#6475 Sorting of index in case of LaTeX
  src/util.cpp
Labels: LaTeX, bug

#6584 Correcting tag in printdocvisitor
  src/printdocvisitor.h
Labels: bug

#6582 Spelling of the word Javadoc
  doc/autolink.doc
  doc/commands.doc
  doc/docblocks.doc
  doc/features.doc
  examples/jdstyle.cfg
  src/commentscan.h
Labels: bug, documentation

#6588 [C++] Add support for std::shared_ptr
  src/doxygen.cpp
Labels: C/C++, enhancement

#6586 Issue_6585: Unexpected anchor tags in tag-files
  src/tagreader.cpp
Labels: bug
