Repository doxygen/doxygen, pull requests merged in 2018-09, with the labels that each got.

#6418 Correct typing error in warning message.
  src/util.cpp
Labels: bug

#6419 Consistency of environment variables between config and code
  src/doctokenizer.l
Labels: enhancement

#6480 Correct typing error in test 51
  testing/051/indexpage.xml
  testing/051_escape.dox
Labels: bug

#6424 Include height item in XML output
  src/xmldocvisitor.cpp
Labels: XML, bug

#6477 Missing opening round bracket in case of an exception
  src/latexgen.cpp
  src/rtfgen.cpp
Labels: LaTeX, RTF, bug

#6430 'self' keyword in PHP documentation
  src/code.l
Labels: PHP, bug

#6493 Small correction installation / build procedure
  doc/install.doc
Labels: bug, documentation

#6474 WIP: Init Windows AppVeyor CI
  appveyor.yml
Labels: enhancement, install/build

#6496 Issue 6494: asterisks before args and kwargs are ignored in python
  src/pyscanner.l
Labels: Python, bug

#6440 Bug 634830 - Automatic links don't work correctly with operator< and operator<=
  src/code.l
Labels: C/C++, bug

#6500 Update install.doc: Qt 5 is now supported as well
  doc/install.doc
Labels: bug, documentation

#6509 Usage of '{', '}' and ',' in ALIAS
  doc/custcmd.doc
  src/config.xml
Labels: bug, documentation

#6502 Init macOS CI
  .travis.yml
  README.md
Labels: enhancement, install/build

#6503 Fixing problem with possible not initialized variable (endless loop in VS 2017 debug)
  src/definition.cpp
  src/xmlgen.cpp
Labels: XML, bug, install/build

#6506 Fixing coverity messages (Namespace tag)
  src/namespacedef.cpp
Labels: bug

#6501 Close last code line properly.
  src/latexgen.cpp
Labels: LaTeX, Python, bug

#6511 Add possibility for adding doxygen configuration items to, all, tests during runtime.
  testing/README.txt
  testing/runtests.py
Labels: enhancement, install/build

#6505 Fixing coverity messages
  src/clangparser.cpp
  src/context.cpp
  src/definition.cpp
  src/docparser.h
  src/htmlgen.cpp
  src/latexdocvisitor.cpp
  src/layout.cpp
  src/layout.h
  src/perlmodgen.cpp
  src/pyscanner.l
  src/tagreader.cpp
  src/tclscanner.l
Labels: bug

#6499 Namespace with name docstrings_linebreak
  src/pyscanner.l
Labels: Python, bug

#6510 Difference between standard and used Doxyfile
  doc/arch.doc
  doc/doxygen.1
  src/config.h
  src/configimpl.h
  src/configimpl.l
  src/doxygen.cpp
Labels: enhancement, install/build

#6487 Implementation of standard generator for docbook output
  doc/commands.doc
  src/classdef.cpp
  src/commentscan.l
  src/definition.cpp
  src/docbookgen.cpp
  src/docbookgen.h
  src/docbookvisitor.cpp
  src/docbookvisitor.h
  src/docparser.h
  src/dot.cpp
  src/doxygen.cpp
  src/filedef.cpp
  src/index.cpp
  src/marshal.cpp
  src/memberdef.cpp
  src/outputgen.h
  src/pagedef.cpp
  src/types.h
  src/util.cpp
  src/util.h
  testing/031/indexpage.xml
  testing/031_image.dox
  testing/043_page.dox
Labels: DocBook, bug

#6520 C++11 features used in doxygen
  src/docbookgen.cpp
  src/docbookgen.h
  src/htmlgen.cpp
  src/index.cpp
  src/tagreader.cpp
Labels: bug, install/build

#6514 addindex supports also DocBook and RTF
  doc/commands.doc
  doc/output.doc
Labels: bug, documentation

#6521 Difference between standard and used Doxyfile (list)
  src/configimpl.l
Labels: bug, install/build

#6489 Don't link to non existing / not accessible namespaces , in CSharp, in the source code
  src/code.l
Labels: C#, bug
