Repository doxygen/doxygen, pull requests merged in 2018-07, with the labels that each got.

#6405 Improvements in handling special characters in LaTeX
  src/util.cpp
  templates/latex/doxygen.sty
Labels: LaTeX, bug

#6403 Consistency between 'generate' and 'update' startup option
  src/doxygen.cpp
Labels: bug

#6401 Bug 648180 - Fortran: tagfile.tag:789: warning: Unknown compound attribute `type' found!
  src/classdef.cpp
  src/classdef.h
Labels: Fortran, bug

#6389 Bug PATCH -- updates reference link with no closing
  src/htmlgen.cpp
Labels: HTML, bug

#6398 Bug 610436 - <![CDATA[ is not handled inside C# comments
  doc/xmlcmds.doc
  src/commentscan.l
Labels: enhancement

#6394 Wrong link generated for inherited members when tag files are used.
  src/htmlgen.cpp
Labels: HTML, bug

#6410 Bug 734820 - "remove" is treated as a keyword (green) in the source browser for C++
  src/code.l
Labels: C/C++, bug

#6397 Documentation EXTENSION_MAPPING
  src/config.xml
Labels: documentation
