Repository doxygen/doxygen, pull requests merged in 2019-05, with the labels that each got.

#6965 Fix #6906
  addon/doxyapp/CMakeLists.txt
  addon/doxyparse/CMakeLists.txt
  src/CMakeLists.txt
  vhdlparser/CMakeLists.txt
Labels: bug, install/build

#6964 Missing white space in warning
  src/doxygen.cpp
Labels: bug

#6963 Truncated warning message
  src/message.cpp
Labels: bug

#6967 Bug 783759 - PERL_PATH config option: when is this needed? Still used?
  Doxyfile
  addon/doxmlparser/Doxyfile
  addon/doxmlparser/Doxyfile.impl
  doc/Doxyfile
  examples/tag.cfg
  qtools/Doxyfile
  src/config.xml
Labels: bug, documentation

#6970 issue #6968 INLINE_INHERITED_MEMB doesn't respect EXTRACT_PRIVATE=NO
  src/classdef.cpp
Labels: C/C++, bug

#6931 Windows crash in case of incorrect end statement
  src/fortranscanner.l
Labels: Fortran, bug

#6974 Fixes #6973 - Fixed segmentation fault in do_warn
  src/message.cpp
Labels: bug

#6981 issue #6979 Method parameters documented inline are not present in documentation of overriding/implementing methods
  src/memberdef.cpp
Labels: bug

#6984 Bug 781306 - *** Error in `doxygen': realloc(): invalid pointer: 0x0000000001d45ba0 @ exit
  src/htags.cpp
Labels: bug

#6913 Markdown file as internet link
  src/markdown.cpp
  src/util.cpp
  src/util.h
Labels: bug

#6870 issue #6869 SVG image generated by \dot or \dotfile does not render properly in HTML
  src/dot.cpp
Labels: HTML, bug

#6914 Image not seen as svg image
  src/docparser.cpp
Labels: bug

#6985 Enable example doxmlparser possibilities for cmake build
  addon/doxmlparser/CMakeLists.txt
  addon/doxmlparser/examples/CMakeLists.txt
  addon/doxmlparser/examples/metrics/CMakeLists.txt
  addon/doxmlparser/examples/metrics/Makefile.in
  addon/doxmlparser/examples/metrics/metrics.pro.in
  addon/doxmlparser/include/doxmlintf.h
  addon/doxmlparser/src/CMakeLists.txt
  addon/doxmlparser/src/doxmlintf.h
  addon/doxmlparser/test/CMakeLists.txt
  addon/doxmlparser/test/Makefile.in
  addon/doxmlparser/test/xmlparse.pro.in
Labels: enhancement

#6989 Don't try to load htags filemap in case htags fails
  src/doxygen.cpp
Labels: bug

#6988 USE_HTAGS = YES, there are _no_ call / caller graphs in the documentation
  src/doxygen.cpp
Labels: bug

#6991 issue #6990 Dot produces no Graphs
  src/dot.cpp
Labels: bug

#6983 Special handling of the UTF8 nbsp sequence
  src/markdown.cpp
Labels: bug

#6971 issue #6945 \class after \brief doesn't count as a new line - resulting docs show merged descriptions
  src/commentscan.l
Labels: enhancement

#6962 Incorrect output tag order
  src/pagedef.cpp
Labels: bug

#6961 Incorrect Reached end of file while still inside a (nested) comment for TCL / Python
  src/commentcnv.l
Labels: Python, bug

#6916 Class definition with collections
  src/pyscanner.l
Labels: Python, bug

#7001 Missing debug statements sqlcode and xmlcode lexers
  src/sqlcode.l
  src/xmlcode.l
Labels: enhancement

#7007 More than 26 appendices in LaTeX manual
  doc/doxygen_manual.tex
Labels: bug, documentation

#7005 enable debug for re-entrant lexers
  src/constexp.l
  src/declinfo.l
  src/sqlcode.l
Labels: bug

#6954 Ambiguous file name in file command
  src/doxygen.cpp
Labels: enhancement

#7016 issue 7015 Parsing issue with @includedoc and @startuml
  src/doctokenizer.l
Labels: bug

#7017 Conflict between RCS tag and (e.g.) php description
  src/doctokenizer.l
Labels: PHP, bug

#6944 Handling digraph versus label
  src/dot.cpp
Labels: bug
