Repository doxygen/doxygen, pull requests merged in 2019-11, with the labels that each got.

#7287 Nicer warning for missing parameter
  src/docparser.cpp
Labels: enhancement

#7369 Removing left over debug statements
  src/doxygen.cpp
  src/memberdef.cpp
Labels: bug

#7364 issue #7358: Ternary conditional and null-coalescing operator in constructor results in faulty warning
  src/scanner.l
Labels: C#, bug

#7323 Skip empty HTML tag
  src/docparser.cpp
Labels: bug

#7308 Code links.
  src/code.l
Labels: bug

#7371 QGDict::hashAsciiKey: Invalid null key due to empty procedure name
  src/tclscanner.l
Labels: bug, tcl

#7372 Spelling corrections for vhdl directory
  vhdlparser/vhdlparser.jj
Labels: bug

#7373 Spelling corrections for testing directory
  testing/012/indexpage.xml
  testing/012_cite.dox
  testing/testsqlite3.py
Labels: bug

#7380 Spelling corrections for qtools directory
  qtools/qcstring.h
  qtools/qdict.doc
  qtools/qglobal.h
  qtools/qlist.doc
  qtools/qstring.cpp
  qtools/qtextcodec.cpp
  qtools/qtl.doc
  qtools/qvaluelist.doc
  qtools/qxml.cpp
Labels: bug

#7378 Spelling corrections for addon directory
  addon/doxmlparser/Doxyfile
  addon/doxmlparser/Doxyfile.impl
  addon/doxmlparser/include/doxmlintf.h
  addon/doxmlparser/test/main.cpp
Labels: bug

#7376 Spelling corrections for doc directory
  doc/changelog.doc
  doc/htmlcmds.doc
  doc/translator.py
Labels: bug

#7374 Spelling corrections for templates directory
  templates/html/htmllayout.tpl
  templates/html/htmltypeconstraints.tpl
Labels: bug

#7377 Spelling corrections for src directory
  src/cite.cpp
  src/clangparser.cpp
  src/classdef.cpp
  src/code.l
  src/commentcnv.l
  src/commentscan.l
  src/condparser.h
  src/context.cpp
  src/declinfo.l
  src/definition.cpp
  src/diagram.cpp
  src/dirdef.cpp
  src/docparser.cpp
  src/doctokenizer.l
  src/dotdirdeps.cpp
  src/dotgraph.cpp
  src/doxygen.cpp
  src/filedef.cpp
  src/fortrancode.l
  src/fortranscanner.l
  src/htmlhelp.cpp
  src/languages.py
  src/latexgen.cpp
  src/markdown.cpp
  src/pre.l
  src/pycode.l
  src/rtfgen.cpp
  src/rtfgen.h
  src/scanner.l
  src/searchindex.cpp
  src/searchindex.h
  src/sortdict.h
  src/sqlite3gen.cpp
  src/template.cpp
  src/util.cpp
  src/vhdldocgen.h
  src/vhdljjparser.cpp
  src/xmlgen.cpp
Labels: bug

#7379 Spelling corrections for libmscgen directory
  libmscgen/gd.h
  libmscgen/mscgen_adraw.h
  libmscgen/mscgen_adraw_int.h
  libmscgen/mscgen_api.c
  libmscgen/mscgen_gd_out.c
  libmscgen/mscgen_lexer.l
  libmscgen/mscgen_msc.h
  libmscgen/mscgen_usage.c
  libmscgen/mscgen_utf8.c
Labels: bug

#7375 Spelling corrections for examples directory
  examples/templ.cpp
Labels: bug

#7383 Better warning message in case of illegal command
  src/docparser.cpp
Labels: bug

#7344 Small improvements of TCL output
  src/docbookgen.cpp
  src/htmlgen.cpp
  src/latexgen.cpp
  src/mangen.h
  src/rtfgen.cpp
  src/tclscanner.l
Labels: bug, tcl

#7296 issue #7295 Doxygen documentation of C++17 nested namespace erroneous
  src/scanner.l
Labels: C++17, bug

#7392 issue #7290 error: Problem running ghostscript gs -q -g562x56 -r384x384x -sDEVICE=ppmraw -sOutputFile=_form0.pnm -dNOPAUSE -dBATCH -- _form0.ps. Check your installation!
  src/formula.cpp
Labels: bug

#7394 Fix line count after multiline close group
  src/scanner.l
Labels: bug

#7397 issue #7396 Illegal Character in XML output
  src/xmlgen.cpp
Labels: XML, bug

#7402 HHC and directory elements starting with "."
  src/doxygen.cpp
  src/portable.cpp
  src/portable.h
Labels: bug

#7395 Problem with horizontal ruler directly after fenced code section
  src/markdown.cpp
Labels: Markdown, bug

#7416 Problem converting UCS big endian file
  src/util.cpp
Labels: bug

#7418 Adding some links in search documentation
  doc/extsearch.doc
Labels: documentation

#7414 Correct style in table header in case of paragraph is used
  templates/html/doxygen.css
Labels: bug

#7293 Textual error
  doc/commands.doc
Labels: bug, documentation
