Repository doxygen/doxygen, pull requests merged in 2019-01, with the labels that each got.

#6724 Fixed typo in warning message
  src/docparser.cpp
Labels: bug

#6735 issue #6732 align environment for formula (\f{align}) no longer working
  src/commentscan.l
Labels: bug

#6742 Double defined operator in test 74
  testing/074/namespacens.xml
  testing/074/struct_foo.xml
  testing/074_ref.cpp
Labels: HTML, bug

#6743 Tests are unsorted
  testing/runtests.py
Labels: bug

#6739 Implementing `<hr>` for LaTeX
  src/latexdocvisitor.cpp
  templates/latex/doxygen.sty
Labels: LaTeX, bug

#6736 https link to sourceforge.net
  README.md
Labels: bug

#6684 Broken links in documentation
  doc/commands.doc
  doc/faq.doc
Labels: bug, documentation

#6746 issue #6744 Ampersand in Markdown image URL is not escaped in XML output
  src/htmldocvisitor.cpp
  src/util.cpp
  src/util.h
  src/xmldocvisitor.cpp
  testing/031/indexpage.xml
  testing/031_image.dox
Labels: HTML, XML, bug

#6751 issue #6749 doxygen 1.8.15 segfault
  src/util.cpp
Labels: LaTeX, bug

#6755 issue #6748 1.8.15 regression with C# internal modifier
  src/scanner.l
Labels: C#, bug

#6750 issue #6725 Doxygen 1.8.15 CMake 3.13 incompatibility
  src/config.xml
Labels: LaTeX, enhancement, install/build

#6747 Warning messages of test 66
  testing/066/class_class1.xml
  testing/066_property_initializer.cs
Labels: bug

#6761 Terminating brief command
  src/commentscan.l
Labels: bug

#6757 issue #6754 False positives for "multiple @param sections"
  src/docparser.cpp
Labels: bug

#6740 issue #6727 SHOW_NAMESPACES = NO breaks latex PDF
  src/index.cpp
Labels: LaTeX, RTF, bug

#6738 issue #6733 invalid cite anchor id when using crossref
  src/cite.cpp
  templates/html/doxygen.bst
  testing/012/citelist.xml
  testing/012/indexpage.xml
  testing/012_cite.dox
  testing/050/indexpage.xml
  testing/sample.bib
Labels: bug

#6768 Terminate brief in case of `-#` list
  src/commentscan.l
  testing/081/081__brief__lists_8h.xml
  testing/081_brief_lists.h
Labels: bug

#6767 Invalid id possible with tooltips
  src/htmlgen.cpp
  src/tooltip.cpp
Labels: HTML, bug

#6766 No translation of markdown in <pre>
  src/markdown.cpp
  testing/081/081__markdown__pre_8f90.xml
  testing/081_markdown_pre.f90
Labels: Fortran, Python, bug

#6780 issue #6679 Multiple use of section label warning for Setex-stype headers in markdown
  src/markdown.cpp
Labels: bug

#6792 issue #6791 TOC not generated when using a particular Markdown headerstyle
  src/config.xml
  testing/055/md_055_markdown.xml
Labels: bug

#6807 Inline VHDL code
  src/vhdlcode.l
Labels: VHDL, bug

#6801 issue #6800 Markdown line ending problems in 1.8.15 and master
  src/markdown.cpp
Labels: bug
