Repository doxygen/doxygen, pull requests merged in 2020-12, with the labels that each got.

#8217 Extend tests with some other default tests
  .travis.yml
Labels: enhancement, install/build

#8207 Enable UML diagrams without member fields
  src/config.xml
  src/dotnode.cpp
Labels: bug, enhancement

#8197 issue #8023 Add option to exit with non-zero exit code on warnings even if WARN_AS_ERROR is OFF
  src/config.xml
  src/doxygen.cpp
  src/message.cpp
  src/message.h
Labels: enhancement

#7991 bug 789318 c# expression-bodied property is not rendered correctly
  src/scanner.l
Labels: C#, bug

#8221 Correction of spelling errors
  addon/doxyparse/README.md
Labels: bug

#8222 Incorrect link in doxygen documentation
  doc/commands.doc
  doc/faq.doc
  doc/features.doc
  doc/install.doc
  src/config.xml
Labels: bug, documentation

#8199 Have build of doxygen documentation fail on warnings.
  doc/Doxyfile
  examples/afterdoc.cfg
  examples/author.cfg
  examples/autolink.cfg
  examples/class.cfg
  examples/define.cfg
  examples/diagrams.cfg
  examples/docstring.cfg
  examples/enum.cfg
  examples/example.cfg
  examples/file.cfg
  examples/func.cfg
  examples/group.cfg
  examples/include.cfg
  examples/javadoc-banner.cfg
  examples/jdstyle.cfg
  examples/manual.cfg
  examples/memgrp.cfg
  examples/mux.cfg
  examples/overload.cfg
  examples/page.cfg
  examples/par.cfg
  examples/pyexample.cfg
  examples/qtstyle.cfg
  examples/relates.cfg
  examples/restypedef.cfg
  examples/structcmd.cfg
  examples/tag.cfg
  examples/templ.cfg
Labels: bug, documentation, install/build

#8225 Update used links in test examples
  testing/012/citelist.xml
  testing/031/indexpage.xml
  testing/031_image.dox
  testing/050/indexpage.xml
  testing/sample.bib
Labels: bug, install/build

#8224 Creating link to not defined label in case of groups
  src/groupdef.cpp
  src/groupdef.h
Labels: HTML, bug

#8223 Present all warnings of first documentation sub-task when it fails
  doc/Doxyfile
  examples/afterdoc.cfg
  examples/author.cfg
  examples/autolink.cfg
  examples/class.cfg
  examples/define.cfg
  examples/diagrams.cfg
  examples/docstring.cfg
  examples/enum.cfg
  examples/example.cfg
  examples/file.cfg
  examples/func.cfg
  examples/group.cfg
  examples/include.cfg
  examples/javadoc-banner.cfg
  examples/jdstyle.cfg
  examples/manual.cfg
  examples/memgrp.cfg
  examples/mux.cfg
  examples/overload.cfg
  examples/page.cfg
  examples/par.cfg
  examples/pyexample.cfg
  examples/qtstyle.cfg
  examples/relates.cfg
  examples/restypedef.cfg
  examples/structcmd.cfg
  examples/tag.cfg
  examples/templ.cfg
Labels: documentation, enhancement

#8248 issue #8247 declaration different in cpp and h file of qstrncmp
  qtools/qcstring.h
Labels: bug

#8250 Incorrect end tag in doxywizard
  addon/doxywizard/inputbool.cpp
  addon/doxywizard/inputint.cpp
  addon/doxywizard/inputstring.cpp
  addon/doxywizard/inputstrlist.cpp
Labels: bug, doxywizard

#8249 issue #8246 The prefix &#х202А; for files is displayed incorrectly in the file names.
  src/index.cpp
Labels: bug

#8242 Incorrect specification of irc as URL protocol
  src/doctokenizer.l
  src/util.cpp
Labels: bug

#8252 Recent file list of doxywizard not cleared properly
  addon/doxywizard/doxywizard.cpp
Labels: bug, doxywizard

#8254 Improvements of reading the configuration file
  addon/doxywizard/CMakeLists.txt
  addon/doxywizard/config_doxyw.l
  addon/doxywizard/config_msg.cpp
  addon/doxywizard/config_msg.h
  addon/doxywizard/doxywizard.cpp
  addon/doxywizard/doxywizard.h
  addon/doxywizard/inputbool.cpp
  addon/doxywizard/inputint.cpp
  addon/doxywizard/inputstring.cpp
Labels: bug, doxywizard

#8243 issue #8142 UTF-8 in URL in source generates truncated URL in HTML
  src/doctokenizer.l
Labels: bug

#8244 Incorrect handling of UTF-8 characters in latex reference statement
  src/util.cpp
Labels: LaTeX, bug

#8260 Extend tests with some other default tests
  .github/workflows/build_cmake.yml
  testing/runtests.py
Labels: bug, install/build

#8257 Show configuration warnings unconditionally in the doxywizard
  addon/doxywizard/config_msg.cpp
Labels: doxywizard, enhancement

#8265 Remove some build warnings
  src/groupdef.cpp
  src/groupdef.h
  src/index.cpp
Labels: bug, install/build

#8262 Doxygen's own documentation doesn't build with recent LaTeX version
  doc/doxygen_manual.tex
  examples/CMakeLists.txt
  examples/afterdoc.cfg
  examples/author.cfg
  examples/autolink.cfg
  examples/class.cfg
  examples/define.cfg
  examples/diagrams.cfg
  examples/docstring.cfg
  examples/enum.cfg
  examples/example.cfg
  examples/file.cfg
  examples/func.cfg
  examples/group.cfg
  examples/include.cfg
  examples/javadoc-banner.cfg
  examples/jdstyle.cfg
  examples/manual.cfg
  examples/memgrp.cfg
  examples/mux.cfg
  examples/overload.cfg
  examples/page.cfg
  examples/par.cfg
  examples/pyexample.cfg
  examples/qtstyle.cfg
  examples/relates.cfg
  examples/restypedef.cfg
  examples/structcmd.cfg
  examples/tag.cfg
  examples/templ.cfg
Labels: LaTeX, bug, documentation, install/build

#8263 Usage of version and help in addons
  addon/doxmlparser/examples/metrics/CMakeLists.txt
  addon/doxmlparser/examples/metrics/main.cpp
  addon/doxmlparser/test/CMakeLists.txt
  addon/doxmlparser/test/main.cpp
  addon/doxyapp/doxyapp.cpp
  addon/doxyparse/doxyparse.cpp
  addon/doxysearch/CMakeLists.txt
  addon/doxysearch/doxyindexer.cpp
  addon/doxysearch/doxysearch.cpp
Labels: doxmlparser, doxysearch, enhancement

#8239 Update CMakeLists.txt
  CMakeLists.txt
Labels: bug, install/build, needinfo

#8237 Multiple anchors with member-group
  src/memberlist.cpp
Labels: HTML, bug

#8270 Doxygen manual top rule is in uppercase.
  doc/manual.sty
Labels: LaTeX, bug, documentation

#8271 Miscounting of lines in case of inserting an anchor for a "H." tag
  src/markdown.cpp
Labels: Markdown, bug

#8268 Remove warnings from util.cpp
  src/util.cpp
Labels: bug, install/build

#8273 issue #8269 Make failed when building layout.cpp
  src/to_c_cmd.py
Labels: bug, install/build

#8276 Refactoring position of layout_default.xml
  src/CMakeLists.txt
  src/layout.cpp
  src/to_c_cmd.py
  templates/general/layout_default.xml
Labels: enhancement, install/build

#8275 Concatenation of \param text and \details text
  src/doctokenizer.l
Labels: bug

#8277 Miscounting lines in case a fenced code block
  src/markdown.cpp
Labels: Markdown, bug

#8279 archive build artefacts in GitHub Actions
  .github/workflows/build_cmake.yml
Labels: enhancement, install/build

#8284 issue #8282 Error on ALIAS declaration without quotes
  addon/doxywizard/config_doxyw.l
  addon/doxywizard/inputstrlist.cpp
  src/configimpl.l
Labels: bug, doxywizard

#8288 issue #8286 Incorrect processing of VHDL strings (comment part)
  src/commentcnv.l
Labels: VHDL, bug

#8285 Layout in doxywizard documentation
  src/latexdocvisitor.cpp
Labels: bug, documentation, doxywizard

#8287 issue #8286 Incorrect processing of VHDL strings
  src/commentcnv.l
Labels: VHDL, bug
