Repository doxygen/doxygen, pull requests merged in 2020-02, with the labels that each got.

#7553 More accurate warning message.
  src/docparser.cpp
Labels: bug

#7529 Correct handling of error / removed debug statement
  src/vhdldocgen.cpp
Labels: VHDL, bug

#7534 Bug 791390 - Table formatting information ignored in Doxygen XML output
  src/docbookvisitor.cpp
  src/xmldocvisitor.cpp
  templates/xml/compound.xsd
Labels: XML, bug

#7577 More indicative warning for wrong nesting of sections
  src/docparser.cpp
Labels: enhancement

#7576 Problem with links from search index files
  src/searchindex.cpp
Labels: HTML, bug

#7571 vhdl-fixed-bug-7432
  src/vhdldocgen.cpp
  src/vhdldocgen.h
  src/vhdljjparser.cpp
  src/vhdljjparser.h
  vhdlparser/vhdlparser.jj
Labels: VHDL, bug

#7591 issue #7590 Map .f18 filetype to Fortran
  doc/starting.doc
  src/config.xml
  src/util.cpp
Labels: Fortran, enhancement

#7594 Doxywizard unknown configuration enum values
  addon/doxywizard/config_doxyw.l
  addon/doxywizard/inputstring.cpp
  addon/doxywizard/inputstring.h
Labels: bug, doxywizard

#7592 Remove some unused enums in doxywizard
  addon/doxywizard/wizard.h
Labels: bug, doxywizard

#7569 issue #7558 PlantUML: Different behavior whether LATEX_OUTPUT has a final slash or not.
  src/plantuml.cpp
  src/plantuml.h
Labels: bug

#7596 Creation of svg images for formulas with inkscape
  src/config.xml
  src/formula.cpp
  src/portable.cpp
  src/portable.h
Labels: HTML, bug

#7603 Problem in case using PREDEFINED with comma
  src/configimpl.l
Labels: bug

#7607 issue #7606 Unable to build "master" branch
  src/sqlite3gen.cpp
Labels: bug, install/build

#7610 Specifying filename in preprocessor debug output
  src/pre.l
Labels: enhancement

#7608 Compilation warnings
  src/definition.h
  src/docparser.h
  src/doxygen.h
  src/entry.h
  src/outputlist.h
  src/util.h
Labels: bug, install/build

#7601 Disappearing words in RTF output after a list
  src/rtfdocvisitor.cpp
Labels: RTF, bug

#7617 Incorrect handling of typedef in combination with const
  src/scanner.l
Labels: C/C++, bug

#7616 Removing warnings from doxygen internal documentation
  Doxyfile
  src/htmlgen.cpp
  src/parserintf.h
  src/util.cpp
Labels: bug

#7619 Problem in case using PREDEFINED with comma and using +=
  src/configimpl.l
Labels: bug

#7618 Problem with temporary / intermediate directory in doxyparse
  addon/doxyparse/doxyparse.cpp
Labels: bug

#7612 issue #7583 External Links in Inheritance Diagrams open in the Image Frame.
  src/diagram.cpp
  src/dotfilepatcher.cpp
  src/util.cpp
  src/util.h
Labels: HTML, bug

#7184 Opening and ending tag mismatch: tbody in docbook output
  src/docbookvisitor.cpp
Labels: DocBook, bug
