Repository doxygen/doxygen, pull requests merged in 2020-08, with the labels that each got.

#7937 Misleading warning about missing argument
  src/commentscan.l
Labels: bug, enhancement

#7817 Creating chm files for doxygen tests
  src/configimpl.l
  src/htmlhelp.cpp
  src/htmlhelp.h
Labels: HTML, bug

#7938 Compiler warning in htmlhelp.cpp
  src/htmlhelp.cpp
Labels: bug, install/build

#7940 Travis does not terminate on error on non last command inside if construct
  .travis.yml
Labels: bug, install/build

#7863 Setting correct babel packages for some languages
  src/translator_sc.h
  src/translator_tr.h
  src/translator_za.h
Labels: LaTeX, bug

#7813 Vhdl improvements (ALIAS, translation)
  src/translator.h
  src/translator_adapter.h
  src/translator_br.h
  src/translator_de.h
  src/translator_en.h
  src/translator_nl.h
  src/translator_pt.h
  src/translator_sv.h
  vhdlparser/VhdlParserTokenManager.cc
  vhdlparser/vhdlparser.jj
Labels: VHDL, enhancement, needinfo

#7950 Spelling corrections is comments
  cmake/Sanitizers/sanitize-helpers.cmake
  src/cite.cpp
  src/context.cpp
  src/markdown.cpp
  testing/CMakeLists.txt
Labels: bug, install/build

#7575 Using Python docstrings
  doc/docblocks.doc
  src/config.xml
  src/pyscanner.l
Labels: Python, documentation, enhancement

#7959 Updated the swedish language translation to 1.8.19
  src/translator_sv.h
Labels: bug

#7955 Layout on the bibliography page
  templates/html/doxygen.css
Labels: HTML, enhancement

#7961 Building documentation after changing language files
  doc/CMakeLists.txt
  doc/language.tpl
  doc/translator.py
Labels: bug, documentation, install/build

#7962 Spelling correction
  doc/language.tpl
Labels: bug, documentation

#7966 Format for size_t (in e.g. warnings)
  src/doxygen.cpp
Labels: bug, install/build

#7968 Format for size_t (in e.g. warnings)
  src/doxygen.cpp
Labels: bug, install/build

#7972 issue #7970 Doxygen doesn't stop on errors
  src/message.cpp
Labels: bug

#7976 bug_786382 Unmatched single quote in C++ source breaks aliases
  src/code.l
  src/commentcnv.l
Labels: C++14, enhancement

#7874 issue #7872 A define containing a doxygen start of comment breaks the parser
  src/code.l
  src/pre.l
Labels: C/C++, bug

#7981 bug_647654 Special command \fn fails when first argument of PHP function is call-by-reference
  src/declinfo.l
  src/scanner.l
Labels: PHP, bug
