Repository doxygen/doxygen, pull requests merged in 2020-11, with the labels that each got.

#8149 64-bit Windows compiler warnings doctokinizer.l
  src/doctokenizer.l
Labels: bug, install/build

#8150 Handling of "Cancel" during "Quit" in doxywizard
  addon/doxywizard/doxywizard.cpp
Labels: bug, doxywizard

#8152 Incorrect checking between default and used values for strList in doxywizard
  addon/doxywizard/inputstrlist.cpp
Labels: bug, doxywizard

#8151 Documentation correction for CASE_SENSE_NAMES
  src/config.xml
Labels: bug, documentation

#8161 issue #8160 Example in documentation of ALIASES shows using `\n` instead of `^^`
  doc/custcmd.doc
Labels: bug, documentation

#8157 issue #8156 Markdown anchors do not work with special symbols in path
  src/markdown.cpp
Labels: Markdown, bug

#8154 Handling Enable / Disable menu items (doxywizard)
  addon/doxywizard/doxywizard.cpp
  addon/doxywizard/doxywizard.h
Labels: doxywizard, enhancement

#8162 Syntax for faq about use in Windows Powershell
  doc/faq.doc
Labels: bug, documentation

#8128 Incorrect handling of string with spaces and no quotes
  addon/doxywizard/config_doxyw.l
  addon/doxywizard/doxywizard.cpp
  addon/doxywizard/doxywizard.h
  addon/doxywizard/inputbool.cpp
  addon/doxywizard/inputint.cpp
  src/configimpl.l
Labels: bug

#8168 Typo in namespacedef.h
  src/namespacedef.h
Labels: bug

#8166 Doxygen crashes on Fortran
  src/fortranscanner.l
Labels: Fortran, bug

#8170 issue #8169 "\emoji heavy_check_mark" produces ✓ instead of ✔️
  src/htmldocvisitor.cpp
  templates/html/doxygen.css
Labels: HTML, enhancement

#8165 Update of doxywizard documentation
  doc/CMakeLists.txt
  doc/Doxyfile
  doc/doxywizard.gif
  doc/doxywizard_expert.png
  doc/doxywizard_main.png
  doc/doxywizard_menu.png
  doc/doxywizard_menu_file.png
  doc/doxywizard_menu_help.png
  doc/doxywizard_menu_settings.png
  doc/doxywizard_page1.png
  doc/doxywizard_page2.png
  doc/doxywizard_page3.png
  doc/doxywizard_page4.png
  doc/doxywizard_run.png
  doc/doxywizard_usage.doc
  doc/expert_bool.png
  doc/expert_enum.png
  doc/expert_int.png
  doc/expert_list_dir.png
  doc/expert_list_file.png
  doc/expert_list_filedir.png
  doc/expert_list_string.png
  doc/expert_string_dir.png
  doc/expert_string_file.png
  doc/expert_string_image.png
  doc/expert_string_string.png
  doc/manual.sty
Labels: bug, documentation, doxywizard

#8175 Show QT version in doxywizard
  addon/doxywizard/doxywizard.cpp
Labels: doxywizard, enhancement

#8173 Unclear description of QHG_LOCATION
  src/config.xml
Labels: bug, documentation

#8180 Redundant storage of `VhdlParser_adj.cc`, it can be regenerated
  vhdlparser/CMakeLists.txt
  vhdlparser/VhdlParser_adj.cc
Labels: enhancement, install/build

#8179 Missing commands in list of commands documentation
  doc/commands.doc
Labels: bug, documentation

#8183 Silently ignoring unexpected characters in configuration
  src/configimpl.l
Labels: bug

#8190 Incorrect line count in case of an error in msc input
  libmscgen/mscgen_language.y
  libmscgen/mscgen_lexer.h
  libmscgen/mscgen_lexer.l
Labels: bug

#8187 issue #8186 Path resolving breaks on included @ sign
  src/doctokenizer.l
Labels: bug

#8176 XHTML: div tag not possible as part of a p tag.
  src/htmldocvisitor.cpp
  templates/html/doxygen.css
Labels: HTML, bug

#8201 Update of testing README.txt
  testing/README.txt
Labels: bug

#8200 issue #8184 Bad parsing of CMakeLists.txt
  addon/doxywizard/expert.cpp
  doc/starting.doc
  src/config.xml
Labels: bug, enhancement

#8194 Doxygen warnings are not seen as errors during running tests
  testing/057/namespacelibrary.xml
  testing/057/namespacelibrary_1_1v1.xml
  testing/057/namespacelibrary_1_1v2.xml
  testing/057_inlinenamespace.cpp
  testing/runtests.py
Labels: bug, install/build

#8198 Making the use of DOT_CLEANUP more transparent
  doc/commands.doc
  src/config.xml
  src/docbookvisitor.cpp
Labels: DocBook, bug, documentation

#8196 Exclude markdown mapped documentation files from Files list
  doc/docblocks.doc
  src/filedef.cpp
Labels: Markdown, bug

#8203 Default doxygen search mechanism doesn't work when using with XHTML output
  src/searchindex.cpp
  templates/html/htmlsearchresult.tpl
  templates/html/search.js
Labels: HTML, bug

#8209 Missing \noop in list with commands starting with "\n" for escaping in aliases
  src/doxygen.cpp
Labels: bug

#8210 Line miscount in case of Html type Comment
  src/commentscan.l
Labels: bug

#8213 Convert http to https for main doxygen website. Closes #8212
  INSTALL
  addon/doxywizard/doxywizard.cpp
  doc/emojisup.doc
  doc/faq.doc
  doc/index.doc
  doc/install.doc
  doc/starting.doc
  src/doxygen.md
  src/htmlgen.cpp
  templates/html/footer.html
  templates/html/htmlbase.tpl
  testing/031/indexpage.xml
  testing/031_image.dox
Labels: HTML, documentation, enhancement
