Repository doxygen/doxygen, pull requests merged in 2020-04, with the labels that each got.

#7684 Fixed section type setting for index page from tags file.
  src/tagreader.cpp
Labels: HTML, bug

#7032 Relative markdown file reference
  src/markdown.cpp
Labels: Markdown, enhancement

#7693 issue #7692 \copydoc does not work with file paths including dots
  src/docparser.cpp
Labels: bug

#7691 Link in case of comma at end of URL
  src/doctokenizer.l
Labels: bug

#7697 Text show as formula when USE_MATHJAX=YES
  src/htmldocvisitor.cpp
  src/htmlgen.cpp
Labels: HTML, bug

#7716 Wrong message in case of svg formulas for HTML
  src/formula.cpp
Labels: bug

#7722 Incorrect text for HTML_FORMULA_FORMAT in documentation / Doxyfile
  src/config.xml
Labels: bug, documentation

#7713 Add doxygen version information to tag file
  src/doxygen.cpp
  src/tagreader.cpp
Labels: enhancement

#7712 Undefined control sequence for formula using MathJax
  src/code.l
Labels: HTML, bug

#7726 Inconsistent behavior between `///` and `//!` for formulas
  src/commentcnv.l
Labels: C/C++, bug
