Repository doxygen/doxygen, pull requests merged in 2020-05, with the labels that each got.

#7745 Input buffer overflow in php input code
  src/scanner.l
Labels: C/C++, PHP, bug

#7744 Users cannot set "enhancement label" on github.
  doc/index.doc
Labels: bug, documentation

#7765 Running Inkscape 1.0
  src/formula.cpp
Labels: bug

#7748 issue #7747 Three-way comparison operator
  src/code.l
  src/doctokenizer.l
  src/doxygen.cpp
  src/scanner.l
Labels: C++2x, enhancement

#7766 issue #7762 C# mode completely broken
  src/util.cpp
Labels: bug

#7754 issue #7753: SVG formula all with zero width
  src/formula.cpp
Labels: bug

#7750 sqlite3gen: defend text binds against junk data
  src/sqlite3gen.cpp
Labels: bug

#7742 issue #7734 Incorrect parsing of Q_PROPERTY
  src/scanner.l
Labels: bug

#7740 issue #7738 \todo ignores EXCLUDE_SYMBOLS
  src/reflist.cpp
Labels: bug

#7682 Link fixed in documentation
  doc/autolink.doc
Labels: bug, documentation

#7559 Plantuml has problems with output directories ending with directory separator
  src/plantuml.cpp
Labels: bug

#7771 fixed if-generate-bug 7721
  vhdlparser/vhdlparser.jj
Labels: VHDL, bug

#7770 GNU compilation warnings
  cmake/CompilerWarnings.cmake
Labels: bug, install/build

#7790 issue #7595 Links from one Markdown file to another do not work
  src/markdown.cpp
Labels: Markdown, bug

#7800 Compilation error on debug compilation of constexp.l
  src/constexp.l
Labels: bug, install/build

#7801 Better warning for non documented struct
  src/memberdef.cpp
Labels: bug

#7806 Warning in case of multiple python documentation sections.
  src/pyscanner.l
Labels: Python, bug

#7776 Change of git version input file was not taken into account
  cmake/git_watcher.cmake
Labels: bug, install/build

#7814 Empty enum setting in configuration file
  src/configimpl.l
Labels: bug
