Repository doxygen/doxygen, pull requests merged in 2020-09, with the labels that each got.

#7997 issue #7995 Doxygen doesn't handle very simple example in the .md file
  src/fortrancode.l
  src/sqlcode.l
  src/vhdlcode.l
Labels: Fortran, VHDL, bug

#7998 issue #7996 \ref commands broken in markdown tables
  src/markdown.cpp
Labels: Markdown, bug

#8012 Not always linking in map as maps use name instead of id
  src/dotfilepatcher.cpp
Labels: bug

#8008 Consistency in documentation of used Python versions
  doc/install.doc
  doc/translator.py
Labels: bug, documentation

#8007 Readability of warning message
  src/doxygen.cpp
Labels: enhancement

#8013 Double "->" in warning in case of trailing return type
  src/util.cpp
Labels: C++11, C/C++, bug

#8020 Make testsqlite3.py python script running with python 3
  testing/testsqlite3.py
Labels: bug

#8019 issue #8017 C++: mishandling of brackets used in trailing return types
  src/scanner.l
Labels: C++11, C/C++, bug

#8016 issue #8015 Special command \skip and \until no longer functional in ALIASES
  src/doctokenizer.l
Labels: bug

#8014 issue #6442 C++: Trailing return type syntax + void
  src/memberdef.cpp
Labels: C++11, C/C++, bug

#8036 Allow building doxygen as a subproject
  CMakeLists.txt
  addon/doxmlparser/src/CMakeLists.txt
  addon/doxmlparser/test/CMakeLists.txt
  addon/doxyapp/CMakeLists.txt
  addon/doxyparse/CMakeLists.txt
  addon/doxysearch/CMakeLists.txt
  addon/doxywizard/CMakeLists.txt
  cmake/Coverage.cmake
  cmake/doxygen_version.cmake
  cmake/git_watcher.cmake
  doc/CMakeLists.txt
  examples/CMakeLists.txt
  libmscgen/CMakeLists.txt
  libversion/CMakeLists.txt
  src/CMakeLists.txt
  testing/CMakeLists.txt
  vhdlparser/CMakeLists.txt
Labels: bug, install/build

#8003 Command \ilinebr remained
  src/commentscan.l
Labels: bug

#8004 Warning about end of list in brief description after alias `^^` replacement
  src/definition.cpp
Labels: bug

#8041 Line count mismatch for Python
  src/commentscan.l
  src/pyscanner.l
Labels: Python, bug

#8000 Fortran comments with C comments inside
  src/commentcnv.l
Labels: Fortran, bug

#8048 Mismatch documentation and build system
  doc/arch.doc
Labels: bug, documentation, install/build

#8058 issue #8053 error: Attribute target redefined in SVG
  src/dotfilepatcher.cpp
Labels: HTML, bug

#8052 #8051 Consider documenting debug options of doxygen
  src/doxygen.cpp
Labels: enhancement

#8045 Miscounting of lines in case of fenced code block
  src/markdown.cpp
Labels: Markdown, bug

#8064 Incorrect sorting of reflist items
  src/reflist.cpp
Labels: bug

#8060 No warning for unbalanced brackets in markdown
  src/markdown.cpp
Labels: Markdown, bug
