Repository doxygen/doxygen, pull requests merged in 2020-07, with the labels that each got.

#7891 issue #7890 Macro Expansion broken
  src/pre.l
Labels: bug

#7885 Misleading compiler warning
  src/vhdldocgen.cpp
Labels: bug, install/build

#7888 Scalable search bar for high resolution displays
  src/htmlgen.cpp
  templates/html/close.svg
  templates/html/htmlbase.tpl
  templates/html/htmllayout.tpl
  templates/html/htmltabs.tpl
  templates/html/mag.svg
  templates/html/mag_sel.svg
  templates/html/menu.js
  templates/html/search.css
  templates/html/search.js
Labels: HTML, enhancement

#7896 Compilation warning in debug.cpp
  src/debug.cpp
  src/debug.h
  src/doxygen.cpp
  src/message.cpp
Labels: bug, install/build

#7878 remove vhdlparser/Makefile
  vhdlparser/CMakeLists.txt
  vhdlparser/Makefile
Labels: VHDL, bug, install/build

#7875 No default rule present in commentcnv.l
  src/commentcnv.l
Labels: bug

#7895 Superfluous space in "TEST_FLAGS"
  testing/runtests.py
Labels: bug, install/build

#7889 Missing last item in htmlhelp level2 index
  src/htmlhelp.cpp
Labels: HTML, bug

#7903 issue #6846 Doxygen parsing global variable as function in certain cases
  src/memberdef.cpp
Labels: C/C++, bug

#7882 Missing links in Fortran in case use statement with upper case characters in name
  src/fortranscanner.l
Labels: Fortran, bug

#7870 Correct misspelling in config.xml
  src/config.xml
Labels: bug

#7864 improve using plantuml for vhdl flowcharts
  src/vhdldocgen.cpp
  src/vhdljjparser.cpp
Labels: VHDL, bug, enhancement

#7908 Unused variable in code (VHDL)
  src/vhdldocgen.cpp
Labels: VHDL, bug, install/build

#7788 issue #7787 Doxygen 1.8.18: Markdown tables not working in ALIASES anymore?
  src/markdown.cpp
Labels: Markdown, bug

#7925 issue #7923 source line numbers in warnings output by parser are off by 1
  src/fortranscanner.l
  src/markdown.cpp
  src/markdown.h
  src/pyscanner.l
  src/scanner.l
  src/vhdljjparser.cpp
Labels: bug

#7869 issue #7865 Update documentation of USE_PDFLATEX option
  src/config.xml
Labels: LaTeX, bug, documentation

#7893 issue #7884 Python to xml: Whitespace in method doc not preserved (MARKDOWN_SUPPORT=NO)
  src/pyscanner.l
Labels: Python, bug

#7881 More flexible and correct detection of direction of an argument
  src/doctokenizer.l
  src/util.cpp
Labels: C/C++, bug, enhancement

#7935 Incorrect representation of citation
  templates/html/bib2xhtml.pl
Labels: bug

#7936 Debug facility for the \cite command
  src/cite.cpp
  src/debug.cpp
  src/debug.h
  templates/html/bib2xhtml.pl
Labels: enhancement

#7932 crossref citations are shown unconditionally
  src/cite.cpp
Labels: bug
