Repository doxygen/doxygen, pull requests merged in 2021-03, with the labels that each got.

#8405 Spelling correction
  src/regex.cpp
  src/regex.h
Labels: bug

#8348 Missing CLANG dependency
  src/config.xml
Labels: bug

#8387 Strange HTML tab title in case of a page without title
  src/doxygen.cpp
  src/pagedef.cpp
Labels: HTML, bug

#8394 Correction end tag in documentation
  doc/trouble.doc
Labels: bug, documentation

#8395 issue #8390 Reusing documentation snippets
  src/docparser.cpp
Labels: Markdown, bug

#8410 Problems generating chm documentation
  src/htmlhelp.cpp
Labels: HTML, bug, documentation

#8411 Issue #8405 Dead link in documentation
  doc/install.doc
  src/config.xml
Labels: bug, documentation

#8412 Missing build note for sqlite3
  src/config.xml
Labels: bug, documentation

#8398 Correction compilation warnings
  src/context.cpp
  src/docsets.cpp
  src/pre.l
Labels: bug, install/build

#8438 Building Cygwin version of doxygen fails
  src/filesystem.hpp
Labels: bug, install/build

#8439 Correcting spelling errors in filesystem.hpp
  src/filesystem.hpp
Labels: bug

#8407 Spelling correction
  src/defargs.l
Labels: bug

#8446 Regression: dead code in classdef.cpp
  src/classdef.cpp
Labels: bug

#8447 Regression: dead code in configimpl.l
  src/configimpl.l
Labels: bug

#8445 Some regressions on the template approach
  src/context.cpp
  templates/html/htmllayout.tpl
Labels: bug

#8454 Fix deadlock when using `WARN_AS_ERROR = YES`.
  src/message.cpp
Labels: bug

#8453 Maintenance of .gitignore
  .gitignore
Labels: bug, install/build

#8451 Maintenance doxygen internal Doxyfiles
  Doxyfile
  qtools/Doxyfile
Labels: install/build

#8456 Problem with empty buffer in pyscanner.l
  src/pyscanner.l
Labels: bug

#8461 Remove not used file
  doc/CMakeLists.txt
  doc/install_prefix
Labels: bug, install/build

#8459 Removing some left over qtools
  Doxyfile
  addon/doxywizard/CMakeLists.txt
  vhdlparser/CMakeLists.txt
Labels: bug, install/build

#8460 Environment variabelen in changelog
  doc/changelog.doc
Labels: bug, documentation

#8466 issue #8465 Parens in return type template are dropped
  src/scanner.l
Labels: C/C++, bug

#8468 Consistency with other debug messages
  libxml/xml.l
Labels: bug

#8467 Incorrect DOXYFILE_ENCODING upon update
  src/configimpl.l
Labels: bug
