Repository doxygen/doxygen, pull requests merged in 2021-07, with the labels that each got.

#8634 Incorrect line number in warnings in case of if command
  src/cmdmapper.cpp
  src/cmdmapper.h
  src/commentscan.l
  src/docparser.cpp
  src/docparser.h
  src/doctokenizer.h
  src/doctokenizer.l
Labels: bug

#8644 issue #8642 invalid argument for command iline
  src/docparser.cpp
  src/doctokenizer.l
Labels: bug

#8643 Issue #8640: replaced spaces in front of lines in python examples with css margin
  src/htmlgen.cpp
  templates/html/doxygen.css
Labels: HTML, bug

#8609 List item problem
  src/doctokenizer.l
Labels: bug

#8650 issue #8648 positioning at line anchors is disturbed by the navigation bar
  src/htmldocvisitor.cpp
  src/htmlgen.cpp
Labels: HTML, bug

#8627 Empty / obsolete file removed
  src/qtbc.h
Labels: bug, install/build

#8651 bug_464997 Commandline-parameter for quiet operation
  src/config.h
  src/configimpl.l
  src/doxygen.cpp
Labels: enhancement

#8653 QUIET=YES doesn't work anymore
  src/configimpl.l
Labels: bug

#8658 startuml documentation
  doc/commands.doc
Labels: bug, documentation

#8673 issue #8649 doxygen with php make ugly array parameter output
  src/defargs.l
  src/scanner.l
Labels: PHP, bug

#8667 Correct line count and handling of inline comments for macro definitions
  src/pre.l
Labels: bug

#8674 Missing rule in defargs.l
  src/defargs.l
Labels: PHP, bug

#8675 bug_782262 Friend functions returning decltype(auto) not inserted in the "friends" group
  src/code.l
  src/scanner.l
Labels: C++11, C/C++, bug

#8678 issue #8633 Line break in C++ nested-name confuses doxygen
  src/scanner.l
Labels: C/C++, bug

#8677 PlantUML cached information
  src/config.xml
  src/plantuml.cpp
  src/plantuml.h
Labels: bug

#8676 Warning message in case of preprocesssor macro substitution
  src/pre.l
Labels: C/C++, bug

#8685 LaTeX warning in test 26
  src/latexdocvisitor.cpp
Labels: LaTeX, bug

#8696 Spelling correction for variant.h
  src/variant.h
Labels: bug

#8695 Incorrect line count on warning for \snippet and missing warning for \snippet{doc}
  src/docparser.cpp
  src/doctokenizer.l
Labels: bug

#8699 Spelling correction for variant.h (2)
  src/variant.h
Labels: bug

#8698 Incorrect debug statements in docbookgen
  src/docbookgen.cpp
  src/docbookgen.h
Labels: DocBook, bug

#8700 Warnings running doxygen on its own internal documentation
  src/dotfilepatcher.cpp
Labels: HTML, bug
