Repository doxygen/doxygen, pull requests merged in 2021-04, with the labels that each got.

#8479 Update ghostscript version
  .github/workflows/build_cmake.yml
Labels: install/build

#8481 Determine ghostscript directory (Windows)
  .github/workflows/build_cmake.yml
Labels: enhancement, install/build

#8486 issue #8485 The browser based search doesn't handle underscores correctly
  src/searchindex.cpp
  src/util.h
Labels: HTML, bug

#8491 remove a double "the"
  doc/commands.doc
Labels: bug, documentation

#8500 Written layout file was empty
  src/layout.cpp
Labels: bug

#8514 No warning for incorrect ALIASES
  src/configimpl.l
Labels: bug

#8502 Coverity warnings
  src/template.cpp
  src/utf8.cpp
Labels: bug

#8424 Usage of default lex rule with `\param`
  src/commentscan.l
Labels: bug

#8430 issue #8425 Would like a way to sort class list but not brief member list
  src/namespacedef.cpp
Labels: bug

#8516 Problem with Fortran, giving a warning about invalid state
  src/fortranscanner.l
Labels: Fortran, bug

#8520 Fix typos
  src/config.xml
Labels: bug, documentation

#8519 issue #8518 tag </programlisting> was inserted before </highlight> parsing python file to xml
  src/pycode.l
  src/pyscanner.l
Labels: Python, XML, bug

#8496 issue #7346 Incompatibility with MathJax 3.0
  src/config.xml
  src/configimpl.l
  src/htmlgen.cpp
Labels: HTML, enhancement

#8421 Better handling of rules in lex scanners
  src/lexcode.l
  src/lexscanner.l
Labels: bug

#8420 Better handling of option possibility in lex scanner
  src/lexscanner.l
Labels: bug

#8513 Error messages on ASSERTS
  src/qcstring.h
Labels: bug

#8510 issue #8505 Local search too specific
  doc/searching.doc
Labels: bug, documentation

#8504 Warning from preprocessor regarding binary literals
  src/constexp.l
  src/constexp.y
  src/cppvalue.cpp
  src/cppvalue.h
Labels: C++14, C/C++, bug

#8524 issue #8518 tag </programlisting> was inserted before </highlight> parsing cpp file to xml
  src/code.l
Labels: C/C++, XML, bug

#8512 issue #8511 Java: linebreak after @link can cause wrong parsing of subsequent doc
  src/doctokenizer.l
Labels: Java, bug

#8523 issue #8522 Javadoc: type attribute of ordered lists not preserved
  src/docbookvisitor.cpp
  src/latexdocvisitor.cpp
  src/mandocvisitor.cpp
  src/mandocvisitor.h
  src/perlmodgen.cpp
  src/printdocvisitor.h
  src/rtfdocvisitor.cpp
  src/rtfstyle.h
  src/util.cpp
  src/util.h
  src/xmldocvisitor.cpp
  templates/latex/doxygen.sty
  templates/xml/compound.xsd
Labels: DocBook, LaTeX, Man, RTF, XML, bug

#8352 Incorrect code coloring of typedef
  src/code.l
Labels: C/C++, bug

#8337 issue #8336 Python class only with async methods support
  src/pycode.l
  src/pyscanner.l
Labels: Python, enhancement

#8332 issue #8329 Force line buffering
  doc/faq.doc
  src/doxygen.cpp
  src/doxygen.h
Labels: documentation, enhancement

#8463 Write out used settings when generating XML output
  src/config.h
  src/configimpl.h
  src/configimpl.l
  src/xmlgen.cpp
  templates/xml/doxyfile.xsd
  testing/runtests.py
Labels: XML, enhancement

#8501 Some documentation improvements
  doc/commands.doc
  src/config.xml
  src/configgen.py
Labels: bug, documentation

#8526 Spelling corrections
  src/config.h
  src/configimpl.h
  src/doxygen.cpp
Labels: bug

#8527 issue #8525 Links aren't properly rendered when preceded by quoted text
  src/doctokenizer.l
Labels: bug
