Repository doxygen/doxygen, pull requests merged in 2021-05, with the labels that each got.

#8478 Extending startuml with extra figure types
  doc/commands.doc
  src/docbookvisitor.cpp
  src/docparser.cpp
  src/docparser.h
  src/doctokenizer.l
  src/htmldocvisitor.cpp
  src/latexdocvisitor.cpp
  src/plantuml.cpp
  src/plantuml.h
  src/rtfdocvisitor.cpp
  src/vhdldocgen.cpp
Labels: enhancement

#8530 Spelling correction
  doc/commands.doc
Labels: bug, documentation

#8509 Problems with some commands in MathJax
  doc/Doxyfile
  doc/commands.doc
  doc/formulas.doc
  src/commentcnv.l
  src/commentscan.l
  src/docparser.h
  src/htmldocvisitor.cpp
  src/lexcode.l
  src/lexscanner.l
  src/markdown.cpp
  src/pre.l
  src/scanner.l
Labels: bug

#8327 Incorrect type for enum struct
  src/entry.h
  src/memberdef.cpp
  src/memberdef.h
  src/memberlist.cpp
  src/scanner.l
Labels: bug

#8333 bug_305773 Volatile declaration is missing for variables in XML output
  src/doxygen.cpp
  src/scanner.l
  src/sqlite3gen.cpp
  src/symbolresolver.cpp
  src/util.cpp
  src/xmlgen.cpp
Labels: XML, bug

#8349 Incorrect line count for normal comment in define
  src/pre.l
Labels: C/C++, bug

#8422 Problem with non escaped double quote in preprocessor
  src/pre.l
Labels: bug

#8369 Support vertical alignment in a multi-row HTML cell to LaTex
  src/docparser.cpp
  src/docparser.h
  src/latexdocvisitor.cpp
Labels: LaTeX, enhancement

#8431 Warnings regarding Internal inconsistency: namespace in IDL
  src/namespacedef.cpp
Labels: bug

#8538 Missing page when followed by mainpage
  src/commentscan.l
Labels: bug

#8533 Adding field extern for sqlite output
  src/sqlite3gen.cpp
Labels: bug

#8548 Formulas with a new environment handled as inline formulas
  src/docparser.h
Labels: bug

#8557 Issue #8556 Removed bracket '(' in HTML an XML output
  src/scanner.l
Labels: C/C++, bug

#8555 Incorrect handling normal C comment in comment converter
  src/commentcnv.l
Labels: C/C++, bug

#8550 Inconsistent behavior between unknown command and unknown html entity
  src/docparser.cpp
Labels: bug

#8549 Empty class definition.
  src/htmldocvisitor.cpp
Labels: bug

#8544 issue #8542 Variadic macro expansion
  src/pre.l
Labels: C/C++, bug

#8562 Using spaces in a PREDEFINED setting
  src/pre.l
Labels: C/C++, bug

#8565 issue #8564 input buffer overflow, can't enlarge buffer because scanner uses REJECT
  src/pycode.l
  src/pyscanner.l
Labels: Python, bug

#8554 Extra settings for MathJax V3
  src/htmlgen.cpp
  templates/html/header.html
  templates/html/htmlbase.tpl
Labels: HTML, bug

#8553 issue #8552 Javadoc: strange issue with @verbatim ... @endverbatim
  src/commentscan.l
  src/lexcode.l
  src/lexscanner.l
  src/scanner.l
Labels: bug

#8545 issue #8541 Javadoc: external links to classes in java.lang are not resolved
  src/scanner.l
Labels: Java, bug

#8566 issue #8563 Link not created and the Doxygen comment is placed in the output improperly
  doc/docblocks.doc
Labels: documentation, enhancement

#8543 Confusing debug output for markdown
  src/markdown.cpp
  src/markdown.h
Labels: Markdown, bug
