Repository doxygen/doxygen, pull requests merged in 2021-08, with the labels that each got.

#8621 issue #8617 XML: Issue with $ sign in Java identifiers
  src/code.l
  src/commentscan.l
  src/declinfo.l
  src/defargs.l
  src/doctokenizer.l
  src/lexcode.l
  src/lexscanner.l
  src/scanner.l
  src/util.cpp
  src/util.h
Labels: enhancement, Java

#8671 bug_172256 Todo stops at first sentence.
  src/commentscan.l
Labels: bug

#8687 issue #8680 Markdown links going via tag files instead of local resolution
  src/commentscan.l
  src/doxygen.cpp
  src/util.cpp
Labels: enhancement

#8603 Missing anchors to source code in RTF
  testing/runtests.py
Labels: bug, RTF

#8606 issue #8604 `LATEX_BATCHMODE` not used for formulas anymore
  src/config.xml
  src/formula.cpp
Labels: bug

#8579 Incorrect warning for \ref comand
  src/doctokenizer.l
Labels: bug

#8719 issue #8713 external markdown links do not respect EXT_LINKS_IN_WINDOW
  src/markdown.cpp
Labels: bug

#8720 issue #8718 Miss-classifying public field when using coma to initialize several at once in C#.
  src/scanner.l
Labels: bug, C#

#8691 Equation reference for formulas missing for HTML / Docbook / RTF
  src/formula.cpp
Labels: bug, HTML, RTF, DocBook

#8705 bug_582617 A @cond @endcond in a single comment block kills the remaining of the comment block.
  doc/commands.doc
Labels: enhancement, documentation

#8692 Add option for an anchor to the image command
  doc/commands.doc
  src/commentscan.l
  src/docparser.cpp
  src/doctokenizer.l
Labels: enhancement

#8664 issue #7195 reserved identifier violation
  addon/doxywizard/inputbool.h
  addon/doxywizard/inputint.h
  addon/doxywizard/inputstring.h
  addon/doxywizard/inputstrlist.h
  examples/diagrams_a.h
  examples/diagrams_b.h
  examples/diagrams_c.h
  examples/diagrams_d.h
  examples/diagrams_e.h
  libmd5/md5_loc.h
  libmscgen/gdfonts.h
  libmscgen/gdfontt.h
  src/bufstr.h
  src/cmdmapper.h
  src/commentcnv.h
  src/constexp.h
  src/constexp_p.h
  src/cppvalue.h
  src/debug.h
  src/dia.h
  src/docbookvisitor.h
  src/docparser.h
  src/doctokenizer.h
  src/docvisitor.h
  src/htmlattrib.h
  src/htmldocvisitor.h
  src/image.h
  src/latexdocvisitor.h
  src/mandocvisitor.h
  src/msc.h
  src/printdocvisitor.h
  src/reflist.h
  src/rtfdocvisitor.h
  src/textdocvisitor.h
  src/xmldocvisitor.h
Labels: install/build

#8659 Incorrect enduml warning message
  src/commentscan.l
Labels: bug

#8494 Usage of HTML BR tag in HTML A tag
  src/docparser.cpp
Labels: bug

#8619 issue #8615 Markdown **emphasis** at the beginning of the line is not rendered.
  doc/markdown.doc
Labels: enhancement, documentation

#8721 Extend testing of RTF tests with test for page references
  testing/runtests.py
Labels: enhancement, install/build

#8725 Updated swedish translation to 1.9.2
  src/translator_sv.h
Labels: bug

#8728 representation of inheritance relations in relation to HAVE_DOT setting
  addon/doxywizard/wizard.cpp
  doc/customize.doc
  src/classdef.cpp
  src/config.xml
  src/context.cpp
  src/layout.cpp
Labels: bug

#8727 Fix unknown pragma warning in MinGW
  src/definition.h
Labels: bug, install/build

#8739 Fix memory corruption in TextStream.
  src/textstream.h
Labels: bug, install/build

#8740 Update of image in respect to doxywizard Diagrams to generate
  doc/doxywizard_page4.png
Labels: bug, documentation

#8745 bug_683640 Docset info.plist file doesn't include feed URL
  src/config.xml
  src/docsets.cpp
Labels: enhancement

#8744 issue #8743 <tt> missinterpreted
  doc/docblocks.doc
Labels: bug, documentation

#8741 issue #8738 Fixed sizes in project area of HTML output
  templates/html/doxygen.css
  templates/html/header.html
  templates/html/htmlbase.tpl
Labels: enhancement, HTML
