Repository doxygen/doxygen, pull requests merged in 2021-01, with the labels that each got.

#8298 issue #8297 fails to parse list of INPUT files
  src/configimpl.l
Labels: bug

#8299 bug_549093 Regular HTML comments are removed.
  doc/htmlcmds.doc
Labels: documentation, enhancement

#8301 Compilation warning in groupdef
  src/groupdef.cpp
Labels: bug, install/build

#8307 Incorrect entries on treeview
  src/markdown.cpp
Labels: Markdown, bug

#8303 Compilation warning in util.cpp
  src/util.cpp
Labels: bug, install/build

#8317 Typeerror when running tests
  testing/runtests.py
Labels: bug, install/build

#8315 issue #8311 Markdown table: double-quote ruins the output
  src/doctokenizer.l
Labels: Markdown, bug

#8323 issue #8322 Random output for markdown xml snippet
  src/xmlcode.l
Labels: XML, bug

#8321 bug_560861 Class graph does not differentiate same classes in different namespace
  src/dotclassgraph.cpp
Labels: bug

#8319 Incorrect HTML sequence
  doc/changelog.doc
Labels: bug, documentation

#8314 issue #8308 Verbatim block followed by markdown header breaks verbatim block
  src/markdown.cpp
Labels: Markdown, bug, enhancement

#8309 bug 668003 Default LaTeX header misses $-placeholders
  src/cite.cpp
  src/cite.h
  src/config.xml
  src/htmlgen.cpp
  src/index.cpp
  src/latexgen.cpp
  src/util.cpp
  src/util.h
  templates/latex/footer.tex
  templates/latex/header.tex
Labels: LaTeX, bug

#8324 sqlcode.l does not compile in LEX debug mode
  src/sqlcode.l
Labels: bug, install/build

#8325 Spelling corrections config
  src/config.xml
Labels: bug, documentation

#8326 Bug when running docbook with debug output
  src/docbookgen.cpp
Labels: DocBook, bug, install/build

#8330 Portuguese translators updated to 1.9.0
  src/translator_br.h
  src/translator_pt.h
Labels: bug

#8339 issue #8338 \until and \skipline don't hide doxygen comments like \skip does
  src/code.l
Labels: bug

#8344 issue #8343 doxygen-1.9.1 crashes when parsing config file (part 2)
  src/configimpl.l
Labels: bug

#8345 Github Actions could not find version 4.0 of MiKTeX
  .github/workflows/build_cmake.yml
Labels: bug, install/build

#8353 Spelling correction
  src/htmlattrib.h
Labels: bug

#8360 Extension during mapping not correctly replaced.
  src/util.cpp
Labels: bug

#8359 issue #8357 XML output does not include cross-references in code-fragments
  src/docbookgen.cpp
  src/docbookvisitor.cpp
  src/docbookvisitor.h
  src/xmldocvisitor.cpp
  src/xmldocvisitor.h
  src/xmlgen.cpp
  testing/014/indexpage.xml
Labels: DocBook, XML, bug

#8368 Add sqlite build for Ubuntu on Github Actions
  .github/workflows/build_cmake.yml
Labels: enhancement, install/build
