Repository doxygen/doxygen, pull requests merged in 2021-12, with the labels that each got.

#8927 Some spelling corrections
  src/markdown.cpp
Labels: bug

#8928 issue #8924 Horizontal scroll bar missing in HTML for wide class="dotgraph" objects
  templates/html/doxygen.css
Labels: bug, HTML

#8929 issue #8925 Java: Issue with enum parsing (xml output)
  src/scanner.l
Labels: bug, Java

#8931 Incorrect markdown links.
  src/markdown.cpp
Labels: bug, Markdown

#8938 issue #8932 XML output: table caption doesn't have ID
  src/docbookvisitor.cpp
  src/rtfdocvisitor.cpp
  src/xmldocvisitor.cpp
  templates/xml/compound.xsd
Labels: bug, RTF, XML, DocBook

#8939 issue #8933 Return type "unsigned int constexpr" not parsed properly
  src/scanner.l
Labels: bug, C/C++, C++17

#8941 issue #8940 Not parsing #if correctly in C++
  src/pre.l
Labels: bug, C/C++

#8945 issue #8935 'make docs' fails when building PDF
  doc/manual.sty
Labels: install/build, documentation

#8944 issue #8934 documentation 'DEP' s.b. 'DEB'
  doc/install.doc
Labels: bug, documentation

#7482 Remove double entry of rtfonly command from list of commands
  src/cmdmapper.cpp
Labels: bug

#8952 bug_772405 *_AUTOBRIEF=YES gobbles end of paragraph from brief
  src/commentscan.l
Labels: bug

#8949 issue #8590 XML: Issue with spacing around <programlisting>
  src/cmdmapper.cpp
  src/cmdmapper.h
  src/commentcnv.l
  src/commentscan.l
  src/docbookvisitor.cpp
  src/docbookvisitor.h
  src/docparser.cpp
  src/docparser.h
  src/doctokenizer.h
  src/doctokenizer.l
  src/htmldocvisitor.cpp
  src/htmldocvisitor.h
  src/latexdocvisitor.cpp
  src/latexdocvisitor.h
  src/lexcode.l
  src/lexscanner.l
  src/mandocvisitor.cpp
  src/markdown.cpp
  src/perlmodgen.cpp
  src/pre.l
  src/printdocvisitor.h
  src/rtfdocvisitor.cpp
  src/scanner.l
  src/util.cpp
  src/util.h
  src/xmldocvisitor.cpp
  templates/html/doxygen.css
  templates/xml/compound.xsd
Labels: bug, enhancement, HTML, LaTeX, RTF, Man, DocBook

#8951 bug_688384 JavaDoc @link does not use code font
  src/cmdmapper.cpp
  src/docparser.cpp
  src/doctokenizer.l
Labels: bug, enhancement, Java

#8490 Improvement of WARN_LOGFILE possibilities
  src/config.xml
  src/message.cpp
Labels: enhancement

#8955 System independent usage of generateDS
  addon/doxmlparser/CMakeLists.txt
  addon/doxmlparser/doxmlparser/compound.py
  addon/doxmlparser/doxmlparser/index.py
  addon/doxmlparser/generateDS_post.py
Labels: bug, install/build

#8954 Correct text in comment
  vhdlparser/vhdl_adj.py
Labels: bug, install/build

#8959 issue #9857 C# incorrect interpretation of '?'-operators
  src/scanner.l
Labels: bug, C#

#8947 Update header.tex
  templates/latex/header.tex
Labels: enhancement, LaTeX

#8961 issue #8956 Section links in markdown mainpage not working
  doc/markdown.doc
  src/markdown.cpp
Labels: enhancement, Markdown

#8960 Latex: allow using percentage numbers for images dimensions
  src/latexdocvisitor.cpp
Labels: enhancement, LaTeX

#8962 Correcting spelling correction
  src/latexdocvisitor.cpp
Labels: bug

#8841 bug_774111 GENERATE_LEGEND with svg graphs
  src/config.xml
Labels: bug, documentation

#8968 bug_365053 Wrong reference to ::classname (in typedef)
  src/scanner.l
Labels: bug, C/C++

#8969 bug_365053 Wrong reference to ::classname
  src/code.l
  src/symbolresolver.cpp
  src/util.cpp
Labels: bug, C/C++

#8967 issue #8965 Allow other names for plantuml.jar
  addon/doxywizard/expert.cpp
  addon/doxywizard/inputstring.cpp
  addon/doxywizard/inputstring.h
  doc/CMakeLists.txt
  doc/doxywizard_usage.doc
  doc/expert_string_filedir.png
  src/config.xml
  src/configgen.py
  src/configimpl.h
  src/configimpl.l
  src/plantuml.cpp
Labels: enhancement

#8970 bug_771606 'doxygen -w' should not require existence of header.html/footer.html even if listed in an options file
  src/config.h
  src/configimpl.l
  src/doxygen.cpp
Labels: bug

#8892 Add the HTML and XML commands to the index
  doc/commands.doc
  doc/htmlcmds.doc
  doc/trouble.doc
  doc/xmlcmds.doc
Labels: enhancement, documentation

#8852 Don't use full path for *file in XML output
  src/xmldocvisitor.cpp
Labels: bug, XML

#8875 Doxygen stops on invalid namespace name
  src/commentscan.l
Labels: bug

#8972 Unmatched tt tag.
  src/doctokenizer.l
Labels: bug

#8964 Set currentCmd for `\relates` / `\related` command
  src/commentscan.l
Labels: bug

#8974 Adding HTML tag <cite>
  addon/doxmlparser/doxmlparser/compound.py
  doc/htmlcmds.doc
  src/cmdmapper.cpp
  src/cmdmapper.h
  src/docbookvisitor.cpp
  src/docparser.cpp
  src/docparser.h
  src/htmldocvisitor.cpp
  src/latexdocvisitor.cpp
  src/mandocvisitor.cpp
  src/perlmodgen.cpp
  src/printdocvisitor.h
  src/rtfdocvisitor.cpp
  src/xmldocvisitor.cpp
  templates/xml/compound.xsd
Labels: enhancement

#8963 bug_791832 \static command not working
  src/doxygen.cpp
  testing/027/struct_object.xml
Labels: bug

#8946 Create an artifact for HTML and Latex documentation
  .github/workflows/build_cmake.yml
Labels: enhancement, install/build, documentation

#8876 Warning on empty \cond statement plus extra empty line.
  src/commentcnv.l
Labels: bug

#8975 Spelling correction
  src/markdown.cpp
Labels: bug, Markdown

#8887 issue #8884 Java: Issue with dotted annotations
  src/scanner.l
Labels: bug, Java

#8886 issue #8882 Java: Issue with virtual as identifier
  src/code.l
  src/scanner.l
Labels: bug, Java

#8904 issue #8898 c#: Inherit documentation from interface property (not working as no docs displayed)
  src/context.cpp
  src/doxygen.cpp
  src/memberdef.cpp
  src/memberdef.h
Labels: bug, C#

#8870 bug_526008 cpp directives in \code fragments breaks subsequent links replacement
  src/code.l
Labels: bug, C/C++

#8576 Better error message in case of a fatal error in a lexer
  src/code.l
  src/commentcnv.l
  src/commentscan.l
  src/configimpl.l
  src/constexp.l
  src/declinfo.l
  src/defargs.l
  src/doctokenizer.l
  src/doxygen_lex.h
  src/fortrancode.l
  src/fortranscanner.l
  src/lexcode.l
  src/lexscanner.l
  src/pre.l
  src/pycode.l
  src/pyscanner.l
  src/scanner.l
  src/sqlcode.l
  src/vhdlcode.l
  src/xmlcode.l
Labels: enhancement

#8837 bug_741992 XML output - "bodyend" inside location tag sometimes prints the wrong row.
  src/pyscanner.l
Labels: bug, Python

#8417 UTF-8 characters in email address
  src/commentcnv.l
  src/commentscan.l
  src/doctokenizer.l
  src/htmldocvisitor.cpp
Labels: bug, enhancement

#8979 Regression on #8974 Adding HTML tag <cite>
  src/docparser.cpp
Labels: bug

#8814 bug_684050 line continuation in (auto)linking
  src/doctokenizer.l
Labels: bug

#8819 issue #8817 If \if, \else or \endif is in a list, the subsequent listentry is not formatted as list entry but in "raw format"
  src/commentscan.l
Labels: bug

#8811 Incorrect xml tags in source code listing (XML output)
  src/xmlgen.cpp
Labels: bug, XML

#8804 Issue #8802 Nested \cond sections are not started
  src/pre.l
Labels: bug

#8871 bug_411629 ifdef-ed namespaces generate "endif" namespace (C#)
  src/scanner.l
Labels: bug, C/C++, C#

#8227 Small correction in help
  testing/README.txt
  testing/runtests.py
Labels: bug, install/build

#8976 Escaped double quotes inside double quotes
  src/doctokenizer.l
Labels: bug

#8984 Differences in spacing and protection
  testing/021/indexpage.xml
  testing/024/indexpage.xml
  testing/031/indexpage.xml
  testing/049/indexpage.xml
  testing/055/md_055_markdown.xml
  testing/076/indexpage.xml
Labels: bug, install/build

#8983 Include qualified names in `<memberdef>`s in XML output
  src/xmlgen.cpp
Labels: enhancement

#8836 bug_774167 Left nav pane
  src/layout.cpp
  src/layout.h
Labels: bug

#8986 Coverity: side_effect_free: Calling countLines(yyscanner) is only useful for its return value, which is ignored.
  src/vhdlcode.l
Labels: bug, VHDL

#8689 issue #7434 Error in LaTeX output of doxygen documentation of VHDL
  src/translator_br.h
  src/translator_de.h
  src/translator_en.h
  src/translator_es.h
  src/translator_fr.h
  src/translator_nl.h
  src/translator_pt.h
  src/translator_sv.h
Labels: bug, VHDL

#8890 HTML tag details
  doc/htmlcmds.doc
  doc/xmlcmds.doc
  src/cmdmapper.cpp
  src/cmdmapper.h
  src/commentscan.l
  src/docbookvisitor.cpp
  src/docparser.cpp
  src/docparser.h
  src/htmldocvisitor.cpp
  src/latexdocvisitor.cpp
  src/mandocvisitor.cpp
  src/perlmodgen.cpp
  src/printdocvisitor.h
  src/rtfdocvisitor.cpp
  src/xmldocvisitor.cpp
  templates/xml/compound.xsd
Labels: enhancement

#8982 bug_693776 @copydoc not working properly
  src/commentscan.l
  src/doxygen.cpp
  src/pagedef.cpp
  testing/043/mypage.xml
Labels: bug

#8987 Create proper links to <details> tag
  addon/doxmlparser/doxmlparser/compound.py
  doc/xmlcmds.doc
Labels: bug, documentation

#8856 Copy original dotfile to output directory in case of DOT_CLEANUP is not set
  src/docbookvisitor.cpp
  src/htmldocvisitor.cpp
  src/latexdocvisitor.cpp
  src/rtfdocvisitor.cpp
Labels: bug, HTML, LaTeX, RTF, DocBook

#8833 bug_792690 Spaces MAKEINDEX_CMD_NAME don't work the same as other config options
  src/latexgen.cpp
  src/util.cpp
  src/util.h
Labels: bug, LaTeX

#8926 bug_712291 A command that will generate a warning during compilation
  doc/commands.doc
  src/commentscan.l
Labels: enhancement

#8869 Handling \code in non doxygen comment
  src/scanner.l
Labels: bug, C/C++

#8879 Coloring of the nodes in the inheritance graph
  src/dotnode.cpp
Labels: bug

#8690 bug_796673 doxygen markdown engine disallow parentheses in image title
  src/markdown.cpp
Labels: bug, Markdown

#8988 Consistent messages regarding enabling settings for VHDL
  src/configimpl.l
Labels: bug, VHDL

#8990 Non initialized member
  src/tagreader.cpp
Labels: bug, install/build

#8993 Wrong line counting in VHDL code with 2008 type comment
  vhdlparser/VhdlParserTokenManager.cc
  vhdlparser/vhdlparser.jj
Labels: bug, VHDL

#8992 Make email obfuscation CSP friendly
  src/htmldocvisitor.cpp
  templates/html/doxygen.css
Labels: HTML

#8994 Missing <VERSION> in description of doxyparse
  addon/doxyparse/README.md
Labels: bug
