Repository doxygen/doxygen, pull requests merged in 2021-09, with the labels that each got.

#8748 issue #8747 Improve output with WARN_AS_ERROR = FAIL_ON_WARNINGS
  src/message.cpp
Labels: enhancement

#8746 Correction of some small documentation problems
  doc/Doxyfile
  doc/perlmod.doc
  src/config.xml
Labels: bug, documentation

#8749 Czech localization update, added all missing czech localization
  src/translator_cz.h
Labels: bug

#8751 Compilation error on Cygwin
  CMakeLists.txt
Labels: bug, install/build

#8754 issue #8753 qhp file corrupt when subsection with no parent section
  src/qhp.cpp
  src/qhp.h
Labels: bug

#8756 issue #8755 :: lost in nested names when using markdown
  src/markdown.cpp
Labels: bug, Markdown

#8758 bug 679192 Missing images from generated qhp file
  src/doxygen.cpp
  src/htmlgen.cpp
Labels: bug

#8729 Bug 722111 - 'function' is displayed as C++ keyword (green) in HTML output
  src/code.l
Labels: bug, C/C++

#8763 No warning in case non existing macro parameter
  src/pre.l
Labels: bug, C/C++

#8771 Warnings when using `CREATE_SUBDIRS` and `HTMLHELP`
  src/htmlhelp.cpp
Labels: bug, HTML

#8769 Also point for questions to Stack overflow
  doc/trouble.doc
Labels: bug, documentation

#8775 Test for setting MAX_DOT_GRAPH_DEPTH not working properly
  src/configimpl.l
Labels: bug

#8780 Incorrect warning regarding SQLITE3 settings
  src/configgen.py
Labels: bug, install/build

#8782 Fix misspelled GENERATE_TREEVIEW
  src/config.xml
Labels: bug, documentation

#8794 Correcting internal documentation for dotdirdeps
  src/dotdirdeps.cpp
Labels: bug, install/build
