Repository doxygen/doxygen, pull requests merged in 2022-11, with the labels that each got.

#9657 `&zwj;` showed up in the documentation
  doc/changelog.doc
  doc/docblocks.doc
  doc/markdown.doc
Labels: bug, documentation

#9645 Removing hierarchy / namespace from layout file results in incorrect RTF / LaTeX document
  src/index.cpp
Labels: bug, LaTeX, RTF

#9658 Small spelling correction
  src/config.xml
Labels: bug, documentation

#9662 issue #9319 Doc build fails with cairo 1.17.6
  src/doxygen.cpp
Labels: bug, LaTeX

#9664 HTML `<details>` tag without `<summary>` tag
  src/docnode.cpp
  src/translator.h
  src/translator_am.h
  src/translator_ar.h
  src/translator_bg.h
  src/translator_br.h
  src/translator_ca.h
  src/translator_cn.h
  src/translator_cz.h
  src/translator_de.h
  src/translator_dk.h
  src/translator_en.h
  src/translator_eo.h
  src/translator_es.h
  src/translator_fa.h
  src/translator_fi.h
  src/translator_fr.h
  src/translator_gr.h
  src/translator_hi.h
  src/translator_hr.h
  src/translator_hu.h
  src/translator_id.h
  src/translator_it.h
  src/translator_jp.h
  src/translator_kr.h
  src/translator_lt.h
  src/translator_lv.h
  src/translator_mk.h
  src/translator_nl.h
  src/translator_no.h
  src/translator_pl.h
  src/translator_pt.h
  src/translator_ro.h
  src/translator_ru.h
  src/translator_sc.h
  src/translator_si.h
  src/translator_sk.h
  src/translator_sr.h
  src/translator_sv.h
  src/translator_tr.h
  src/translator_tw.h
  src/translator_ua.h
  src/translator_vi.h
  src/translator_za.h
  testing/060/class_details_without_summary.xml
Labels: bug

#9661 Reference to non existing pages with embedded anonymous union / struct
  src/memberdef.cpp
Labels: bug

#9673 issue #9672 doxygen does not interpret Python docstrings when typed next to SLURM directives
  src/pyscanner.l
Labels: bug, Python

#9671 issue #9669 Namespaces in arguments of a method breaks cref resolving in C#
  src/scanner.l
Labels: bug, C#

#9675 Fixed missing line return
  src/doxygen.cpp
Labels: bug

#9667 Incorrect man code output in respect to backslashes
  src/mangen.cpp
Labels: bug, Man

#9677 Make path of examples independent of `..`
  examples/CMakeLists.txt
  examples/baseexample.cfg
Labels: bug, install/build

#9684 Small correction of `startGroupHeader` argument (int <-> bool)
  src/mangen.cpp
  src/rtfgen.h
Labels: bug, install/build

#9690 Incorrect place of prototype of `dateToString`
  src/context.cpp
  src/datetime.h
  src/htmlgen.cpp
  src/latexgen.cpp
  src/mangen.cpp
  src/sqlite3gen.cpp
  src/util.h
Labels: bug, install/build

#9688 Incorrect return of getUTF8CharAt giving wrong alphabetical index
  src/utf8.cpp
Labels: bug

#9676 Added latex and html folders in gitignore
  .gitignore
Labels: bug, install/build

#9695 Documentation correction in config.xml
  src/config.xml
Labels: bug

#9693 Area tag does not give `alt=""` as of dot 7.0.2
  src/dotfilepatcher.cpp
Labels: bug

#9698 issue #9697 Minor correction to documentation
  doc/commands.doc
Labels: bug, documentation

#9700 Correct place of doxygen.md
  doc_internal/Doxyfile.in
  doc_internal/doxygen.md
Labels: bug, install/build
