Repository doxygen/doxygen, pull requests merged in 2022-12, with the labels that each got.

#9712 Replace MiKTeX by tlmgr for Windows
  .github/workflows/build_cmake.yml
Labels: bug, install/build

#9709 Adding Python PEP 526 typing support
  src/pyscanner.l
Labels: enhancement, Python

#9714 Double reference to enumitem package
  templates/latex/doxygen.sty
Labels: bug, LaTeX

#9706 Adding protection protected for Python
  src/pyscanner.l
Labels: enhancement, Python

#9692 bug_466064 Formatting-options for $datetime
  src/config.xml
  src/context.cpp
  src/datetime.cpp
  src/datetime.h
  src/htmlgen.cpp
  src/latexgen.cpp
  src/mangen.cpp
  src/rtfgen.cpp
  src/sqlite3gen.cpp
  src/translator.h
  src/translator_adapter.h
  src/translator_am.h
  src/translator_bg.h
  src/translator_br.h
  src/translator_ca.h
  src/translator_cn.h
  src/translator_cz.h
  src/translator_de.h
  src/translator_dk.h
  src/translator_en.h
  src/translator_eo.h
  src/translator_es.h
  src/translator_fa.h
  src/translator_fr.h
  src/translator_gr.h
  src/translator_hi.h
  src/translator_hr.h
  src/translator_hu.h
  src/translator_id.h
  src/translator_it.h
  src/translator_jp.h
  src/translator_kr.h
  src/translator_lv.h
  src/translator_nl.h
  src/translator_pl.h
  src/translator_pt.h
  src/translator_ro.h
  src/translator_ru.h
  src/translator_sk.h
  src/translator_sv.h
  src/translator_tr.h
  src/translator_tw.h
  src/translator_ua.h
  src/util.cpp
Labels: enhancement

#9725 Warnings when generating documentation
  doc/translator.py
Labels: bug, install/build, documentation

#9727 Creation of internal documentation depends on executable
  doc_internal/CMakeLists.txt
Labels: bug, install/build

#9731 Check debug settings by means of the compiler
  src/debug.cpp
  src/debug.h
  src/doxygen.cpp
Labels: bug, install/build

#9734 issue #9733 doxygen stops parsing a file if one uses latex formulas and //!< or ///< for inline parameter documentation
  src/scanner.l
Labels: bug, C/C++

#9737 Coverity warnings
  src/portable.cpp
Labels: bug, install/build

#9735 Don't show default text in case no default value present
  addon/doxywizard/expert.cpp
Labels: bug, doxywizard

#9724 issue #9721 \code blocks have blank lines removed in LaTeX/PDF output
  src/latexgen.cpp
  templates/latex/doxygen.sty
Labels: bug, LaTeX

#9739 Coverity warnings
  src/definition.cpp
Labels: bug, install/build

#9741 Compiler warnings 64bit Windows
  src/index.cpp
Labels: bug, install/build

#9685 Show "Additional Inherited Members" for LaTeX, RTF, etc.
  src/classdef.cpp
  src/docbookgen.cpp
  src/docbookgen.h
  src/htmlgen.cpp
  src/htmlgen.h
  src/latexgen.cpp
  src/latexgen.h
  src/mangen.cpp
  src/mangen.h
  src/memberlist.cpp
  src/rtfgen.cpp
  src/rtfgen.h
Labels: bug, LaTeX, RTF, Man, DocBook

#9740 Remove redundant functions and typedef
  src/definition.cpp
  src/portable.cpp
  src/portable.h
Labels: bug, install/build

#9738 issue #9736 Doxygen will not generate class information for a C# class that contains certain string combinations
  src/scanner.l
Labels: bug, C#

#9743 bug_621171 \relates does not find class if it is in an anonymous namespace
  src/declinfo.l
Labels: bug

#9528 issue #9317 File-scoped nested namespaces in C#
  src/scanner.l
Labels: bug, C#

#9670 Add option to have warning on undocumented enumeration member
  addon/doxyapp/doxyapp.cpp
  addon/doxyparse/doxyparse.cpp
  src/config.xml
  src/memberdef.cpp
Labels: enhancement

#9730 issue #9702 How can I add custom tags that would be similar to "inline" and "static" to some functions?
  addon/doxmlparser/doxmlparser/compound.py
  doc/commands.doc
  src/commentscan.l
  src/doxygen.cpp
  src/entry.cpp
  src/entry.h
  src/markdown.cpp
  src/memberdef.cpp
  src/memberdef.h
  src/xmlgen.cpp
  templates/xml/compound.xsd
Labels: enhancement

#9744 Adding new setting to list of settings in internal documentation
  doc_internal/tags_history.md
Labels: bug, install/build

#9745 `SORT_MEMBERS_DOCS` incorrectly set as obsolete in 1.9.2
  doc_internal/tags_history.md
Labels: bug, install/build

#9746 Consistency of used setting names
  src/config.xml
Labels: bug, documentation

#9755 Revised and updated spanish translation to 1.9.6
  src/translator_es.h
Labels: bug

#9754 Correction of spelling in changelog
  doc/changelog.doc
Labels: bug, documentation

#9750 Updated swedish translation to 1.9.6
  src/translator_sv.h
Labels: bug

#9752 Incorrect representation of endverbatim command in commands history
  doc_internal/commands_history.md
Labels: bug, install/build, documentation

#9759 issue #9756 Doxygen produces invalid output for many C# interpolated strings
  src/scanner.l
Labels: bug, C#
