Repository doxygen/doxygen, pull requests merged in 2022-03, with the labels that each got.

#9176 Recognize type= as variable in Fortran
  src/fortranscanner.l
Labels: bug, Fortran

#9178 Issue #9171 XML output for dot file uses relative path in 1.9.3
  addon/doxmlparser/doxmlparser/compound.py
  templates/xml/compound.xsd
Labels: bug, XML

#9177 Determination of fixed source form.
  src/util.cpp
Labels: bug, Fortran

#9179 Replace static Config_Get... by just Config_get...
  src/clangparser.cpp
  src/classdef.cpp
  src/classlist.cpp
  src/commentcnv.l
  src/conceptdef.cpp
  src/context.cpp
  src/definition.cpp
  src/dirdef.cpp
  src/docbookvisitor.cpp
  src/docparser.cpp
  src/doctokenizer.l
  src/dotdirdeps.cpp
  src/dotnode.cpp
  src/doxygen.cpp
  src/filedef.cpp
  src/fortrancode.l
  src/ftvhelp.cpp
  src/groupdef.cpp
  src/htmldocvisitor.cpp
  src/htmlhelp.cpp
  src/image.cpp
  src/index.cpp
  src/latexdocvisitor.cpp
  src/layout.cpp
  src/memberdef.cpp
  src/memberlist.cpp
  src/namespacedef.cpp
  src/pagedef.cpp
  src/qhp.cpp
  src/rtfdocvisitor.cpp
  src/rtfgen.cpp
  src/searchindex.cpp
  src/translator_bg.h
  src/translator_br.h
  src/translator_de.h
  src/translator_en.h
  src/translator_es.h
  src/translator_fr.h
  src/translator_hi.h
  src/translator_nl.h
  src/translator_pt.h
  src/translator_sv.h
  src/util.cpp
  src/vhdlcode.l
  src/vhdljjparser.cpp
  src/xmlgen.cpp
Labels: bug, install/build

#9183 Refer to chapter Grouping with GROUP_GRAPHS
  src/config.xml
Labels: enhancement, documentation

#9189 issue #9187 doxygen -x_noenv option to not expand environment variables
  doc/arch.doc
  doc/doxygen.1
  src/config.h
  src/configimpl.l
  src/doxygen.cpp
Labels: enhancement

#9186 Detecting end of body in python
  src/pyscanner.l
Labels: bug, Python

#9184 Small correction in post processing generateDS output
  addon/doxmlparser/doxmlparser/compound.py
  addon/doxmlparser/doxmlparser/index.py
  addon/doxmlparser/generateDS_post.py
Labels: bug, doxmlparser

#9198 Extended support for language specified in markdown fenced code blocks
  doc/markdown.doc
  src/markdown.cpp
Labels: enhancement, Markdown

#9173 missing preposition
  src/config.xml
Labels: bug

#9161 Reinstate warnings about stale translations
  src/language.cpp
Labels: bug

#9067 Reference to non existing anchor with "More..."
  src/memberdef.cpp
Labels: bug

#9206 Better translation for trPackageMembers
  src/context.cpp
  src/layout.cpp
  src/translator.h
  src/translator_am.h
  src/translator_ar.h
  src/translator_bg.h
  src/translator_br.h
  src/translator_ca.h
  src/translator_cn.h
  src/translator_cz.h
  src/translator_de.h
  src/translator_dk.h
  src/translator_en.h
  src/translator_eo.h
  src/translator_es.h
  src/translator_fa.h
  src/translator_fi.h
  src/translator_fr.h
  src/translator_gr.h
  src/translator_hi.h
  src/translator_hr.h
  src/translator_hu.h
  src/translator_id.h
  src/translator_it.h
  src/translator_jp.h
  src/translator_kr.h
  src/translator_lt.h
  src/translator_lv.h
  src/translator_mk.h
  src/translator_nl.h
  src/translator_no.h
  src/translator_pl.h
  src/translator_pt.h
  src/translator_ro.h
  src/translator_ru.h
  src/translator_sc.h
  src/translator_si.h
  src/translator_sk.h
  src/translator_sr.h
  src/translator_sv.h
  src/translator_tr.h
  src/translator_tw.h
  src/translator_ua.h
  src/translator_vi.h
  src/translator_za.h
Labels: bug

#9218 issue #9217 Can't load MathJax 3 extensions
  src/htmlgen.cpp
  templates/html/htmlbase.tpl
Labels: bug, HTML
