Repository doxygen/doxygen, pull requests merged in 2022-04, with the labels that each got.

#9237 issue #9234 NUM_PROC_THREADS not being honored when processing input
  src/configimpl.l
  src/doxygen.cpp
Labels: bug

#9233 issue #9229 Crash with Segmentation fault in ClassDefImpl::mergeMembers
  src/vhdldocgen.cpp
Labels: bug, VHDL

#9244 issue #9243 GHC_NO_DIRENT_D_TYPE should be defined on Solaris
  filesystem/filesystem.hpp
Labels: bug, install/build

#9208 Remove shadowed variable warning
  src/markdown.cpp
Labels: bug, install/build

#9256 issue #9254 Missing first word of page in case of existing \page command in markdown
  src/markdown.cpp
Labels: bug, Markdown

#9263 Problem compiling under Cygwin
  CMakeLists.txt
Labels: bug, install/build

#9170 issue #9158 Python: Two classes in one file, second class documentation block copied into its class method block
  src/pyscanner.l
Labels: bug, Python

#9265 issue #9264 Markdown tables not rendered for parameters
  src/scanner.l
Labels: bug, C/C++

#9258 bug 783768 QCH files: classes & their constructors get conflicting keyword handling
  src/htmlhelp.cpp
  src/qhp.cpp
Labels: bug

#9204 issue #9200 Doxygen cannot resolve link to HTML anchor page
  src/commentscan.l
Labels: bug

#9261 issue #9257 Build Error regarding vhdlparser
  vhdlparser/CMakeLists.txt
  vhdlparser/vhdljj_adj.py
Labels: bug, install/build, VHDL

#9228 issue #9135 Qhelpgenerator debug mode
  src/doxygen.cpp
Labels: enhancement

#9149 issue #9143 warning file-line format in Possible candidates
  src/config.xml
  src/doxygen.cpp
  src/message.cpp
  src/message.h
Labels: enhancement

#9139 issue #9138 QHP index contains duplicated file entries
  src/qhp.cpp
Labels: enhancement, HTML

#9146 issue #9144 problem with matching function when using namespace
  src/doxygen.cpp
Labels: bug, C/C++

#9153 Enable the equal sign in the file mask
  src/commentscan.l
  src/doctokenizer.l
Labels: bug

#9169 Give warning in case of switch to a non supported language
  src/commentscan.l
  src/config.h
  src/configgen.py
Labels: bug

#9220 issue #9190 DOC: Mention -x switch in the "Support" page
  doc/doxygen_usage.doc
  doc/perlmod.doc
  doc/trouble.doc
  src/config.xml
Labels: enhancement, documentation

#9197 issue #9192 "Packages" has a "Packages" in the tree
  src/context.cpp
  src/layout.cpp
  src/translator.h
  src/translator_adapter.h
  src/translator_bg.h
  src/translator_br.h
  src/translator_cn.h
  src/translator_cz.h
  src/translator_en.h
  src/translator_gr.h
  src/translator_hi.h
  src/translator_nl.h
  src/translator_pt.h
  src/translator_sv.h
Labels: bug, Python

#9088 bug_644899 New diagram implementing environment
  src/commentscan.l
  testing/028/indexpage.xml
Labels: bug

#9252 issue #9251 HTML extensions stripped from DOT SVG links with tagfiles
  src/dotnode.cpp
Labels: bug

#9268 Small text correction config.xml
  src/config.xml
Labels: bug

#9270 bug_698167 HIDE_SCOPE_NAMES does not hide namespace scope for functions within it
  src/doxygen.cpp
Labels: bug, C/C++

#9273 Incorrect protection for test 28
  testing/028/indexpage.xml
Labels: install/build

#9231 bug_445536 Select folder for STRIP_FROM_PATH
  src/config.xml
Labels: enhancement, doxywizard

#9271 issue #9269 Not able to compile with MSYS2/mingw (file too big)
  CMakeLists.txt
Labels: install/build

#9278 Handling of value of visible attribute
  src/layout.cpp
Labels: bug

#9087 issue #9070 Doxygen is not showing all called functions in graph plot
  src/pre.l
  src/scanner.l
Labels: bug

#9277 issue #9276 File-Line is omitted when suggesting possible candidates depending on noMatchCount
  src/doxygen.cpp
Labels: bug

#9216 Don't create anchor for \name command
  src/context.cpp
  src/filedef.cpp
  src/memberdef.cpp
  src/memberdef.h
  src/membergroup.cpp
  src/membergroup.h
  src/memberlist.cpp
  src/namespacedef.cpp
  src/vhdldocgen.cpp
Labels: bug

#9285 issue #9284 Clicking external link within search results with EXT_LINKS_IN_WINDOW=YES opens the link in the search results box
  src/searchindex_js.cpp
  templates/html/search.js
Labels: bug, HTML

#9060 issue #9055 Objective C method / property attribute decoration confuses parsing
  src/scanner.l
Labels: bug

#9288 Concept mising in the layout description
  doc/customize.doc
Labels: bug, documentation

#9289 Remove retrieval of the process count for tests
  .github/workflows/build_cmake.yml
Labels: bug, install/build

#9281 Handling enums in settings that double as boolean
  src/config.xml
  src/configgen.py
  src/layout.cpp
Labels: bug

#9291 Error when generating documentation with formulas a second time
  src/formula.cpp
Labels: bug, HTML
