Repository doxygen/doxygen, pull requests merged in 2022-01, with the labels that each got.

#8997 issue #8355 Doxywizard 1.9.x doesn't start up properly
  addon/doxywizard/expert.cpp
Labels: bug, doxywizard

#8995 Remove obsolete reference to version.cpp
  addon/doxywizard/CMakeLists.txt
Labels: bug, doxywizard, install/build

#9008 Compilation warnings in util.cpp
  src/textstream.h
  src/util.cpp
Labels: bug

#9009 Trace statement in markdown.cpp
  src/markdown.cpp
Labels: bug, Markdown

#9015 Combine function of rtf gives wrong results.
  src/textstream.h
Labels: bug, RTF

#9014 issue #9007 Using DOT_PATH with a symlink for dot does not always work
  src/config.xml
  src/configimpl.l
  src/dotrunner.cpp
  src/plantuml.cpp
  src/vhdldocgen.cpp
Labels: bug

#9010 Incorrect macro file name in LaTeX
  src/latexgen.cpp
Labels: bug, LaTeX

#9001 Incorrect version in language documentation
  doc/CMakeLists.txt
  doc/translator.py
Labels: bug, install/build, documentation

#9004 Align latex commands
  src/latexgen.cpp
Labels: bug, LaTeX

#8999 issue #6992 Automatic Coverity run
  .github/workflows/coverity.yml
Labels: enhancement, install/build

#9013 Add for the xml output also xml to the markdown image representation.
  src/markdown.cpp
Labels: bug, XML, Markdown

#9018 issue #9007 Using DOT_PATH with a symlink for dot does not always work (plantuml)
  src/config.h
  src/configimpl.h
  src/configimpl.l
  src/plantuml.cpp
Labels: bug

#9026 bug 711041 Undocumented "enum" values in TOC of qhp files causes tag-mismatch and corrupt TOC
  src/qhp.cpp
Labels: bug

#9031 Incorrect doxygen help information
  doc/doxygen.1
  src/doxygen.cpp
Labels: bug, documentation

#9030 issue #9028 DoxyVerb environment should terminate the previous paragraph before changing paragraph formatting
  templates/latex/doxygen.sty
Labels: bug, LaTeX

#9034 Correcting spelling error
  src/context.cpp
  testing/dtd/xhtml-symbol.ent
Labels: bug

#9033 issue_9027 SEARCHDATA_FILE (searchdata.xml) keyword elements blank
  src/doxygen.cpp
Labels: bug, HTML

#9041 Close open brackets.
  templates/html/doxygen.css
Labels: bug, HTML

#9042 Correcting spelling error
  src/tagreader.cpp
Labels: bug

#9046 Spelling error in Dutch translation
  src/translator_nl.h
Labels: bug

#9032 bug_711041 Undocumented "enum" values in TOC of qhp files causes tag-mismatch and corrupt TOC.
  src/docsets.h
  src/eclipsehelp.h
  src/ftvhelp.h
  src/htmlhelp.h
  src/index.cpp
  src/index.h
  src/qhp.cpp
  src/qhp.h
  templates/general/layout_default.xml
Labels: bug

#9050 issue #9045 wrong grammar/spelling in german html Output
  src/translator_de.h
Labels: bug

#7876 issue #7873 Combining `///`-style comments with macros containing @cond/@endcond causes a preprocessor error
  src/commentcnv.l
Labels: bug, C/C++

#9062 Incorrect line number in warning message
  src/markdown.cpp
Labels: bug

#9063 Spelling correction
  src/commentcnv.l
Labels: bug

#9061 issue #9054 Feature Request: Doxywizard: Customize Doxyfile Line Endings
  addon/doxywizard/doxywizard.cpp
Labels: bug, doxywizard

#9066 Restrict usable flex version to 2.6 and higher
  CMakeLists.txt
Labels: bug, install/build

#9068 issue #9058 Strip leading spaces in QHP file
  src/debug.cpp
  src/debug.h
  src/qhpxmlwriter.cpp
Labels: bug

#9069 #issue 9058 Indentation on enum in QHP file
  src/index.cpp
Labels: bug

#9078 Fixing number of format problems reported by coverity
  src/doxygen.cpp
Labels: bug, install/build

#9076 Issue #9075 .html Extension Removed from Tag File URLs
  src/util.cpp
Labels: bug, HTML

#9071 Warnings Windows 64-bit compilation
  src/pre.l
  src/vhdljjparser.cpp
Labels: bug, install/build

#9077 issue #9074 Menubar Links not Parsed Correctly
  src/index.cpp
  templates/html/menu.js
Labels: bug, HTML

#9080 Fixing format problem reported by coverity
  src/doxygen.cpp
Labels: bug
