Repository doxygen/doxygen, pull requests merged in 2022-09, with the labels that each got.

#9555 Better VHDL translation support
  src/htmldocvisitor.cpp
  src/translator.h
  src/translator_adapter.h
  src/translator_br.h
  src/translator_cz.h
  src/translator_en.h
  src/translator_nl.h
  src/translator_pt.h
Labels: bug, VHDL

#9560 Commands documentation overview on website not shown in 3 columns
  doc/doxygen_manual.css
  doc_internal/doc_internal.css
  templates/html/doxygen.css
Labels: bug, documentation, HTML, website

#9561 Shadowed variable in fortranscanner.l
  src/fortranscanner.l
Labels: bug, Fortran

#9547 Incorrect documentation for the command `\fileinfo`
  doc/commands.doc
Labels: bug, documentation

#9573 Warning during compilation on Windows systems
  src/diagram.cpp
  src/fortranscanner.l
  src/util.cpp
  src/vhdldocgen.cpp
Labels: bug

#9570 Update commands.doc
  doc/commands.doc
Labels: bug, documentation

#9583 issue #9582 `noexcept(false)`-function is labeled as noexcept
  src/scanner.l
Labels: bug, C/C++

#9586 issue #9584 Warning "Illegal command \ifile found as part of a \c command" in \copydoc, but not original documentation
  src/docparser.cpp
Labels: bug

#9565 Warning during compilation on Windows systems
  src/code.l
  src/dotfilepatcher.cpp
  src/doxygen.cpp
  src/layout.cpp
  src/portable.cpp
  src/pre.l
  src/util.cpp
  src/xmldocvisitor.cpp
Labels: bug, install/build

#9575 Update translator_fr.h
  src/translator_fr.h
Labels: bug

#9576 Update translator_fr.h
  src/translator_fr.h
Labels: bug

#9578 Update translator_fr.h
  src/translator_fr.h
Labels: bug

#9579 Update translator_fr.h
  src/translator_fr.h
Labels: bug

#9595 [regression] Double negate
  src/portable.cpp
Labels: bug

#9594 HTML_COLORSTYLE improve documentation
  src/config.xml
Labels: bug, documentation

#9592 Warning during compilation on Windows systems
  src/doxygen.cpp
Labels: bug

#9589 Update translator_fr.h
  src/translator_fr.h
Labels: bug

#9585 [regression] PHP normal comment
  src/commentcnv.l
Labels: bug, PHP

#9574 issue #9566 Same member groups in multibyte characters are separately generated.
  src/qcstring.cpp
Labels: bug

#9572 Warning during compilation on Windows systems
  src/configimpl.l
  src/qcstring.h
  src/xmlcode.l
Labels: bug

#9606 issue #9604 PlantUML @start<engine> not recognized
  doc/commands.doc
Labels: enhancement, documentation

#9599 Usage of steady_clock
  src/debug.cpp
Labels: bug

#9607 GitHub Workflows security hardening
  .github/workflows/build_cmake.yml
Labels: install/build

#9608 Add building of the doxygen internal documentation to CMake
  .github/workflows/build_cmake.yml
  CMakeLists.txt
  doc_internal/CMakeLists.txt
  doc_internal/Doxyfile.in
Labels: enhancement, install/build

#9609 bug 736665 First % in markdown inline code segement a la %PATH% is swallowed
  src/markdown.cpp
Labels: bug, Markdown

#9605 Unknown entities in the preprocessor conditionals
  src/pre.l
Labels: bug

#9614 PR #9605 different fixes
  src/pre.l
  src/qcstring.h
Labels: bug

#9601 Spurious characters in Fortran Fixed to free format conversion
  src/fortranscanner.l
Labels: bug, Fortran

#9596 Warning during compilation on Windows systems
  src/image.cpp
  src/searchindex.cpp
Labels: bug

#9597 Warning during compilation on Windows systems
  src/code.l
  src/commentcnv.l
  src/commentscan.l
  src/configimpl.l
  src/constexp.l
  src/declinfo.l
  src/defargs.l
  src/doctokenizer.l
  src/fortrancode.l
  src/fortranscanner.l
  src/lexcode.l
  src/lexscanner.l
  src/pre.l
  src/pycode.l
  src/pyscanner.l
  src/scanner.l
  src/sqlcode.l
  src/util.cpp
  src/vhdlcode.l
  src/xmlcode.l
Labels: bug

#9598 Warning during compilation on Windows systems
  src/debug.cpp
  src/diagram.cpp
  src/dotdirdeps.cpp
  src/doxygen.cpp
  src/portable.cpp
Labels: bug
