Repository doxygen/doxygen, pull requests merged in 2022-08, with the labels that each got.

#9488 [regression] bug 786576 regression with ALIASES or image latex interpretation
  src/docparser.cpp
Labels: bug

#9495 Warning when compiling with -Wpedantic
  src/classdef.cpp
Labels: bug

#9498 Recognizing and name of implicit Fortran programs
  src/fortranscanner.l
Labels: bug, Fortran

#9494 Warning of missing parameter description
  src/definition.cpp
Labels: bug

#9501 Dtd settings for HTML_DARKMODE
  testing/dtd/xhtml1-transitional.dtd
Labels: bug, HTML

#9505 Setting HTML_COLORSTYLE for examples
  examples/afterdoc.cfg
  examples/author.cfg
  examples/autolink.cfg
  examples/class.cfg
  examples/define.cfg
  examples/diagrams.cfg
  examples/docstring.cfg
  examples/enum.cfg
  examples/example.cfg
  examples/file.cfg
  examples/func.cfg
  examples/group.cfg
  examples/include.cfg
  examples/javadoc-banner.cfg
  examples/jdstyle.cfg
  examples/manual.cfg
  examples/memgrp.cfg
  examples/mux.cfg
  examples/overload.cfg
  examples/page.cfg
  examples/par.cfg
  examples/pyexample.cfg
  examples/qtstyle.cfg
  examples/relates.cfg
  examples/restypedef.cfg
  examples/structcmd.cfg
  examples/tag.cfg
  examples/templ.cfg
Labels: bug, documentation

#9506 Setting proper HTML_COLORSTYLE in case of GENERATE_HTMLHELP
  src/configimpl.l
Labels: bug, HTML

#9507 Making example configurations consistent
  examples/CMakeLists.txt
  examples/afterdoc.cfg
  examples/author.cfg
  examples/autolink.cfg
  examples/baseexample.cfg
  examples/class.cfg
  examples/define.cfg
  examples/diagrams.cfg
  examples/docstring.cfg
  examples/enum.cfg
  examples/example.cfg
  examples/file.cfg
  examples/func.cfg
  examples/group.cfg
  examples/include.cfg
  examples/javadoc-banner.cfg
  examples/jdstyle.cfg
  examples/manual.cfg
  examples/memgrp.cfg
  examples/mux.cfg
  examples/overload.cfg
  examples/page.cfg
  examples/par.cfg
  examples/pyexample.cfg
  examples/qtstyle.cfg
  examples/relates.cfg
  examples/restypedef.cfg
  examples/structcmd.cfg
  examples/tag.cfg
  examples/templ.cfg
Labels: bug, enhancement, documentation

#9508 Regression in respect to nbsp handling in documentation
  doc/changelog.doc
  doc/htmlcmds.doc
  doc/output.doc
  doc/translator.py
  src/htmlgen.cpp
Labels: bug, documentation

#9513 Some minor documentation improvements
  doc/emojisup.doc
  doc/language.tpl
  doc/tables.doc
  doc/xmlcmds.doc
Labels: bug, documentation

#9517 Replacing the list of HTML / XML commands by tables
  doc/htmlcmds.doc
  doc/xmlcmds.doc
Labels: enhancement, documentation

#9516 issue #9515 Function return value problem
  src/doxygen.cpp
Labels: bug, RTF

#9112 Show date in a customized form
  doc/commands.doc
  doc/index.doc
  src/cmdmapper.cpp
  src/cmdmapper.h
  src/commentscan.l
  src/docnode.cpp
  src/docnode.h
  src/docparser.h
  src/doctokenizer.h
  src/doctokenizer.l
  src/translator.h
  src/translator_am.h
  src/translator_ar.h
  src/translator_bg.h
  src/translator_br.h
  src/translator_ca.h
  src/translator_cn.h
  src/translator_cz.h
  src/translator_de.h
  src/translator_dk.h
  src/translator_en.h
  src/translator_eo.h
  src/translator_es.h
  src/translator_fa.h
  src/translator_fi.h
  src/translator_fr.h
  src/translator_gr.h
  src/translator_hi.h
  src/translator_hr.h
  src/translator_hu.h
  src/translator_id.h
  src/translator_it.h
  src/translator_jp.h
  src/translator_kr.h
  src/translator_lt.h
  src/translator_lv.h
  src/translator_mk.h
  src/translator_nl.h
  src/translator_no.h
  src/translator_pl.h
  src/translator_pt.h
  src/translator_ro.h
  src/translator_ru.h
  src/translator_sc.h
  src/translator_si.h
  src/translator_sk.h
  src/translator_sr.h
  src/translator_sv.h
  src/translator_tr.h
  src/translator_tw.h
  src/translator_ua.h
  src/translator_vi.h
  src/translator_za.h
  src/util.cpp
  src/util.h
Labels: enhancement

#9521 issue #9520 Rest of file silently ignored after a certain string literal [PHP]
  src/scanner.l
Labels: bug, PHP

#9510 Fortran private/public statements
  src/fortranscanner.l
  testing/087/structmymodule_1_1t1.xml
  testing/087/structmymodule_1_1t2.xml
  testing/087/structmymodule_1_1t3.xml
  testing/087/structmymodule_1_1t4.xml
  testing/087_public_type.F90
  testing/088/namespacem1.xml
  testing/088/namespacem2.xml
  testing/088_module_var.f90
  testing/089/namespacem1.xml
  testing/089/namespacem2.xml
  testing/089_module_proc.f90
Labels: Fortran

#9511 Test Fortran inheritance over modules
  testing/095/namespacem1.xml
  testing/095/namespacem2.xml
  testing/095/namespacem3.xml
  testing/095/structm1_1_1t1.xml
  testing/095/structm1_1_1t2.xml
  testing/095/structm1_1_1t3.xml
  testing/095/structm2_1_1t3.xml
  testing/095/structm3_1_1t4.xml
  testing/095_inheritance.f03
  testing/096/namespacem1.xml
  testing/096/namespacem2.xml
  testing/096/namespacem3.xml
  testing/096/structm1_1_1t1.xml
  testing/096/structm1_1_1t2.xml
  testing/096/structm1_1_1t3.xml
  testing/096/structm2_1_1t3.xml
  testing/096/structm3_1_1t4.xml
  testing/096_namespace_inheritance.cpp
Labels: enhancement, C/C++, Fortran

#9509 Handling of `@...@` setting with `doxygen -x_noenv`
  doc/arch.doc
  doc/doxygen.1
  src/config.h
  src/config.xml
  src/configimpl.l
  src/doxygen.cpp
Labels: enhancement

#9340 Strange internal documentation in docnode.h
  src/docnode.h
Labels: bug

#9524 Better readability of the format of the `\showdate` command
  doc/commands.doc
Labels: bug, documentation

#9530 Unused variable in Japanese translation
  src/translator_jp.h
Labels: bug

#9529 Correcting warning in `translator_report.txt`
  src/translator_es.h
  src/translator_fr.h
Labels: bug, documentation

#9526 issue #9236 doxygen x_noenv should always diff system-dependent settings
  src/config.xml
  src/filename.h
  src/util.cpp
  src/util.h
Labels: enhancement

#9533 issue #9527 Enhance documentation for filter commands
  doc/preprocessing.doc
  src/config.xml
Labels: enhancement, documentation

#9361 Specify input encoding based on a file pattern
  src/config.xml
  src/configimpl.l
  src/definition.cpp
  src/doxygen.cpp
  src/doxygen.h
  src/util.cpp
  src/util.h
Labels: enhancement

#9532 Extend `\showdate` with time possibilities
  doc/commands.doc
  src/docnode.cpp
  src/doctokenizer.l
Labels: enhancement

#9536 Remove unused Validate debug option
  src/debug.cpp
  src/debug.h
Labels: bug

#8912 Give markdown verbatim and fenced code blocks their own command.
  src/cmdmapper.cpp
  src/cmdmapper.h
  src/commentscan.l
  src/docnode.cpp
  src/docparser.cpp
  src/doctokenizer.h
  src/doctokenizer.l
  src/markdown.cpp
  src/pyscanner.l
Labels: bug, Python, Markdown

#9496 Documenting parameter of function without parameters
  src/docparser.cpp
Labels: bug

#9525 Full line environment replacement for configuration setting
  src/config.h
  src/configimpl.h
  src/configimpl.l
  src/doxygen.cpp
Labels: enhancement

#9461 issue #7946 Add filename and line number support to tags, ala __FILE__ and __LINE__ macros
  doc/commands.doc
  src/commentscan.l
Labels: enhancement

#9543 Incorrect version number in $(VERSION) and thus documentation
  cmake/version.cmake
Labels: bug, install/build

#9545 Update index.doc
  doc/index.doc
Labels: bug

#9556 Extending internal documentation with some version information
  Doxyfile
  doc_internal/commands_history.md
  doc_internal/commands_internal.md
  doc_internal/doc_internal.css
  doc_internal/releases.md
  doc_internal/tags_history.md
Labels: enhancement

#9548 Correcting default HTML stylesheets for color style LIGHT and DARK
  src/htmlgen.cpp
Labels: bug, HTML

#9551 Dot uml class diagram fix
  src/dotnode.cpp
Labels: bug

#9553 Vhdl process flowchart bugfix
  src/vhdldocgen.cpp
Labels: bug, VHDL

#9541 Fortran vhdl menu item normalization
  src/layout.cpp
Labels: bug, Fortran, VHDL

#9518 Fortran interfaces improvements
  src/fortranscanner.l
  testing/090/interfacemymodule_1_1abstractproc.xml
  testing/090/interfacemymodule_1_1externalproc.xml
  testing/090/interfacemymodule_1_1genericproc.xml
  testing/090/interfacemymodule_1_1operator_07_2_2_08.xml
  testing/090/interfacemymodule_1_1operator_07_8cross_8_08.xml
  testing/090/namespacemymodule.xml
  testing/090_interfaces.f90
  testing/091/namespacemymodule.xml
  testing/091_module_with_procs.f90
  testing/092/interfacestrings_1_1append.xml
  testing/092/interfacestrings_1_1operator_07_0a_0a_08.xml
  testing/092/namespacestrings.xml
  testing/092_more_interfaces.f90
  testing/093/093__interface__inside__routine_8f90.xml
  testing/093_interface_inside_routine.f90
  testing/094/094__old__style__fortran__routines_8f90.xml
  testing/094_old_style_fortran_routines.f90
Labels: Fortran

#9558 Hash comment in php
  src/commentcnv.l
Labels: bug, PHP

#9559 Remove non existing Qt compatibility commands from the documentation
  doc/commands.doc
Labels: bug, documentation
