Repository doxygen/doxygen, pull requests merged in 2022-02, with the labels that each got.

#9089 Incorrect check on a list item.
  src/docparser.cpp
Labels: bug

#9086 Spurious colon in the output
  src/commentscan.l
Labels: bug

#9090 Remove debug statement for Bulgarian Language
  src/language.cpp
Labels: bug

#9091 Correcting spelling
  src/configimpl.h
  src/variant.h
Labels: bug

#9093 Update Bulgarian translation
  src/translator_bg.h
Labels: bug

#9097 HTMLHELP warning on using svg as image format for graphs
  src/dotcallgraph.cpp
  src/dotgroupcollaboration.cpp
  src/htmlgen.cpp
  src/htmlhelp.cpp
  src/htmlhelp.h
Labels: bug, HTML

#9085 Adding Qt6 support, dropping Qt4 support
  BUILD.txt
  CMakeLists.txt
  addon/doxywizard/CMakeLists.txt
  addon/doxywizard/config.h
  addon/doxywizard/config_doxyw.l
  addon/doxywizard/doxywizard.cpp
  addon/doxywizard/expert.cpp
  addon/doxywizard/expert.h
  addon/doxywizard/helplabel.h
  addon/doxywizard/input.h
  addon/doxywizard/inputbool.cpp
  addon/doxywizard/inputbool.h
  addon/doxywizard/inputint.cpp
  addon/doxywizard/inputint.h
  addon/doxywizard/inputobsolete.h
  addon/doxywizard/inputstring.cpp
  addon/doxywizard/inputstring.h
  addon/doxywizard/inputstrlist.cpp
  addon/doxywizard/inputstrlist.h
  addon/doxywizard/wizard.cpp
  doc/install.doc
Labels: bug, enhancement, doxywizard

#9098 Automatically show correct year in about box
  addon/doxywizard/doxywizard.cpp
Labels: bug, doxywizard

#9104 Adjust tested Visual Studio version
  doc/install.doc
Labels: bug, documentation

#9082 Making tag information better available
  src/debug.cpp
  src/debug.h
  src/tagreader.cpp
Labels: bug, enhancement

#9099 Automatically set copyright year in doxygen man page
  doc/CMakeLists.txt
  doc/doxygen.1
Labels: bug, install/build, documentation

#9100 Correcting default settings when running HTMLHELP
  src/configimpl.l
Labels: bug, HTML

#9095 Maintenance on translator functions
  src/htmldocvisitor.cpp
  src/index.cpp
  src/latexdocvisitor.cpp
  src/latexgen.cpp
  src/layout.cpp
  src/mandocvisitor.cpp
  src/rtfdocvisitor.cpp
  src/rtfgen.cpp
  src/translator.h
  src/translator_am.h
  src/translator_ar.h
  src/translator_bg.h
  src/translator_br.h
  src/translator_ca.h
  src/translator_cn.h
  src/translator_cz.h
  src/translator_de.h
  src/translator_dk.h
  src/translator_en.h
  src/translator_eo.h
  src/translator_es.h
  src/translator_fa.h
  src/translator_fi.h
  src/translator_fr.h
  src/translator_gr.h
  src/translator_hr.h
  src/translator_hu.h
  src/translator_id.h
  src/translator_it.h
  src/translator_jp.h
  src/translator_kr.h
  src/translator_lt.h
  src/translator_lv.h
  src/translator_mk.h
  src/translator_nl.h
  src/translator_no.h
  src/translator_pl.h
  src/translator_pt.h
  src/translator_ro.h
  src/translator_ru.h
  src/translator_sc.h
  src/translator_si.h
  src/translator_sk.h
  src/translator_sr.h
  src/translator_sv.h
  src/translator_tr.h
  src/translator_tw.h
  src/translator_ua.h
  src/translator_vi.h
  src/translator_za.h
  templates/latex/doxygen.sty
Labels: bug

#9117 Small corrections for Bulgarian language
  src/htmlhelp.cpp
  src/translator_bg.h
Labels: bug, HTML, LaTeX, RTF

#9111 Small spelling correction
  CMakeLists.txt
Labels: bug

#9109 Fix build with MinGW and Ninja
  CMakeLists.txt
Labels: bug, install/build

#9113 Missing part of output due to wrong emoji command
  src/docparser.cpp
  src/doctokenizer.l
Labels: bug

#9126 Line numbers not shown in gray in source code
  src/clangparser.cpp
Labels: bug

#9125 issue #9124 Latex: Does not properly compile when PROJECT_BRIEF contains commas
  templates/latex/header.tex
Labels: bug, LaTeX

#9119 Uniform retrieval of language code by means of translator unit
  src/context.cpp
  src/htmlhelp.cpp
  src/htmlhelp.h
  src/translator.h
  src/translator_am.h
  src/translator_ar.h
  src/translator_bg.h
  src/translator_br.h
  src/translator_ca.h
  src/translator_cn.h
  src/translator_cz.h
  src/translator_de.h
  src/translator_dk.h
  src/translator_en.h
  src/translator_eo.h
  src/translator_es.h
  src/translator_fa.h
  src/translator_fi.h
  src/translator_fr.h
  src/translator_gr.h
  src/translator_hr.h
  src/translator_hu.h
  src/translator_id.h
  src/translator_it.h
  src/translator_je.h
  src/translator_jp.h
  src/translator_ke.h
  src/translator_kr.h
  src/translator_lt.h
  src/translator_lv.h
  src/translator_mk.h
  src/translator_nl.h
  src/translator_no.h
  src/translator_pl.h
  src/translator_pt.h
  src/translator_ro.h
  src/translator_ru.h
  src/translator_sc.h
  src/translator_si.h
  src/translator_sk.h
  src/translator_sr.h
  src/translator_sv.h
  src/translator_tr.h
  src/translator_tw.h
  src/translator_ua.h
  src/translator_vi.h
  src/translator_za.h
Labels: bug, enhancement, install/build

#9137 Incorrect representation of some items in HTMLHELP
  src/index.cpp
Labels: bug, HTML

#9140 Add test possibility to check the structure of the index.qhp file
  .github/workflows/build_cmake.yml
  testing/runtests.py
Labels: enhancement, install/build

#9134 Hindi translation
  doc/maintainers.txt
  src/config.xml
  src/language.cpp
  src/translator.h
  src/translator_hi.h
Labels: enhancement

#9152 Uniform retrieval file definition
  src/doxygen.cpp
  src/htmlhelp.cpp
  src/htmlhelp.h
  src/qhp.cpp
  src/qhp.h
Labels: bug, HTML

#9160 INCLUDE_PATH is not recursive
  src/config.xml
  src/doxygen.cpp
Labels: bug, documentation

#9162 Modernize LANGUAGE.HOWTO
  LANGUAGE.HOWTO
Labels: bug, documentation

#9166 Moving punctuation dependency to translator
  doc/translator.py
  src/definition.cpp
  src/translator.h
  src/translator_cn.h
  src/translator_jp.h
  src/translator_kr.h
Labels: bug

#9167 Enable always all languages
  BUILD.txt
  CMakeLists.txt
  LANGUAGE.HOWTO
  cmake/lang_cfg.cmake
  doc/Doxyfile
  doc/Doxyfile_chm
  doc/language.tpl
  doc/translator.py
  src/CMakeLists.txt
  src/configimpl.l
  src/language.cpp
  src/languages.py
Labels: bug, enhancement
