Repository doxygen/doxygen, pull requests merged in 2022-07, with the labels that each got.

#9356 Support HTML stylesheets on the Internet
  src/doxygen.cpp
  src/htmlgen.cpp
Labels: enhancement

#9392 Enabling dependencies for include files in lex files
  addon/doxywizard/CMakeLists.txt
  src/CMakeLists.txt
  src/pre_lex.py
Labels: bug

#9435 bug 539818 C Preprocessor enum printing trick not handled properly by Doxygen
  src/util.cpp
Labels: bug, C/C++

#9395 Dependency between examples.
  examples/CMakeLists.txt
Labels: bug, install/build

#9433 bug 531817 Python: Backslash prevent showing the proper preview
  src/pyscanner.l
Labels: bug, Python

#9448 Commented function list marcro gives warning
  src/pre.l
Labels: bug, C/C++

#9446 bug 642168 C# "here-docs" not correctly parsed
  src/scanner.l
Labels: bug, C#

#9442 Workaround for DEPFILE
  CMakeLists.txt
  addon/doxywizard/CMakeLists.txt
  src/CMakeLists.txt
Labels: bug, install/build

#9457 issue #8214 missing lang attribute and meta description for SEO
  src/util.cpp
  templates/html/header.html
Labels: enhancement, HTML

#9453 fix typo in DotLegendGraph
  src/dotlegendgraph.cpp
Labels: bug

#9451 issue #9047 Support @param-taint in PHP (permit dashes in command aliases)?
  doc/commands.doc
  src/commentcnv.l
  src/configimpl.l
  src/util.cpp
Labels: enhancement

#9462 [regression] Non resolved ALIASES with minus sign
  src/util.cpp
Labels: bug

#9474 Spelling correction
  src/regex.h
Labels: bug

#9469 [Regression] $lang and $languagesupport replacement problem
  src/config.xml
  src/util.cpp
  templates/html/header.html
Labels: bug, LaTeX

#9481 Spelling correction
  testing/obsolete
Labels: bug

#9465 Correction of line counting
  src/commentscan.l
Labels: bug

#9478 issue #9476 fatal: Cannot open 'doxygen/graph_legend.dox': No such file or directory
  src/filedef.cpp
Labels: bug

#9475 Fix typo in generated Makefile for LaTex
  src/latexgen.cpp
Labels: bug, LaTeX

#9477 bug 786576 regression with ALIASES or image latex interpretation
  src/docparser.cpp
  src/doctokenizer.h
  src/doctokenizer.l
Labels: bug
