Repository doxygen/doxygen, pull requests merged in 2022-06, with the labels that each got.

#9369 issue #9367 Current git master does not honor PROJECT_NUMBER in LaTeX
  src/latexgen.cpp
  templates/latex/header.tex
Labels: bug, LaTeX

#9366 issue #9362 Doxyfile environment/quote mishandling in list values
  src/configimpl.h
  src/configimpl.l
Labels: bug

#9374 Spelling correction
  src/scan_states.py
Labels: bug

#9357 bug_572042 ingroup does not allow multiple groupnames
  doc/commands.doc
Labels: enhancement, documentation

#9382 Improvement of HTML documentation section
  doc/htmlcmds.doc
Labels: bug, enhancement, documentation

#9381 issue #9378 Dollar Sign Escape Sequence Ignored in Markdown Backtick Syntax (Inline Code)
  src/markdown.cpp
Labels: bug, Markdown

#9375 Enabling include files for lex files
  addon/doxywizard/CMakeLists.txt
  src/CMakeLists.txt
  src/post_lex.py
  src/pre_lex.py
Labels: enhancement, install/build

#9384 Corrections for lexer pre- and post-processor
  src/post_lex.py
  src/pre_lex.py
Labels: bug

#9358 Small spelling correction in doxygen usage
  doc/doxygen_usage.doc
Labels: bug, documentation

#9398 End of "here document" can be indented
  src/scanner.l
Labels: bug, PHP

#9389 No click possible on chapters in doxygen's CHM documentation
  src/htmlhelp.cpp
Labels: bug, documentation, HTML

#9388 Incorrect determination of sub-sections for index.
  src/definition.cpp
Labels: bug, HTML

#9396 issue #9096 Call Graph corrupt and/or incomplete (2)
  src/code.l
Labels: bug, C/C++

#9380 Allow empty HTML <div/> and <span/> tags
  src/docnode.cpp
Labels: bug

#9400 issue #9399 XML / perlmod fortran output, the type of a parameter of function is set to the name of the parameter
  src/perlmodgen.cpp
  src/xmlgen.cpp
Labels: bug, Fortran, XML

#9421 chore: Included githubactions in the dependabot config
  .github/dependabot.yml
Labels: enhancement, install/build

#9423 Prohibit in-place doxygen builds
  CMakeLists.txt
  src/CMakeLists.txt
Labels: bug, install/build

#9431 issue #9417 Java: Issue with static initializer if no space after static
  src/scanner.l
Labels: bug, Java
