Repository doxygen/doxygen, pull requests merged in 2022-05, with the labels that each got.

#9308 Making Windows executable large address aware
  CMakeLists.txt
Labels: bug, install/build

#9245 issue #9241 Undocumented external namespaces from .tags files are shown in output Namespace index
  src/index.cpp
Labels: bug, C/C++

#9311 issue #9309 Colon on a line by itself
  src/commentscan.l
Labels: bug

#9316 Compilation warnings
  addon/doxywizard/config_doxyw.l
  libmscgen/mscgen_lexer.l
Labels: bug, install/build

#9322 Spelling error
  src/formula.cpp
Labels: bug

#9320 issue #9319 Doc build fails with cairo 1.17.6
  src/dotrunner.cpp
Labels: bug

#9338 Missing possibility for Element 'compounddef', attribute 'language'
  addon/doxmlparser/doxmlparser/compound.py
  templates/xml/compound.xsd
Labels: bug, XML

#9337 Correction to internal documentation
  src/doxygen.md
Labels: bug

#9333 issue #9317 File-scoped Namespaces in C#
  src/code.l
  src/scanner.l
Labels: bug, enhancement, C#

#9331 issue #9016 Support collapsible sections in markdown
  addon/doxmlparser/doxmlparser/compound.py
  src/docbookvisitor.cpp
  src/docbookvisitor.h
  src/docnode.cpp
  src/docnode.h
  src/docparser.cpp
  src/docparser_p.h
  src/doctokenizer.h
  src/htmldocvisitor.cpp
  src/htmldocvisitor.h
  src/latexdocvisitor.cpp
  src/latexdocvisitor.h
  src/mandocvisitor.cpp
  src/mandocvisitor.h
  src/mangen.cpp
  src/perlmodgen.cpp
  src/printdocvisitor.h
  src/rtfdocvisitor.cpp
  src/rtfdocvisitor.h
  src/textdocvisitor.h
  src/xmldocvisitor.cpp
  src/xmldocvisitor.h
  templates/xml/compound.xsd
Labels: bug

#9335 Correcting some small incorrect in documentation of doxygen's own internal documentation
  addon/doxysearch/doxyindexer.cpp
  src/plantuml.h
Labels: bug

#9326 Implementation of lineBreak and nonBreakingSpace in docbook
  src/docbookgen.cpp
  src/docbookvisitor.cpp
Labels: bug, DocBook

#9325 Warning about non closed (nested) comment
  src/commentcnv.l
Labels: bug, C/C++

#9324 Friendly message on incorrect input
  src/fortrancode.l
  src/fortranscanner.l
  src/pycode.l
Labels: bug, Fortran, Python

#9348 Spelling corrections
  src/context.cpp
  src/qhp.h
Labels: bug

#9345 issue #9344 Long bibliography entry looks bad
  templates/html/bib2xhtml.pl
Labels: bug

#9342 bug_751023 Predefined macros are handled incorrectly in source browser
  src/code.l
Labels: bug, C/C++

#9355 issue #9352 Qt Q_GADGET macro is not supported
  src/scanner.l
Labels: bug, enhancement

#9354 Portuguese translators updated to 1.9.4.
  src/translator_br.h
  src/translator_pt.h
Labels: bug
