Repository doxygen/doxygen, pull requests merged in 2023-09, with the labels that each got.

#10275 Spelling correction
  src/util.cpp
Labels: bug

#10271 Remove obsolete parts from cmake configuration files
  doc/CMakeLists.txt
  doc_internal/CMakeLists.txt
  src/CMakeLists.txt
  testing/CMakeLists.txt
Labels: install/build

#10279 Removing shadowed variables
  src/util.cpp
Labels: bug, install/build

#10270 bug_746577 Problem locating unresolvable @ref in case of a MSC image
  src/docparser.cpp
  src/docparser.h
  src/msc.cpp
Labels: bug

#10288 Update of testing README.txt
  testing/README.txt
  testing/runtests.py
Labels: bug, documentation

#10284 Fix linking doxyapp and doxyparse to spdlog
  addon/doxyapp/CMakeLists.txt
  addon/doxyparse/CMakeLists.txt
Labels: bug, install/build

#10294 Adjusting the term "module" to "topic" in documentation
  doc/customize.doc
  doc/faq.doc
  doc/features.doc
  src/layout.cpp
Labels: bug, documentation

#10298 Handling of incorrect HTML end comment
  doc/htmlcmds.doc
  src/commentscan.l
  src/markdown.cpp
Labels: bug

#10290 Warning about internal doxygen inconsistency for python packages
  src/util.cpp
Labels: bug, Python

#10303 More flexible inline sources regarding show / hide
  doc/commands.doc
  src/commentscan.l
  src/definition.cpp
  src/doxygen.cpp
  src/entry.cpp
  src/entry.h
  src/memberdef.cpp
  src/memberdef.h
Labels: enhancement

#10309 Correcting count for volatile when checking redundant white space
  src/util.cpp
Labels: bug

#10308 issue #10304 Cannot copydoc operator*
  src/util.cpp
Labels: bug, C/C++, Python

#10302 Correcting incorrect comment
  src/classdef.cpp
Labels: bug

#10301 Improvement of the description of INLINE_SOURCES setting
  src/config.xml
Labels: bug, documentation

#10312 Warning about internal doxygen inconsistency for python packages (2)
  src/util.cpp
Labels: bug, Python

#10317 Add missing C++20 module file extension
  doc/starting.doc
  src/config.xml
  src/util.cpp
Labels: bug, C/C++

#10297 Incorrect showing of hidden call graph
  src/doxygen.cpp
  src/memberdef.cpp
  src/memberdef.h
Labels: bug

#10332 Remove obsolete vhdl functions
  src/vhdldocgen.cpp
  src/vhdldocgen.h
Labels: VHDL

#10331 Add debug listing for sections
  src/debug.cpp
  src/debug.h
  src/doxygen.cpp
Labels: enhancement

#10328 Publish doxmlparser on PyPI
  .github/workflows/doxmlparser-publish.yml
  addon/doxmlparser/setup.py
Labels: enhancement, install/build

#10333 Remove obsolete vhdl functions (2)
  src/vhdldocgen.cpp
Labels: VHDL
