Repository doxygen/doxygen, pull requests merged in 2023-03, with the labels that each got.

#9887 Fix a pedantic warning
  src/translator_br.h
Labels: bug, install/build

#9888 issue 9855 Markdown: Heading auto id starting with digit of minus sign
  src/anchor.cpp
  src/markdown.cpp
Labels: bug, Markdown

#9890 Text on start line of fenced code block should not be ignored.
  src/markdown.cpp
Labels: bug, Markdown

#9884 Issue #9883 Performance issues when HAVE_DOT is YES to make \dot work, and CLASS_GRAPH=GRAPH is also used
  src/classdef.cpp
  src/config.xml
  src/context.cpp
Labels: enhancement

#9699 bug 327697 Ignores single-line /*! ... */ comment contents sometimes
  doc/commands.doc
Labels: bug, documentation

#9290 Support visible attribute for all elements in the layout file
  doc/customize.doc
  src/doxygen.cpp
  src/layout.cpp
  src/layout.h
Labels: enhancement

#9905 Don't show `__pad*__` for unnamed bitfields
  src/memberdef.cpp
Labels: bug, C/C++

#9900 issue #9899 Error on commenting function parameters
  src/memberdef.cpp
Labels: bug, C/C++

#9913 doxygen should use grep -E instead obsolescent egrep.
  src/latexgen.cpp
  templates/latex/latexmakefile.tpl
Labels: bug, LaTeX

#9920 Hyperlinks in help information of doxywizard
  addon/doxywizard/expert.cpp
Labels: bug, doxywizard

#9924 issue #9921 HIDE_SCOPE_NAMES does not hide names in treeview
  src/ftvhelp.cpp
Labels: bug

#9919 Limit index fields in hhk file of chm file.
  src/htmlhelp.cpp
  src/util.cpp
  src/util.h
Labels: bug, HTML

#9927 Small clarification on path mentioned in BUILD.txt
  BUILD.txt
Labels: bug, install/build

#9917 Make reading configuration utf-8 compatible
  src/configgen.py
Labels: bug

#9930 Incorrect handling of `ianchor` in markdown files
  src/markdown.cpp
Labels: bug, Markdown

#9939 issue #9935 Doxygen WARN_LOGFILE needs to create folder
  src/message.cpp
Labels: enhancement

#9941 issue #9932 Incomplete Style.css
  src/doxygen.cpp
  src/message.cpp
Labels: bug

#9943 issue #9942 warning: Member try (variable) of namespace lib_validation is not documented.
  src/pyscanner.l
Labels: bug, Python

#9949 Spelling correction
  src/pyscanner.l
Labels: bug

#9945 Latex incorrect handling of backticks in code fragments
  src/latexgen.cpp
Labels: bug, LaTeX

#9951 issue #9950 PlantUML is not fully supported in markdown fenced code blocks
  src/plantuml.cpp
Labels: bug

#9948 Ignore c11 static assert
  src/code.l
  src/scanner.l
  testing/101/101__static__assert_8c.xml
  testing/101_static_assert.c
Labels: bug, C/C++

#9928 issue #9911 Support ##< for documenting members and variables
  doc/docblocks.doc
  src/pyscanner.l
Labels: enhancement, Python

#9933 bug 628022 single `-` in `<pre>` busts nesting levels
  src/doctokenizer.l
Labels: bug

#7215 Add '<thead>', '<tbody>' and '<tfoot>' HTML tags as dummies
  doc/htmlcmds.doc
  src/cmdmapper.cpp
  src/cmdmapper.h
  src/docnode.cpp
Labels: enhancement

#9909 The CDATA sections in xml code representation should not be interpreted
  addon/doxmlparser/doxmlparser/compound.py
  src/xmlcode.l
  templates/html/darkmode_settings.css
  templates/html/doxygen.css
  templates/html/lightmode_settings.css
  templates/latex/doxygen.sty
  templates/xml/compound.xsd
Labels: bug

#8779 Making settings from settings file available.
  doc/commands.doc
  src/cmdmapper.cpp
  src/cmdmapper.h
  src/docnode.cpp
  src/docnode.h
  src/doctokenizer.h
  src/doctokenizer.l
Labels: enhancement

#9938 bug 615500 Program Icon under Windows
  addon/doxyapp/CMakeLists.txt
  addon/doxyparse/CMakeLists.txt
  addon/doxysearch/CMakeLists.txt
  src/CMakeLists.txt
  templates/icon/doxygen.ico
  templates/icon/doxygen.rc
Labels: enhancement

#9955 Updated spanish translation to 1.9.7
  src/translator_es.h
Labels: bug, documentation

#9954 Update translator_gr.h
  src/translator_gr.h
Labels: bug, documentation

#9931 Incorrect link in ref list of internal documentation
  doc_internal/commands_internal.md
Labels: bug, documentation

#9922 Consistency / links in LaTeX output of the doxygen documentation
  doc/commands.doc
  doc/index.doc
Labels: bug, documentation

#9960 Remove obsolete parts from translator.py
  doc/translator.py
Labels: bug, install/build, documentation

#9958 Incorrect translator adapter version
  src/translator_gr.h
Labels: bug

#9962 Spell fix
  doc/commands.doc
Labels: bug, documentation

#9961 Make the translator report available in the internal documentation
  doc/CMakeLists.txt
  doc/translator.py
  doc_internal/CMakeLists.txt
  doc_internal/Doxyfile.in
Labels: enhancement, install/build, documentation

#9912 Make configuration default texts configurable
  src/config.xml
  src/configgen.py
Labels: bug
