Repository doxygen/doxygen, pull requests merged in 2023-07, with the labels that each got.

#10158 issue #10145 latex duplicate equations
  src/formula.cpp
Labels: bug

#10161 Fix c++20 error
  src/template.cpp
Labels: install/build

#10156 issue #8393 @Endcond not behaving as expected (missing warnings, missing output)
  src/pre.l
Labels: bug

#10166 issue #10123 Argument for parameter does not exist and is missing at the same time
  src/scanner.l
Labels: bug

#10171 Sync etoc_doxygen with upstream 1.2b release of 2023/07/01
  templates/latex/etoc_doxygen.sty
Labels: bug, LaTeX

#10182 Fix for tests failing XHTML validation
  testing/013/class_t1.xml
  testing/013/class_t2.xml
  testing/013/class_t3.xml
  testing/013/class_t4.xml
  testing/013_class.h
  testing/044/struct_s.xml
  testing/044_section.h
  testing/082/namespace_n.xml
  testing/082_decl_def.cpp
  testing/dtd/xhtml1-transitional.dtd
Labels: bug, install/build, HTML

#10183 Non readable error message in tests
  testing/runtests.py
Labels: bug, install/build

#10188 Spelling correction
  doc/arch.doc
Labels: bug, documentation

#10187 issue #10186 C++: constexpr and / or static trailing return type syntax + void
  src/memberdef.cpp
Labels: bug, C/C++

#10185 Fix latex quotes in <pre>
  src/latexgen.cpp
Labels: bug, LaTeX

#10189 Problems copy `FORMULA_MACROFILE`
  src/formula.cpp
Labels: bug

#10192 issue #10191 Python docstring parsed incorrect
  src/pyscanner.l
Labels: bug, Python

#10179 Adding a separator to ALIASES
  doc/custcmd.doc
  src/CMakeLists.txt
  src/aliases.cpp
  src/aliases.h
  src/commentcnv.l
  src/configimpl.l
  src/containers.h
  src/doxygen.cpp
  src/doxygen.h
  src/util.cpp
  src/util.h
Labels: enhancement

#10197 Spelling correction
  src/definition.cpp
Labels: bug

#10198 issue #10190 References to enumerations within a class named Bool are not properly handled
  src/filedef.cpp
  src/memberdef.cpp
  src/memberdef.h
  src/memberlist.cpp
  src/memberlist.h
Labels: bug, C/C++

#10168 Show outline on focused elements with tab press
  templates/html/doxygen.css
Labels: HTML

#10200 Testing with ` CLANG_ASSISTED_PARSING=YES`
  testing/015_cond.c
  testing/026_exception.cpp
  testing/041/class_test.xml
  testing/041_overload.cpp
  testing/072/072__using_8cpp.xml
  testing/072_using.cpp
  testing/075/struct_foo.xml
  testing/075_argmatch.cpp
  testing/085/085__tooltip_8cpp.xml
  testing/085_tooltip.cpp
  testing/099_a.c
  testing/100_a.c
  testing/test.h
Labels: bug, install/build

#10196 issue #10195 Cant create C# classes using XSD.exe
  templates/xml/compound.xsd
Labels: enhancement, XML
