Repository doxygen/doxygen, pull requests merged in 2023-05, with the labels that each got.

#10030 Add `point` as email separator
  src/doctokenizer.l
Labels: bug

#10027 Waning in svg files due to unknown attribute.
  src/dotfilepatcher.cpp
Labels: bug, HTML

#10024 Fix latex counter reset and subsubsection
  src/latexdocvisitor.cpp
  templates/latex/doxygen.sty
Labels: bug, LaTeX

#10019 Portuguese translators updated to 1.9.7
  src/translator_br.h
  src/translator_pt.h
Labels: bug

#10034 Spelling correction
  templates/latex/etoc_doxygen.sty
Labels: bug

#10026 Making a number of svg files svg standard conforming
  templates/html/close.svg
  templates/html/doc.svg
  templates/html/docd.svg
  templates/html/doxygen.svg
  templates/html/folderclosed.svg
  templates/html/folderclosedd.svg
  templates/html/folderopen.svg
  templates/html/folderopend.svg
  templates/html/mag.svg
  templates/html/mag_d.svg
  templates/html/mag_sel.svg
  templates/html/mag_seld.svg
Labels: bug, HTML

#10021 Enable possible other LaTeX error modes
  src/config.xml
  src/latexgen.cpp
  templates/latex/header.tex
Labels: enhancement, LaTeX

#10001 No anchor should be created for inherited members
  src/memberdef.cpp
Labels: bug

#10014 issue #10010 SHOW_HEADERFILE doesn't work well for headers with no file extension
  src/util.cpp
Labels: bug, enhancement, C/C++

#10036 Fix for #10035, rename correct file to .bak when using "doxygen -u <some-path>"
  src/util.cpp
Labels: bug

#10025 Incorrect svg file generated
  src/dotfilepatcher.cpp
Labels: bug, HTML

#10039 Silently ignore `</img>` tag
  src/docnode.cpp
Labels: bug

#10038 Fix for some permanent redirects
  README.md
  addon/doxyparse/README.md
Labels: bug

#10042 Check and copy logo file for rtf output
  src/rtfgen.cpp
Labels: bug, RTF

#10022 issue #10015 Add warning when file set for USE_MDFILE_AS_MAINPAGE isn't found
  src/doxygen.cpp
Labels: bug, Markdown

#10029 issue #10023 Sitemap generation
  src/CMakeLists.txt
  src/config.xml
  src/configimpl.l
  src/doxygen.cpp
  src/indexlist.h
  src/sitemap.cpp
  src/sitemap.h
Labels: enhancement, HTML

#10043 issue #9963 [VHDL] - Generic parameter list of generic subprograms are not printed
  src/vhdldocgen.cpp
  src/vhdljjparser.cpp
  vhdlparser/VhdlParser.cc
  vhdlparser/VhdlParser.h
  vhdlparser/vhdlparser.jj
Labels: bug, VHDL

#10047 issue #9963 [VHDL] - Generic parameter list of generic subprograms are not printed
  vhdlparser/VhdlParser.cc
  vhdlparser/VhdlParser.h
  vhdlparser/vhdlparser.jj
Labels: bug, VHDL

#10045 bug 750447 add option to build man pages without timestamps
  src/config.xml
  src/configimpl.l
  src/htmlgen.cpp
  src/latexgen.cpp
  src/mangen.cpp
  src/rtfgen.cpp
Labels: bug, enhancement, HTML, LaTeX, RTF, Man

#10051 issue #10050 Typo in the Doxygen \todo documentation
  doc/commands.doc
Labels: bug, documentation

#9908 Issue #7386 Method parameters documented inline are not present in documentation when using `@copydoc`
  src/docparser.cpp
  src/memberdef.cpp
  src/util.cpp
  src/util.h
Labels: bug

#10057 Regression chm file generation
  doc/CMakeLists.txt
  doc/index.hhp.txt
Labels: bug, documentation

#10058 Changelog correcting tag usage
  doc/changelog.doc
Labels: bug, documentation

#10061 Setting correct version in LaTeX documentation
  doc/CMakeLists.txt
  doc/doxygen_manual_latex.py
Labels: bug, documentation

#10063 parser update to vhdl2017
  vhdlparser/VhdlParser.cc
  vhdlparser/VhdlParser.h
  vhdlparser/VhdlParserConstants.h
  vhdlparser/VhdlParserTokenManager.cc
  vhdlparser/VhdlParserTokenManager.h
  vhdlparser/vhdlparser.jj
Labels: enhancement, VHDL

#10069 Consistent use of TIMESTAMP
  doc_internal/Doxyfile.in
  src/latexgen.cpp
  templates/html/htmlbase.tpl
  templates/latex/header.tex
Labels: bug

#10067 Correct spelling and grammar in MARKDOWN_ID_STYLE docs
  src/config.xml
Labels: bug, documentation

#10059 cleanup doxygen.h, update .gitignore
  .gitignore
  src/doxygen.h
Labels: bug, install/build

#10077 issue #10076 \include and Python
  src/pycode.l
Labels: bug, Python

#10083 Variable names seen as keywords in C++
  src/scanner.l
Labels: bug, C/C++

#10082 Correct warning in case automatic setting of doxygen settings
  src/configimpl.l
Labels: bug

#10075 Check for remaining markers in the used header and footer for HTML and LaTeX
  src/htmlgen.cpp
  src/latexgen.cpp
  src/util.cpp
  src/util.h
Labels: bug, HTML, LaTeX

#10080 issue #10078 Newline missing in parser output
  src/doxygen.cpp
Labels: bug

#10090 Setting correct version in LaTeX documentation
  doc/CMakeLists.txt
Labels: bug, documentation

#10098 Possibility to see the temporary files used for formulas
  src/debug.cpp
  src/debug.h
  src/formula.cpp
Labels: bug
