Repository doxygen/doxygen, pull requests merged in 2023-08, with the labels that each got.

#10203 Remove unused variable
  src/clangparser.cpp
Labels: bug, install/build

#10202 Spelling and layout corrections
  doc/arch.doc
  doc/emojisup.doc
  doc/markdown.doc
  doc_internal/doxygen.md
  src/config.xml
Labels: bug, documentation

#10204 Consistency of use of arguments
  src/docparser.h
Labels: bug, install/build

#10216 Correction in the documentation and internal documentation
  doc/commands.doc
  doc_internal/commands_history.md
  doc_internal/tags_history.md
  src/markdown.cpp
  src/template.cpp
  src/template.h
Labels: bug, documentation

#10217 Correcting Brazilian output
  src/translator_br.h
Labels: bug

#10219 Small layout correction in internal documentation
  src/fortrancode.l
Labels: bug, documentation

#10222 Correcting double debug codes
  src/debug.h
Labels: bug, install/build

#10221 Making resulting internal documentation path independent
  doc_internal/Doxyfile.in
Labels: bug, install/build

#10239 Portuguese translators updated to 1.9.8
  src/translator_br.h
  src/translator_pt.h
Labels: bug

#10155 Detection of missing / superfluous `\n` in warnings
  src/doxygen.cpp
  src/message.cpp
  src/message.h
Labels: bug

#10214 issue #10212 "refid" attribute on "includes" (incType) XML nodes should be marked optional
  templates/xml/compound.xsd
Labels: bug, XML

#10236 issue #10235 separator in warning for C#
  src/memberdef.cpp
Labels: bug, Python

#10237 issue #10235 Python private class incorrectly expects documentation for its methods
  src/pyscanner.l
Labels: bug, Python

#10225 Show not up to date message for translator
  src/language.cpp
Labels: bug

#10226 More flexible include graphs regarding show / hide
  doc/commands.doc
  src/commentscan.l
  src/config.xml
  src/context.cpp
  src/doxygen.cpp
  src/entry.cpp
  src/entry.h
  src/filedef.cpp
  src/filedef.h
  templates/general/layout_default.xml
Labels: enhancement

#10208 Possibility to exclude tests by number
  testing/runtests.py
Labels: enhancement, install/build

#10244 Spelling correction
  src/moduledef.cpp
Labels: bug

#10246 Consistency Python_EXECUTABLE in CMake
  cmake/WindowsEncoding.cmake
  testing/CMakeLists.txt
Labels: bug

#10245 Updating xmlparser for changes in respect to module
  addon/doxmlparser/doxmlparser/compound.py
  addon/doxmlparser/doxmlparser/index.py
Labels: bug

#10210 issue #10209 UML diagrams do not honor HIDE_UNDOC_MEMBERS
  src/dotnode.cpp
Labels: bug

#10164 Add 'extern' to xml output
  addon/doxmlparser/README.md
  addon/doxmlparser/doxmlparser/compound.py
  src/doxygen.cpp
  src/xmlgen.cpp
  templates/xml/compound.xsd
Labels: bug, C/C++, XML

#10249 issue #10238 Doxygen can't document Global functions
  src/commentscan.l
Labels: bug, C/C++

#10248 More flexible directory graphs regarding show / hide
  doc/commands.doc
  src/commentscan.l
  src/config.xml
  src/dirdef.cpp
  src/dirdef.h
  src/doxygen.cpp
  src/entry.cpp
  src/entry.h
Labels: enhancement

#10250 Remove Windows compilation warnings
  libxml/xml.l
  src/aliases.cpp
  src/docparser.cpp
  src/moduledef.cpp
  src/moduledef.h
  src/searchindex_js.cpp
  src/util.cpp
Labels: bug, install/build

#10247 Enable link on line of edge in a directory graph
  src/dotdirdeps.cpp
Labels: bug

#10254 More flexible group dependency graphs regarding show / hide
  doc/commands.doc
  src/commentscan.l
  src/config.xml
  src/dotgroupcollaboration.cpp
  src/dotgroupcollaboration.h
  src/doxygen.cpp
  src/entry.cpp
  src/entry.h
  src/groupdef.cpp
  src/groupdef.h
  templates/general/layout_default.xml
Labels: enhancement

#10259 More flexible inheritance graphs regarding show / hide
  doc/commands.doc
  src/classdef.cpp
  src/classdef.h
  src/commentscan.l
  src/config.xml
  src/doxygen.cpp
  src/entry.cpp
  src/entry.h
  templates/general/layout_default.xml
Labels: enhancement

#10260 Spelling corrections
  doc/commands.doc
Labels: bug, documentation

#10266 Added update of BUILD.txt
  BUILD.txt
Labels: bug, documentation
