Repository doxygen/doxygen, pull requests merged in 2023-12, with the labels that each got.

#10462 Spelling error
  doc/additional.dox
Labels: bug, documentation

#10463 Remove help info about non existing option
  src/doxygen.cpp
Labels: bug, documentation

#10441 Incorrect warning and output with `\image` followed by HTML command
  src/docparser.cpp
  src/doctokenizer.h
  src/doctokenizer.l
Labels: bug

#10461 issue #10460 `\hideinheritancegraph` not working
  src/doxygen.cpp
Labels: bug

#10457 issue #7688 Include markdown file in mainpage.dox
  src/commentcnv.l
Labels: bug

#10470 `undeclared start condition InludeFile`
  src/commentcnv.l
Labels: bug, install/build

#10476 Escape characters in section headers
  doc_internal/commands_internal.md
Labels: bug, documentation

#10480 Incorrect jump to anchor inside page when using CTRL-click
  templates/html/navtree.js
Labels: bug, HTML

#10478 Incorrect warning due to import statement
  src/pre.l
Labels: bug, C/C++

#10482 Spelling correction
  src/classdef.cpp
Labels: bug

#10477 Incorrect setting return state after `\include{doc}`
  src/commentcnv.l
Labels: bug

#10481 issue #6996 Missing definitions for BUILTIN_STL_SUPPORT
  src/stlsupport.cpp
Labels: bug, C/C++

#10486 issue #10485 Parsing error with C++20 requires clause if at the end of the function declaration
  src/scanner.l
Labels: bug, C/C++

#10490 Incorrect line count with `\include{doc}`
  src/scanner.l
Labels: bug, C/C++, Java, C#

#10497 Problem with `\fC` on man pages
  src/mangen.cpp
Labels: bug, Man

#10501 Problem with `\fC` on man pages
  src/mandocvisitor.cpp
  src/mangen.cpp
  src/mangen.h
Labels: bug, Man

#10494 Incorrect handling of `\include{doc}` for Fortran
  src/commentcnv.l
  src/fortranscanner.l
Labels: bug, Fortran

#10495 Incorrect handling of `\include{doc}` for Python
  src/commentcnv.l
  src/pyscanner.l
Labels: bug, Python

#10502 issue #10498 `cmakedefine01 macros are not documented
  src/pre.l
  src/scanner.l
Labels: enhancement

#10503 Handling of spaces around option of `\include{doc}`
  src/commentcnv.l
Labels: bug

#10454 issue #10447 Add explicit links to static pages
  src/doxygen.cpp
  src/index.cpp
  src/sitemap.cpp
  src/sitemap.h
Labels: enhancement, HTML

#10505 Show commands `\htmlinclude[block]` and `\htmlonly[block]` as code in documentation
  doc/commands.dox
Labels: bug, documentation

#10326 issue #10324 [C#] Using expression-bodied functions with generics generates wrong type constraints.
  src/scanner.l
Labels: bug, C#

#10428 bug 793570 Keep the original code indentation
  src/htmlgen.cpp
Labels: enhancement, HTML

#10507 Add option `-t_notime` to doxygen
  src/doxygen.cpp
  src/trace.cpp
  src/trace.h
Labels: enhancement, install/build

#10509 Small documentation correction
  doc/changelog.dox
  doc_internal/releases.md
Labels: bug, documentation

#10512 Update greek translation
  src/translator_gr.h
Labels: bug

#10515 Translator Greek doesn't need adapter
  src/translator_gr.h
Labels: bug

#10514 issue #10511 C# namespace separators are output in C++ style
  src/memberdef.cpp
Labels: bug, C#
