Repository doxygen/doxygen, pull requests merged in 2023-10, with the labels that each got.

#10341 Wrong links for stateToString in internal doxygen documentation
  src/code.l
  src/commentcnv.l
  src/commentscan.l
  src/configimpl.l
  src/constexp.l
  src/declinfo.l
  src/defargs.l
  src/doctokenizer.l
  src/fortrancode.l
  src/lexcode.l
  src/lexscanner.l
  src/pre.l
  src/pycode.l
  src/pyscanner.l
  src/scanner.l
  src/sqlcode.l
  src/vhdlcode.l
  src/xmlcode.l
Labels: bug

#10342 Spelling correction
  src/pre.l
Labels: bug

#10347 issue #10344 "param ?callable $callback" misinterpreted as undocumented parameter
  src/doctokenizer.l
Labels: bug, PHP

#10346 issue #10343 Missing 'Referenced by' links for macros (C/C++)
  src/doxygen.cpp
Labels: bug, C/C++

#10345 Add project icon to HTML output
  doc/CMakeLists.txt
  doc/Doxyfile
  doc_internal/Doxyfile.in
  examples/CMakeLists.txt
  examples/baseexample.cfg
  src/config.xml
  src/doxygen.cpp
  src/htmlgen.cpp
  src/util.cpp
  templates/html/header.html
Labels: enhancement, HTML

#10348 Spelling correction
  src/codefragment.cpp
Labels: bug

#10338 issue #10306 Some intra-page links include the HTML file name
  src/htmldocvisitor.cpp
  src/htmldocvisitor.h
  src/htmlgen.cpp
  src/htmlgen.h
Labels: enhancement

#10325 Remove obsolete tagfile test
  src/classdef.cpp
Labels: bug

#10289 Submit warning when the ingroup command is used with an non-existing group name
  src/groupdef.cpp
Labels: bug

#10323 Prevent reading tag file multiple times
  src/doxygen.cpp
  src/doxygen.h
Labels: bug

#10296 bug_651081 Inconsistency between @page and @subpage parsing
  src/commentscan.l
Labels: bug

#10352 Submit warning when the ingroup command is used with an non-existing group name (2)
  src/doxygen.cpp
  src/groupdef.cpp
Labels: bug

#10360 Remove double resetting for htmlhelp
  src/configimpl.l
Labels: bug

#10361 Disable `HTML_COPY_CLIPBOARD` for generating doxygen htmlhelp documentation
  doc/Doxyfile_chm
Labels: bug, documentation

#10358 Recognition of `<=` inside template construct
  src/scanner.l
Labels: bug, C/C++

#10359 Recognition of `>=` inside inintializer construct
  src/scanner.l
Labels: bug, C/C++

#10357 issue #10356 CopyDoc target is parsed incorrectly
  src/docparser.cpp
Labels: bug

#10355 Reinstate list of brief functions
  src/memberdef.cpp
Labels: bug

#10363 Recognition of `>=` inside template construct
  src/scanner.l
Labels: bug, C/C++

#10365 Documentation correction for sqlite3
  src/config.xml
Labels: bug, documentation

#10364 Documentation `HTML_COPY_CLIPBOARD`
  src/config.xml
Labels: bug, documentation

#10286 add bibtex to testing readme as dependency
  testing/README.txt
Labels: bug, documentation

#10366 issue #10353 Doxygen cannot handle `#define` after PlantUML
  src/pre.l
Labels: bug, C/C++

#10373 Unused `yyColNr` in code.l
  src/code.l
Labels: C/C++, beautify

#10371 Properties in python "namespaces"
  src/filedef.cpp
  src/layout.cpp
  src/namespacedef.cpp
  templates/general/layout_default.xml
Labels: bug, Python

#10378 issue #10377 Wrong syntax for output of non-C++ deprecation lists for enum members
  src/memberdef.cpp
Labels: bug, Java, C#, Python

#10375 More consistent warning messages
  src/codefragment.cpp
  src/docnode.cpp
  src/docparser.cpp
  src/doxygen.cpp
  src/scanner.l
  src/util.cpp
Labels: bug

#10383 Handling of relative include path in preprocessor
  src/pre.l
Labels: bug

#10381 issue #10351 Search subpart research after a search
  templates/html/search.js
Labels: bug, HTML

#10384 Handling comment in macro name
  src/pre.l
Labels: bug

#10385 Handling of `import` in non cpp files
  src/scanner.l
Labels: bug, C/C++, Java

#10389 Handling of relative include path in code output processor
  src/code.l
Labels: bug
