Repository doxygen/doxygen, pull requests merged in 2023-02, with the labels that each got.

#9835 Debugging documentation
  doc/arch.doc
Labels: bug, install/build, documentation

#9829 Not documented parameter in case of `const <type>` without argument name
  src/defargs.l
Labels: bug, C/C++

#9833 issue #9831 @exception description paragraph does not accept @ref tag
  src/commentcnv.l
Labels: bug, Python

#9827 Remove common leading space from code snippets
  doc/commands.doc
  src/docbookvisitor.cpp
  src/docnode.cpp
  src/docnode.h
  src/htmldocvisitor.cpp
  src/latexdocvisitor.cpp
  src/mandocvisitor.cpp
  src/markdown.h
  src/perlmodgen.cpp
  src/printdocvisitor.h
  src/rtfdocvisitor.cpp
  src/util.cpp
  src/util.h
  src/xmldocvisitor.cpp
Labels: enhancement

#9837 Consistency in used debug terminology
  src/layout.cpp
  src/tagreader.cpp
Labels: bug

#9841 docs: Ensure examples' "click here for output" HTML links point to the most useful place
  doc/commands.doc
  doc/diagrams.doc
  doc/docblocks.doc
Labels: bug, documentation

#9847 issue #9845 C# parser reads "$" as "Interpolated string expression" which is not correct
  src/scanner.l
Labels: bug, C#

#9818 issue #9816 Missing search files in QCH content
  src/searchindex_js.cpp
Labels: bug, HTML

#9856 Handling debug information in in respect to mscgen
  deps/libmscgen/mscgen_lexer.l
Labels: bug, install/build

#9844 Build: Re-enable LEX_FILES_{H,CPP}, streamline
  src/CMakeLists.txt
Labels: enhancement, install/build

#9860 qcstring.h: Fix conversion method layout
  src/qcstring.h
Labels: beautify

#9610 GHC_NO_DIRENT_D_TYPE should be defined on Haiku
  deps/filesystem/filesystem.hpp
Labels: enhancement, install/build

#9814 issue #9810 Math in bibliography
  src/cite.cpp
  src/cite.h
Labels: bug

#9862 Fix server based search for PHP 8.1
  templates/html/search_functions.php
Labels: bug, HTML

#9865 Spelling correction
  src/config.xml
Labels: bug

#9820 Windows compilation warnings
  src/code.l
  src/fortrancode.l
  src/pycode.l
  src/threadpool.h
  src/vhdlcode.l
Labels: bug

#9864 Double identifiers due to mapping to same id of file names
  src/markdown.cpp
  testing/055/md_055__markdown.xml
  testing/055_markdown.md
Labels: bug, Markdown

#9848 issue #9846 Python functions with and without type hints displayed inconsistently.
  src/pyscanner.l
Labels: bug, Python

#9866 Incorrect warning about not matching number of `#if` / `#endif`
  src/pre.l
Labels: bug, C/C++

#9728 issue #9719 \ref command does not insert title of referenced page
  doc/commands.doc
  src/commentscan.l
  src/markdown.cpp
Labels: bug, Markdown

#9870 Documentation `\ianchor` correction
  doc_internal/commands_internal.md
Labels: bug, documentation

#9868 issue #6737 `*/` inside code block
  src/scanner.l
Labels: bug, C/C++

#9872 bug 752410 make.bat on UNC paths will start to erase files from c:\windows\system32
  src/latexgen.cpp
Labels: bug, LaTeX

#9851 bug 549438 VERBATIM_HEADERS - only works with header files with file type
  src/filedef.cpp
Labels: bug, C/C++

#9873 Improvement of position of open / closed folder icon
  templates/html/doxygen.css
Labels: bug, HTML

#9875 Compilation warning
  src/cite.cpp
Labels: bug, install/build

#9881 Portuguese translators updated to 1.9.7v2
  doc/translator.py
  src/translator_br.h
  src/translator_pt.h
Labels: bug

#9880 Compilation warnings in respect to sprintf
  src/cite.cpp
  src/commentscan.l
  src/docnode.cpp
  src/formula.cpp
  src/rtfgen.cpp
  src/util.cpp
  src/vhdldocgen.cpp
Labels: bug, install/build
