Repository doxygen/doxygen, pull requests merged in 2023-01, with the labels that each got.

#9762 Labels were not visible in dark mode for some dot graphs
  src/dotlegendgraph.cpp
Labels: bug, documentation

#9764 Incorrect handling of unordered lists in docbook
  src/docbookvisitor.cpp
Labels: bug, DocBook

#9765 Spelling corrections
  src/memberdef.cpp
  src/scanner.l
Labels: bug

#9761 issue #9726 \ref command doesn't perform in LaTeX as described in the documentation
  doc/commands.doc
  src/docnode.cpp
  src/docnode.h
  src/latexdocvisitor.cpp
  src/latexdocvisitor.h
  templates/latex/doxygen.sty
Labels: enhancement, documentation, LaTeX

#9753 Automatic generation history information for commands / tags
  doc_internal/CMakeLists.txt
  doc_internal/Doxyfile.in
  doc_internal/cmds_tags.py
  doc_internal/commands_history.md
  doc_internal/tags_history.md
Labels: enhancement, install/build, documentation

#9768 Removed extra space in `UML_LOOK` diagrams for constructor
  src/dotnode.cpp
Labels: bug

#9770 Coloring in languages table in manual
  doc/translator.py
Labels: bug, documentation

#9769 issue #9713 Variables show in "Related Functions" section
  src/context.cpp
  src/index.cpp
  src/layout.cpp
  src/translator.h
  src/translator_adapter.h
  src/translator_br.h
  src/translator_cz.h
  src/translator_en.h
  src/translator_es.h
  src/translator_nl.h
  src/translator_pt.h
  src/translator_sv.h
Labels: bug

#9767 issue #9763 Python docstring: brief and detailed description not correctly separated by blank line
  src/pyscanner.l
Labels: bug, Python

#9757 Fix conversion of ghc::filesystem::path to std::string
  src/portable.cpp
Labels: bug, install/build

#9773 Escape `-` sign in fontname settings substring as well
  src/qcstring.h
Labels: bug

#9774 issue #9771 Escaped double-quote in Objective-C string confuses parser
  src/scanner.l
Labels: bug, C/C++

#9742 Better representation of brief (union / struct) descriptions in HTML
  src/classdef.cpp
  src/conceptdef.cpp
  src/dirdef.cpp
  src/docbookgen.cpp
  src/docbookgen.h
  src/groupdef.cpp
  src/htmlgen.cpp
  src/htmlgen.h
  src/latexgen.cpp
  src/latexgen.h
  src/mangen.cpp
  src/mangen.h
  src/memberdef.cpp
  src/memberlist.cpp
  src/namespacedef.cpp
  src/outputgen.h
  src/outputlist.h
  src/rtfgen.cpp
  src/rtfgen.h
  src/vhdldocgen.cpp
Labels: bug, HTML

#9775 Escape `-` sign in fontname settings substring as well
  src/configimpl.l
  src/dotattributes.h
Labels: bug

#9646 Consistency between HTML and LaTeX / RTF for examples
  src/index.cpp
  src/rtfgen.cpp
  src/translator.h
  src/translator_am.h
  src/translator_ar.h
  src/translator_bg.h
  src/translator_br.h
  src/translator_ca.h
  src/translator_cn.h
  src/translator_cz.h
  src/translator_de.h
  src/translator_dk.h
  src/translator_en.h
  src/translator_eo.h
  src/translator_es.h
  src/translator_fa.h
  src/translator_fi.h
  src/translator_fr.h
  src/translator_gr.h
  src/translator_hi.h
  src/translator_hr.h
  src/translator_hu.h
  src/translator_id.h
  src/translator_it.h
  src/translator_jp.h
  src/translator_kr.h
  src/translator_lt.h
  src/translator_lv.h
  src/translator_mk.h
  src/translator_nl.h
  src/translator_no.h
  src/translator_pl.h
  src/translator_pt.h
  src/translator_ro.h
  src/translator_ru.h
  src/translator_sc.h
  src/translator_si.h
  src/translator_sk.h
  src/translator_sr.h
  src/translator_sv.h
  src/translator_tr.h
  src/translator_tw.h
  src/translator_ua.h
  src/translator_vi.h
  src/translator_za.h
Labels: bug, HTML, LaTeX, RTF

#9048 Union / Struct indicated as Class in the Xref list
  src/classdef.cpp
  src/translator.h
  src/translator_adapter.h
  src/translator_br.h
  src/translator_cn.h
  src/translator_cz.h
  src/translator_en.h
  src/translator_gr.h
  src/translator_nl.h
  src/translator_pt.h
  src/translator_sv.h
  vhdlparser/vhdlstring.h
Labels: bug

#9777 Adding translations for the Dutch language in respect to OPTIMIZATION output flags
  src/translator_nl.h
Labels: bug

#9778 bug 594746 [html] wrong <title> value, missing title in page for "Members" pages
  src/index.cpp
  src/translator.h
  src/translator_adapter.h
  src/translator_en.h
  src/translator_nl.h
Labels: enhancement, HTML

#9776 Incorrect line counting for inbody docs
  src/commentscan.l
Labels: bug

#9791 Spelling corrections
  deps/spdlog/README.md
  deps/spdlog/include/spdlog/details/tcp_client.h
  deps/spdlog/include/spdlog/sinks/android_sink.h
Labels: bug

#9790 Spelling correction
  src/doxygen.cpp
Labels: bug

#9794 Lexical analyzer extra `(for: )` for some lexers
  src/debug.cpp
Labels: bug

#9797 issue #8790 doxyrest command returns "duplicate member id group..."
  addon/doxmlparser/doxmlparser/compound.py
  src/xmlgen.cpp
  templates/xml/compound.xsd
Labels: bug, XML

#9792 Collect warnings and output them at the end
  doc_internal/Doxyfile.in
  src/config.xml
  src/message.cpp
Labels: enhancement

#9798 issue #8790 doxyrest command returns "duplicate member id group..."
  addon/doxmlparser/doxmlparser/compound.py
Labels: bug, XML

#9800 Consistency between return type and usage of pid
  src/portable.cpp
  src/portable.h
Labels: bug, install/build

#9795 Handling of verbatim type sections in preprocessor
  src/pre.l
Labels: bug

#9803 Handling of verbatim type sections in preprocessor (formula end)
  src/pre.l
Labels: bug

#9804 Option handling in respect to `-t`
  src/doxygen.cpp
Labels: bug

#9452 bug_676971 HIDE_SCOPE_NAMES also hides template declarations of template member functions in detail description
  src/memberdef.cpp
Labels: bug

#9443 bug_665439 FILE_VERSION_FILTER incorrectly run for file references from a tagfile with filename "<tagfile>:/my/path"
  src/filedef.cpp
Labels: enhancement

#9806 Layout of copyright notice in manual
  doc/index.doc
Labels: bug, documentation

#9805 Prevent list items in section titles
  src/docparser.cpp
  src/doctokenizer.h
  src/doctokenizer.l
Labels: bug, LaTeX

#9785 Consistency in HTML output with multiple runs
  src/dotfilepatcher.cpp
Labels: bug, HTML

#9807 Handling of `\noop` command in preprocessor
  src/pre.l
Labels: bug

#9789 issue #9779 Doxygen doesn't correctly treat nested \if statements
  src/commentscan.l
Labels: bug

#9808 Image appears in the middle of code in the internal documentation
  src/dotgraph.cpp
  src/index.cpp
Labels: bug, install/build

#9591 Warning during compilation on Windows systems
  src/clangparser.cpp
  src/configimpl.h
  src/constexp.l
  src/docbookgen.cpp
  src/docgroup.cpp
  src/docnode.h
  src/dotnode.cpp
  src/doxygen.cpp
  src/filedef.cpp
  src/fortrancode.l
  src/htmldocvisitor.cpp
  src/htmlgen.cpp
  src/index.cpp
  src/latexgen.cpp
  src/lexscanner.h
  src/mandocvisitor.cpp
  src/markdown.cpp
  src/memberdef.cpp
  src/msc.cpp
  src/outputgen.h
  src/plantuml.cpp
  src/pycode.l
  src/qhp.cpp
  src/sqlcode.l
  src/symbolresolver.cpp
  src/translator_cn.h
  src/translator_hi.h
  src/translator_hu.h
  src/translator_sv.h
  src/util.cpp
  src/vhdlcode.l
  src/vhdldocgen.cpp
  src/xmlcode.l
  vhdlparser/ErrorHandler.h
  vhdlparser/VhdlParserErrorHandler.hpp
  vhdlparser/vhdlstring.h
Labels: bug

#9809 Issue #9802 enumvalueType should not be a mixed type
  templates/xml/compound.xsd
Labels: bug, doxmlparser

#9811 Coverity warning
  src/commentscan.l
Labels: bug

#9815 Windows compilation warnings
  src/docbookgen.cpp
  src/htmlgen.cpp
  src/latexdocvisitor.cpp
  src/latexgen.cpp
  src/mangen.cpp
  src/rtfgen.cpp
Labels: bug, install/build

#9817 Adding "engine" ebnf for plantuml
  addon/doxmlparser/doxmlparser/compound.py
  doc/commands.doc
  src/docnode.cpp
  templates/xml/compound.xsd
Labels: enhancement

#9821 Adding "engine" hcl and regex for plantuml
  addon/doxmlparser/doxmlparser/compound.py
  doc/commands.doc
  src/docnode.cpp
  templates/xml/compound.xsd
Labels: enhancement
