Repository doxygen/doxygen, pull requests merged in 2023-11, with the labels that each got.

#10390 issue #10388 Can't link to a tagfile page in DoxygenLayout?
  src/layout.cpp
  src/msc.cpp
Labels: bug

#10398 Portuguese translators updated to 1.10.0
  src/translator_br.h
  src/translator_pt.h
Labels: bug

#10405 Remove double mentioning of 'module' in compound.xsd
  addon/doxmlparser/doxmlparser/compound.py
  templates/xml/compound.xsd
Labels: bug, XML

#10403 Miscounting in case of markdown links
  src/markdown.cpp
Labels: bug, Markdown

#10416 Issue #10414 Report warning with wrong file and wrong line number
  src/commentscan.l
Labels: bug

#10412 Remove unused css entry
  doc/doxygen_manual.css
Labels: bug, HTML, beautify

#10411 Remove double entries
  deps/jquery/sass/_sm-dox.scss
  doc/doxygen_manual.css
  doc_internal/doc_internal.css
  templates/html/doxygen.css
Labels: bug, documentation, HTML, beautify

#10408 Line miscounting in case of structural indicator
  src/commentscan.l
Labels: bug

#10419 Prevent endless loop for `\include{doc}`
  src/docnode.cpp
Labels: bug

#10425 Rename `.doc` to `.dox` in doxygen documentation
  doc/CMakeLists.txt
  doc/Doxyfile
  doc/arch.dox
  doc/autolink.dox
  doc/changelog.dox
  doc/commands.dox
  doc/custcmd.dox
  doc/customize.dox
  doc/diagrams.dox
  doc/docblocks.dox
  doc/doxygen_usage.dox
  doc/doxywizard_usage.dox
  doc/emojisup.dox
  doc/external.dox
  doc/extsearch.dox
  doc/faq.dox
  doc/features.dox
  doc/formulas.dox
  doc/grouping.dox
  doc/htmlcmds.dox
  doc/index.dox
  doc/install.dox
  doc/language.tpl
  doc/lists.dox
  doc/markdown.dox
  doc/output.dox
  doc/perlmod.dox
  doc/preprocessing.dox
  doc/searching.dox
  doc/starting.dox
  doc/tables.dox
  doc/translator.py
  doc/trouble.dox
  doc/xmlcmds.dox
  doc_internal/cmds_tags.py
Labels: bug, documentation

#10426 Spelling corrections
  doc/changelog.dox
Labels: bug, documentation

#10433 Coverity correction
  src/commentcnv.l
Labels: bug, install/build

#10432 File settings with just a directory are silently ignored
  src/doxygen.cpp
Labels: bug

#10437 Issue #10414 Report warning with wrong file and wrong line number
  src/commentscan.l
Labels: bug

#10429 Fix Discarding of Slice Types during Namespace Doc Generation
  src/namespacedef.cpp
Labels: bug

#10443 Remove empty statement after `}`
  src/caseconvert.h
  src/caseconvert.py
Labels: bug, install/build, beautify

#10442 Give functions override attribute
  src/classdef.cpp
  src/conceptdef.cpp
  src/definitionimpl.h
  src/dirdef.cpp
  src/filedef.cpp
  src/groupdef.cpp
  src/memberdef.cpp
  src/moduledef.cpp
  src/namespacedef.cpp
  src/pagedef.cpp
Labels: bug, install/build, beautify

#10402 Handling of protection of the Java enum constructs.
  src/scanner.l
Labels: bug, Java

#10448 Fix typos
  src/config.xml
Labels: bug, documentation

#10450 Add range possibility in xsd
  addon/doxmlparser/doxmlparser/compound.py
  templates/xml/compound.xsd
Labels: enhancement, XML

#10455 Add range possibility in xsd, update compound.py
  addon/doxmlparser/doxmlparser/compound.py
Labels: enhancement, XML
