Repository doxygen/doxygen, pull requests merged in 2024-08, with the labels that each got.

#11029 issue #11016 Faulty xml generated when markdown header is too deep
  src/htmlgen.cpp
  templates/html/doxygen.css
Labels: bug, HTML

#11032 issue #11031 extra WS in @brief docu block break layout
  src/commentcnv.l
Labels: bug

#11049 Improve readability of codebase
  src/anchor.cpp
  src/arguments.h
  src/defargs.l
  src/memberdef.cpp
  src/scanner.l
  src/util.cpp
  src/xmlgen.cpp
Labels: beautify

#11051 Better type safety of enums
  src/classdef.cpp
  src/defgen.cpp
  src/definition.cpp
  src/dia.cpp
  src/dia.h
  src/docbookgen.cpp
  src/docbookvisitor.cpp
  src/docsets.cpp
  src/dot.cpp
  src/dotcallgraph.cpp
  src/dotclassgraph.cpp
  src/dotgfxhierarchytable.cpp
  src/dotgraph.cpp
  src/dotgraph.h
  src/dotgroupcollaboration.cpp
  src/dotincldepgraph.cpp
  src/dotlegendgraph.cpp
  src/dotnode.cpp
  src/doxygen.cpp
  src/filedef.cpp
  src/fortrancode.h
  src/fortranscanner.h
  src/groupdef.cpp
  src/htmldocvisitor.cpp
  src/htmlgen.cpp
  src/latexdocvisitor.cpp
  src/latexgen.cpp
  src/memberdef.cpp
  src/memberlist.cpp
  src/moduledef.cpp
  src/msc.cpp
  src/msc.h
  src/namespacedef.cpp
  src/perlmodgen.cpp
  src/rtfdocvisitor.cpp
  src/rtfgen.cpp
  src/sqlite3gen.cpp
  src/trace.h
  src/types.h
  src/util.cpp
  src/vhdldocgen.cpp
  src/vhdljjparser.cpp
  src/vhdljjparser.h
  src/xmlgen.cpp
  templates/latex/doxygen.sty
  vhdlparser/VhdlParser.cc
  vhdlparser/VhdlParser.h
  vhdlparser/vhdlparser.jj
Labels: beautify

#11053 Better type safety of enums (2)
  src/docnode.cpp
  src/docnode.h
  src/docparser.cpp
  src/docparser_p.h
  src/doctokenizer.h
  src/doctokenizer.l
Labels: beautify

#11018 issue #11015 In Doxygen 1.11.0, Include Graphs are not made for Java
  src/scanner.l
Labels: enhancement, Java

#11055 Selection possibility of values from an enum (class) by means of `is_any_of`
  src/docnode.cpp
  src/docparser.cpp
  src/doctokenizer.h
  src/doctokenizer.l
  src/util.h
Labels: enhancement, beautify

#11058 issue #11056 HTML: Interactive SVG "viewHeight" is not defined
  src/dotfilepatcher.cpp
Labels: bug, HTML

#11057 Consistency enum class Tokens
  src/doctokenizer.h
  src/doctokenizer.l
Labels: bug

#11061 Incorrect open / closing tags in changelog
  doc/changelog.dox
Labels: bug, documentation

#11062 Detect escaped `\cond` command at end of line
  src/pre.l
Labels: bug

#11066 Coverity warning
  src/doctokenizer.h
Labels: bug

#11067 Remove duplicate lines
  src/markdown.cpp
  src/translator_hr.h
Labels: bug, beautify

#11077 Update translator_gr.h
  src/translator_gr.h
Labels: bug

#11072 End of HTML style special comment marker in documentation
  doc/htmlcmds.dox
Labels: bug, documentation

#11074 issue #11071 Extra spaces added by GFM special comment parsing cause verbatim blocks
  src/commentcnv.l
Labels: bug

#11073 Incorrect handling of spaces before `@page` command
  src/markdown.cpp
Labels: bug

#11089 Greek and Russian translators are up to date
  src/translator_gr.h
  src/translator_ru.h
Labels: bug, documentation

#11092 Coverity bug 20240822 (1)
  src/translator_ru.h
Labels: bug

#11093 Coverity bug 20240822 (2)
  src/doxygen.cpp
Labels: bug

#11090 Incorrect handling of spaces before `@page` command (2)
  src/markdown.cpp
Labels: bug, Markdown

#11087 issue #11082 C include format error
  src/code.l
Labels: enhancement, C/C++

#11104 Plantuml cache file name
  src/plantuml.cpp
Labels: bug

#11097 Compilation error under Cygwin on language.cpp: "too many sections"
  CMakeLists.txt
Labels: bug, install/build

#11108 issue #11107 PHP heredocs with double quotes stop doxygen
  src/scanner.l
Labels: enhancement, PHP

#11110 Fixed a few Doxyfile typos
  src/config.xml
Labels: bug, documentation

#11068 Consistency enum class CommandType / HtmlTagType
  src/cmdmapper.cpp
  src/cmdmapper.h
  src/docnode.cpp
  src/docparser.cpp
  src/docparser_p.h
Labels: enhancement

#11075 Issue #9921 `HIDE_SCOPE_NAMES` and `\ref`
  src/docnode.cpp
Labels: bug
