Repository doxygen/doxygen, pull requests merged in 2024-01, with the labels that each got.

#10520 issue #10504 A list inside an alias on a markdown page seems broken, it repeats the alias indefinitely
  src/docnode.cpp
  src/doctokenizer.l
Labels: bug

#10528 Warning about invalid argument with `\iline` command
  src/doctokenizer.l
Labels: bug

#10527 Adding "engine" files for plantuml
  addon/doxmlparser/doxmlparser/compound.py
  doc/commands.dox
  src/docnode.cpp
  templates/xml/compound.xsd
Labels: enhancement

#10538 Rendering of general `dl.section` styles
  templates/html/doxygen.css
Labels: bug, HTML

#10537 Make the menu bar stick to the top of the screen when scrolling
  src/ftvhelp.cpp
  src/htmlgen.cpp
  templates/html/footer.html
  templates/html/menu.js
  templates/html/resize.js
Labels: bug, enhancement, HTML

#10539 Add `HTML_CODE_FOLDING` possibility to CHM
  doc/Doxyfile_chm
  src/configimpl.l
  src/htmlgen.cpp
Labels: bug, HTML

#10542 Make `HTML_CODE_FOLDING` always possible
  src/docbookgen.h
  src/filedef.cpp
  src/htmlgen.cpp
  src/htmlgen.h
  src/index.cpp
  src/index.h
  src/latexgen.h
  src/mangen.h
  src/outputlist.h
  src/rtfgen.h
Labels: bug, HTML

#10540 Refactor `contexts_t` and `contexts` in `htmldocvisitor.cpp`
  src/htmldocvisitor.cpp
Labels: bug, install/build

#10547 issue #10546 crash when clang enable
  src/clangparser.cpp
Labels: bug

#10548 Block command in section title
  src/commentscan.l
Labels: bug

#10545 issue #10544 Doxygen omits closing '>' in method returning `std::function< void(A *) >`
  src/doxygen.cpp
Labels: bug, C/C++

#10549 Dependency in examples directory
  examples/CMakeLists.txt
Labels: bug, documentation

#10541 Display of index on index page.
  src/htmlgen.cpp
Labels: enhancement, HTML

#10554 add enum type in PERLMOD
  src/perlmodgen.cpp
Labels: bug, needinfo

#10557 issue #10552 thick space in latex formula causes error
  src/fortranscanner.l
Labels: bug, Fortran

#10556 Consistency for use of `<code>`
  src/scanner.l
Labels: bug, C/C++, C#

#10533 Handling C# `<code>` parts
  src/commentscan.l
Labels: bug, C#

#10521 issue #10516 @copybrief command does not take effect with 1.10.0
  src/commentscan.l
Labels: bug

#10561 issue #10516 `@copybrief` command does not take effect with 1.10.0
  src/commentscan.l
Labels: bug

#10560 Make `SrcLangExt` an `enum class`
  src/clangparser.cpp
  src/classdef.cpp
  src/code.l
  src/commentcnv.l
  src/commentscan.l
  src/conceptdef.cpp
  src/declinfo.l
  src/defargs.l
  src/definition.cpp
  src/docbookgen.cpp
  src/docnode.cpp
  src/docparser.cpp
  src/docsets.cpp
  src/dotgfxhierarchytable.cpp
  src/dotnode.cpp
  src/doxygen.cpp
  src/entry.cpp
  src/filedef.cpp
  src/fortrancode.l
  src/fortranscanner.l
  src/ftvhelp.cpp
  src/groupdef.cpp
  src/htmlgen.cpp
  src/index.cpp
  src/layout.cpp
  src/lexcode.l
  src/markdown.cpp
  src/memberdef.cpp
  src/memberlist.cpp
  src/moduledef.cpp
  src/namespacedef.cpp
  src/perlmodgen.cpp
  src/pre.l
  src/pyscanner.l
  src/scanner.l
  src/searchindex.cpp
  src/symbolresolver.cpp
  src/tagreader.cpp
  src/trace.h
  src/translator_br.h
  src/translator_cn.h
  src/translator_cz.h
  src/translator_en.h
  src/translator_es.h
  src/translator_gr.h
  src/translator_nl.h
  src/translator_pt.h
  src/translator_sv.h
  src/types.h
  src/util.cpp
  src/util.h
  src/vhdldocgen.cpp
  src/vhdljjparser.cpp
  src/xmlgen.cpp
Labels: bug, install/build

#10576 issue #10568 Navtree broken for namespace-links if namespace included in groups
  src/index.cpp
Labels: bug, HTML

#10574 issue #10567 Incorrectly closed markdown code block causes doxygen to forget about consecutive macro definitions
  src/fortranscanner.l
  src/lexscanner.l
  src/pre.l
  src/scanner.l
Labels: bug

#10575 issue #10573 Behavior of quotes in markdown type of links
  src/markdown.cpp
Labels: bug, Markdown

#10580 No extra space after `fileinfo` and `lineinfo` commands
  src/commentscan.l
Labels: bug

#10578 Fix some typos in options description
  src/config.xml
Labels: bug, documentation

#10571 Handling commands in section titles.
  src/commentscan.l
  templates/latex/header.tex
Labels: bug

#10587 Better warning when in Fortran a comment block is not closed
  src/fortranscanner.l
Labels: enhancement, Fortran

#10583 Improve warnings
  src/docnode.cpp
  src/docnode.h
  src/docparser.cpp
  src/doctokenizer.h
Labels: beautify

#10581 Incorrect line number and filename after `\include{doc}` and `\snippet{doc}`
  src/commentcnv.l
  src/commentscan.l
  src/docparser.cpp
Labels: bug

#10590 Spelling correction
  src/commentscan.l
Labels: bug

#10585 Show emoji in HTML treeview
  src/textdocvisitor.cpp
  src/util.cpp
Labels: bug, HTML

#10595 Problem generating PDF with some commands in section headers
  src/latexdocvisitor.cpp
  src/latexdocvisitor.h
Labels: bug, LaTeX

#10592 Endless loop in lists due to #10504 / #10520
  src/docnode.cpp
Labels: bug

#10596 No mention of citation reference in treeview
  src/textdocvisitor.cpp
  src/textdocvisitor.h
Labels: bug, HTML

#10600 Link missing in documentation of `INPUT_FILE_ENCODING`
  src/config.xml
Labels: documentation

#10591 issue #10586 Backslash + quote mark causes doxygen not to generate documentation
  src/code.l
  src/commentcnv.l
  src/pre.l
  src/scanner.l
Labels: bug, C#

#10601 Support `link` / `endlink` command in section title
  src/commentscan.l
Labels: bug

#10603 Updated polish translation
  doc/maintainers.txt
  src/translator_pl.h
Labels: bug

#10602 Commands `\anchor` and `\ianchor` in section titles
  src/commentscan.l
Labels: bug

#10610 Keep latex template files with Unix EOL
  .gitattributes
Labels: bug, LaTeX

#10611 CRLF in files
  deps/libmscgen/mscgen_safe.c
  deps/libmscgen/mscgen_safe.h
  deps/libmscgen/mscgen_usage.h
  deps/libmscgen/mscgen_utf8.c
  deps/libmscgen/mscgen_utf8.h
  deps/spdlog/LICENSE
  deps/spdlog/README.md
  deps/spdlog/cmake/spdlogConfig.cmake.in
  deps/svg/svg-3.1.2.js
  doc/translator.py
Labels: bug, install/build
