Repository doxygen/doxygen, pull requests merged in 2024-05, with the labels that each got.

#10845 Update translator_de.h
  src/translator_de.h
Labels: bug

#10852 issue #10851 Unable to build documentation from "master" branch
  src/latexgen.cpp
  templates/latex/header.tex
Labels: bug, install/build, LaTeX

#10795 issue #10766 C# cref or \ref doesn't work without full namespace, even for classes in same namespace
  src/docnode.cpp
  src/docparser.cpp
Labels: bug, Java, C#, Python

#10854 issue #10850 Incorrect links generated for cross-references with same name when using tagfiles
  src/doxygen.cpp
  src/tagreader.cpp
  src/util.cpp
Labels: bug

#10856 Don't import links from tags into crawl file
  src/sitemap.cpp
Labels: bug, HTML

#10857 QT help problems with tag files
  src/configimpl.l
  src/qhp.cpp
  src/qhp.h
Labels: HTML

#10860 bug 783580 hhc.exe fail when a class inherit a class from an external project
  src/configimpl.l
  src/htmlhelp.cpp
Labels: bug, HTML

#10862 issue #10859 More restrictive block-id character set in Doxygen >= 1.10
  src/commentcnv.l
Labels: bug

#10864 issue #10863 Multiple <dd> elements not rendered correctly
  src/docbookvisitor.cpp
  src/docnode.cpp
  src/docparser_p.h
  src/latexdocvisitor.cpp
  src/mandocvisitor.cpp
Labels: bug

#10871 Code sections in Perl documentation not expandable anymore
  templates/html/dynsections.js
Labels: bug

#10875 Fixing compilation warnings
  src/markdown.cpp
Labels: bug, install/build

#10876 issue #10866 Exiting with exit code 1, no warnings, no errors when executed on Github Action
  src/doxygen.cpp
  src/message.cpp
Labels: bug, enhancement

#10884 Warning in case of `0.` as start of a list.
  src/doctokenizer.l
Labels: bug

#10879 Show backtick code span as code
  doc/changelog.dox
Labels: bug, documentation

#10880 issue #10878 semi-colon after a formula causes error
  src/fortranscanner.l
Labels: bug, Fortran

#10877 Cleanup `Doxygen::terminating`
  src/doxygen.cpp
  src/doxygen.h
  src/message.cpp
Labels: bug, beautify

#10883 xmllint error in combination with addindex command
  src/htmldocvisitor.cpp
Labels: bug, HTML

#10874 Update BUILD.txt with dependencies/docker
  BUILD.txt
Labels: install/build, documentation

#10885 Redirecting link corrected
  doc/install.dox
Labels: bug, documentation

#10891 Fix buffer overflow in Markdown parser
  src/markdown.cpp
Labels: bug, Markdown

#10886 Remove temporary file
  src/dia.cpp
  src/diagram.cpp
  src/docparser.cpp
  src/msc.cpp
  src/plantuml.cpp
Labels: bug, LaTeX

#10888 Use CMake's FindIconv (see #10887)
  .codedocs
  CMakeLists.txt
  addon/doxyapp/CMakeLists.txt
  addon/doxyparse/CMakeLists.txt
  cmake/FindIconv.cmake
  deps/iconv_winbuild/.gitignore
  deps/iconv_winbuild/include/iconv.h
  deps/iconv_winbuild/x64/iconv.lib
  deps/iconv_winbuild/x86/iconv.lib
  src/CMakeLists.txt
Labels: install/build

#10899 issue #10989 bison: error: '%name-prefix' and '%define api.prefix' cannot be used together
  CMakeLists.txt
  src/CMakeLists.txt
  src/commentscan.l
Labels: bug, install/build
