Repository doxygen/doxygen, pull requests merged in 2024-12, with the labels that each got.

#11266 Warning with not closed stylchange
  src/docnode.h
  src/docparser.cpp
Labels: bug

#11262 Spelling correction
  src/parserintf.h
Labels: bug

#11268 Better warning in case of an internal error of a layout element
  src/classdef.cpp
  src/conceptdef.cpp
  src/dirdef.cpp
  src/filedef.cpp
  src/groupdef.cpp
  src/moduledef.cpp
  src/namespacedef.cpp
Labels: bug, beautify

#11286 Size of project name when part of "treeview"
  templates/html/doxygen.css
Labels: enhancement, HTML

#11291 Spelling correction
  doc/changelog.dox
Labels: bug, documentation

#11292 Encoding `doxycommentview` output
  addon/doxycommentview/doxycommentview.py
Labels: bug

#11284 Documentation corrections
  doc/customize.dox
Labels: bug, documentation

#11294 issue #11273 Using a tilde in the URL of a Markdown image tag breaks the tag if the image is in the IMAGE_PATH
  src/commentscan.l
  src/doctokenizer.l
  src/fortranscanner.l
  src/pyscanner.l
  src/scanner.l
Labels: enhancement

#11287 Don't convert CMake environment variables when using `-x_noenv` option
  src/configimpl.l
Labels: bug

#11290 Multiple parameters with underscores and one `\param` command
  src/markdown.cpp
Labels: bug

#11298 Documentation corrections.
  doc/changelog.dox
  testing/dtd/xhtml1-transitional.dtd
Labels: bug, documentation

#11302 cmake: Fix flex version check for overriding the register keyword
  CMakeLists.txt
Labels: bug, install/build
