Repository doxygen/doxygen, pull requests merged in 2024-09, with the labels that each got.

#11115 issue #11114 Doxygen 1.12.0 mishandles Markdown section header following `<pre>` HTML markup.
  src/markdown.cpp
Labels: bug, Markdown

#11117 issue #11116 Graphical glitch with lists and text spilling over on a new line.
  templates/html/doxygen.css
Labels: bug, HTML

#11113 issue #10649 Building failure: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
  CMakeLists.txt
Labels: bug, install/build

#11121 Spelling correction
  doc/changelog.dox
Labels: bug, documentation

#11124 Spelling corrections
  doc/changelog.dox
Labels: bug, documentation

#11126 Repeated variable names is code browser
  src/pycode.l
Labels: bug, Python

#11132 issue #11130 three-way comparison operator is showing up as "operator" instead of "operator<=>" in related symbols
  src/declinfo.l
Labels: bug, C/C++

#11131 Change JAVADOC_BLOCK to JAVADOC_BANNER in example
  examples/javadoc-banner.h
Labels: bug, documentation

#11122 bug 729344 Ignoring an items when / or \ is placed after \addindex
  src/commentscan.l
Labels: bug

#11136 Fix out-of-bounds `std::string_view` access in Markdown n-/m-dash processing
  src/markdown.cpp
  testing/055/md_055__markdown.xml
  testing/055_markdown.md
Labels: bug, Markdown

#11140 issue #11135 The anchors don't work
  src/commentscan.l
Labels: bug, Markdown

#11139 issue #11134 gswin64c.exe not recognized if path added to EXTERNAL_TOOL_PATH
  src/portable.cpp
Labels: bug

#10679 Formula doesn't render due to empty lines.
  src/commentscan.l
  src/qcstring.h
Labels: bug, LaTeX

#11145 Incorrect marking of enum values in source browser
  src/scanner.l
Labels: bug

#11146 More flexibility showing undocumented namespaces (2)
  src/doxygen.cpp
Labels: bug

#11150 Incorrect label for enum values
  src/memberdef.cpp
Labels: bug

#11151 issue #11147 Functions are incorrectly flagged as undocumented if not generating HTML or LaTeX
  src/outputlist.cpp
Labels: bug, XML

#11157 Warning in case of double specification of cite name
  src/cite.cpp
Labels: bug

#11159 Update available emojis
  doc/emojisup.dox
  src/emoji.cpp
  testing/076/indexpage.xml
Labels: bug
