Repository doxygen/doxygen, pull requests merged in 2024-03, with the labels that each got.

#10705 issue #10703 Incorrect output for a C++ type containing a function pointer
  src/scanner.l
Labels: bug, C/C++

#10699 Fix Discarding of Slice Types During File Index Generation
  src/filedef.cpp
Labels: bug

#10712 Prevent warning about possible buffer overflow
  src/commentscan.l
Labels: bug, install/build

#10722 Incorrect signatures used for translator report
  doc/translator.py
Labels: bug, documentation

#10725 Incorrect recognition of a lex rule pattern.
  src/pre.l
Labels: bug, documentation

#10728 Keep utf8 characters together in comments
  src/fortrancode.l
Labels: bug, Fortran

#10727 issue #10726 Error in processing Fortran file with character string returning function
  src/util.cpp
Labels: bug, Fortran

#10720 issue #10719 "unable to resolve reference to ... for \ref command" infile comment - but it's right there
  src/pre.l
Labels: bug

#10731 Keep utf8 characters together in comments
  src/fortranscanner.l
Labels: bug, Fortran

#10732 issue #10707 Issue with doxyfigcaption
  src/latexdocvisitor.cpp
  templates/latex/doxygen.sty
Labels: bug, LaTeX

#10734 Incorrect handling of `$` in an objC string
  src/code.l
Labels: bug, C/C++

#10736 Handling escaped commands inside `\if`
  src/commentscan.l
Labels: bug

#10737 Incorrect handling command character in comment conversion
  src/commentcnv.l
Labels: bug

#10738 Updating compound.py
  addon/doxmlparser/doxmlparser/compound.py
Labels: bug, doxmlparser

#10741 issue #10740 Guide the user to doxygen_manual.log when building the manual PDF fails
  doc/CMakeLists.txt
  src/latexgen.cpp
Labels: bug, documentation, LaTeX

#10745 Small improvements internal documentation
  doc_internal/doxygen.md
Labels: bug, documentation

#10748 issue #10747 Alias replaces HTML brackets to HTML codes, e.g "<img src=..." to "&lt;img src="
  src/markdown.cpp
Labels: bug, Markdown

#10753 Spelling correction
  doc_internal/doxygen.md
Labels: bug, documentation

#10755 issue #10754 GENERATE_HTMLHELP with \msc & \endmsc is broken because of absolute paths in index.hhp since 1.9.3
  src/msc.cpp
Labels: bug, HTML

#10715 latexgen: fix doxy*section references
  src/docbookgen.cpp
  src/docbookgen.h
  src/htmlgen.cpp
  src/htmlgen.h
  src/latexgen.cpp
  src/latexgen.h
  src/mangen.cpp
  src/mangen.h
  src/memberdef.cpp
  src/memberlist.cpp
  src/outputlist.h
  src/rtfgen.cpp
  src/rtfgen.h
  src/vhdldocgen.cpp
Labels: bug, LaTeX

#10767 Automatic update of the addon `py` files based on `xsd` file
  .github/workflows/build_cmake.yml
  CMakeLists.txt
  addon/CMakeLists.txt
  addon/doxmlparser/CMakeLists.txt
  testing/CMakeLists.txt
Labels: bug, install/build

#10769 Flexibility for trDocumentation in respect to the ProjectName
  src/index.cpp
  src/translator.h
  src/translator_am.h
  src/translator_ar.h
  src/translator_bg.h
  src/translator_br.h
  src/translator_ca.h
  src/translator_cn.h
  src/translator_cz.h
  src/translator_de.h
  src/translator_dk.h
  src/translator_en.h
  src/translator_eo.h
  src/translator_es.h
  src/translator_fa.h
  src/translator_fi.h
  src/translator_fr.h
  src/translator_gr.h
  src/translator_hi.h
  src/translator_hr.h
  src/translator_hu.h
  src/translator_id.h
  src/translator_it.h
  src/translator_jp.h
  src/translator_kr.h
  src/translator_lt.h
  src/translator_lv.h
  src/translator_mk.h
  src/translator_nl.h
  src/translator_no.h
  src/translator_pl.h
  src/translator_pt.h
  src/translator_ro.h
  src/translator_ru.h
  src/translator_sc.h
  src/translator_si.h
  src/translator_sk.h
  src/translator_sr.h
  src/translator_sv.h
  src/translator_tr.h
  src/translator_tw.h
  src/translator_ua.h
  src/translator_vi.h
  src/translator_za.h
Labels: bug

#10746 Unique labels for `\include{doc}`
  doc/commands.dox
  doc_internal/commands_internal.md
  src/commentcnv.l
  src/commentscan.l
Labels: bug

#10772 issue #10763 CREATE_SUBDIRS and C++20 modules: Doxygen doesn't create directories
  src/moduledef.cpp
Labels: bug, C/C++, C++20

#10770 Consistency of argument of `trDocumentation`
  src/translator.h
  src/translator_am.h
  src/translator_ar.h
  src/translator_bg.h
  src/translator_br.h
  src/translator_ca.h
  src/translator_cn.h
  src/translator_cz.h
  src/translator_de.h
  src/translator_dk.h
  src/translator_en.h
  src/translator_eo.h
  src/translator_es.h
  src/translator_fa.h
  src/translator_fi.h
  src/translator_fr.h
  src/translator_gr.h
  src/translator_hi.h
  src/translator_hr.h
  src/translator_hu.h
  src/translator_id.h
  src/translator_it.h
  src/translator_jp.h
  src/translator_kr.h
  src/translator_lt.h
  src/translator_lv.h
  src/translator_mk.h
  src/translator_nl.h
  src/translator_no.h
  src/translator_pl.h
  src/translator_pt.h
  src/translator_ro.h
  src/translator_ru.h
  src/translator_sc.h
  src/translator_si.h
  src/translator_sk.h
  src/translator_sr.h
  src/translator_sv.h
  src/translator_tr.h
  src/translator_tw.h
  src/translator_ua.h
  src/translator_vi.h
  src/translator_za.h
Labels: bug

#10773 Always set `Compiled file` for HTML help compiler
  src/htmlhelp.cpp
Labels: bug, HTML

#10774 Adding sub links to doxygen_crawl file.
  src/sitemap.cpp
  src/sitemap.h
Labels: bug, HTML

#10771 issue #10762 Macro define a class name to a different one causes extra whitespace to appear
  src/pre.l
Labels: bug
