Repository doxygen/doxygen, pull requests merged in 2024-04, with the labels that each got.

#10775 issued #7589 Add Markdown todo list
  addon/doxmlparser/doxmlparser/compound.py
  doc/lists.dox
  doc/markdown.dox
  src/docbookvisitor.cpp
  src/docnode.cpp
  src/docnode.h
  src/doctokenizer.h
  src/doctokenizer.l
  src/htmldocvisitor.cpp
  src/latexdocvisitor.cpp
  src/mandocvisitor.cpp
  src/perlmodgen.cpp
  src/printdocvisitor.h
  src/rtfdocvisitor.cpp
  src/rtfdocvisitor.h
  src/rtfgen.cpp
  src/rtfstyle.cpp
  src/rtfstyle.h
  src/xmldocvisitor.cpp
  templates/html/doxygen.css
  templates/latex/doxygen.sty
  templates/xml/compound.xsd
Labels: enhancement, Markdown

#10777 Fix up C++20 module pseudo-keyword masking variables/members
  src/code.l
  src/scanner.l
Labels: bug, C++2x

#10779 issue #10776 Provide the ability to sort implemented/re-implemented list
  src/memberlist.cpp
Labels: bug

#10785 issue #10781 Add a "Run" menu item key-command to DoxyWizard
  addon/doxywizard/doxywizard.cpp
  addon/doxywizard/doxywizard.h
  doc/doxywizard_menu_settings.png
  doc/doxywizard_usage.dox
Labels: enhancement, doxywizard

#10784 Problem with colon inserted by `\addindex`
  src/htmldocvisitor.cpp
  src/htmlhelp.cpp
Labels: bug, HTML

#10787 Warning in pre.l
  src/pre.l
Labels: bug, install/build

#10791 issue #10790 Failed to build "master" branch
  doc/translator.py
Labels: bug, install/build, documentation

#10792 Guarantee unsigned 32-bit word for md5 calculation
  deps/libmd5/md5_loc.h
Labels: bug, install/build

#10793 Debugging of tests
  testing/runtests.py
Labels: enhancement, install/build

#10794 Delay removing files in case of RTF till end of process
  src/config.xml
  src/doxygen.cpp
  src/rtfgen.cpp
Labels: bug, enhancement, RTF

#10788 issue #10147 Generating pdf with LuaLateX
  src/formula.cpp
  src/latexgen.cpp
  templates/latex/header.tex
Labels: bug, LaTeX

#10802 Running tests in pdf mode
  src/translator_ar.h
  src/translator_fa.h
  src/translator_gr.h
  src/translator_hi.h
Labels: bug, LaTeX

#10796 Remove pedantic warnings regarding `;`
  src/conceptdef.cpp
  src/dotgraph.h
Labels: bug, install/build

#10803 Error generating PDF for test 59 in Spanish
  src/translator_es.h
Labels: bug, LaTeX

#10800 issue #10799 Explicit C# event mistaken for property
  src/scanner.l
Labels: bug, C#

#10805 Updated Polish translation to 1.11.0
  src/translator_pl.h
Labels: bug

#10808 Removing double logic
  doc/translator.py
  src/translator.h
  src/translator_ar.h
  src/translator_br.h
  src/translator_ca.h
  src/translator_cz.h
  src/translator_de.h
  src/translator_dk.h
  src/translator_en.h
  src/translator_eo.h
  src/translator_es.h
  src/translator_fa.h
  src/translator_fi.h
  src/translator_fr.h
  src/translator_gr.h
  src/translator_hi.h
  src/translator_hr.h
  src/translator_hu.h
  src/translator_id.h
  src/translator_it.h
  src/translator_ke.h
  src/translator_kr.h
  src/translator_lt.h
  src/translator_lv.h
  src/translator_nl.h
  src/translator_no.h
  src/translator_pl.h
  src/translator_pt.h
  src/translator_ro.h
  src/translator_si.h
  src/translator_sk.h
  src/translator_sr.h
  src/translator_sv.h
  src/translator_tr.h
  src/translator_vi.h
  src/translator_za.h
Labels: bug

#10798 issue #10240 Multi-line doc not recognized in Python class field
  src/pyscanner.l
Labels: bug, Python

#10811 Writing all debug output to stderr
  doc/arch.dox
  src/debug.cpp
  src/debug.h
Labels: enhancement

#10813 Removing double logic (part 2)
  src/translator_bg.h
  src/translator_cz.h
  src/translator_kr.h
  src/translator_mk.h
  src/translator_ru.h
  src/translator_sc.h
  src/translator_sk.h
  src/translator_sr.h
  src/translator_tr.h
  src/translator_ua.h
Labels: bug

#10817 Warnings due to multiple "sectioning" commands inside an `\if` type construct
  src/cite.cpp
  src/commentscan.h
  src/commentscan.l
  src/fortranscanner.l
  src/markdown.cpp
  src/pyscanner.l
  src/scanner.l
  src/vhdljjparser.cpp
Labels: bug

#10824 issue #10823 Inconsistencies on use of separating space before an [ or { in documentation and examples
  doc/commands.dox
Labels: bug, documentation

#10826 issue #10820 Snippet in same file to share docs
  src/fortranscanner.l
  src/pyscanner.l
Labels: bug, Fortran, Python

#10829 Warning for Fortran on `\code` command
  src/fortranscanner.l
Labels: bug, Fortran

#10830 Unicode characters in file names
  src/commentcnv.l
  src/doctokenizer.l
  src/fortranscanner.l
  src/pyscanner.l
  src/scanner.l
Labels: bug

#10832 Warning with ingroup command at end of alias
  src/markdown.cpp
Labels: bug, Markdown

#10841 issue #10838 not recognize "*, " in python
  src/pyscanner.l
Labels: bug, Python

#10834 issue #10827 member variable with type annotation and not used anywhere of python class is missed
  src/pyscanner.l
Labels: enhancement, Python
