Repository doxygen/doxygen, pull requests merged in 2024-02, with the labels that each got.

#10616 issue #10608 GitHub Flavored Markdown
  addon/doxmlparser/doxmlparser/compound.py
  doc/commands.dox
  doc/markdown.dox
  src/cmdmapper.cpp
  src/cmdmapper.h
  src/commentscan.l
  src/docbookvisitor.cpp
  src/docnode.cpp
  src/docnode.h
  src/htmldocvisitor.cpp
  src/latexdocvisitor.cpp
  src/mandocvisitor.cpp
  src/markdown.cpp
  src/perlmodgen.cpp
  src/printdocvisitor.h
  src/rtfdocvisitor.cpp
  src/translator.h
  src/translator_adapter.h
  src/translator_br.h
  src/translator_en.h
  src/translator_gr.h
  src/translator_nl.h
  src/translator_pl.h
  src/translator_pt.h
  src/xmldocvisitor.cpp
  templates/html/doxygen.css
  templates/latex/doxygen.sty
  templates/xml/compound.xsd
Labels: enhancement, Markdown

#10620 issue #10618 C++ consteval functions need label
  addon/doxmlparser/doxmlparser/compound.py
  src/memberdef.cpp
  src/memberdef.h
  src/scanner.l
  src/types.h
  src/xmlgen.cpp
  templates/xml/compound.xsd
Labels: enhancement, C++20

#10617 Incorrect translation indented fenced code blocks
  src/markdown.cpp
Labels: bug, Markdown

#10621 Spelling errors
  src/stringutil.h
Labels: bug

#10622 Portuguese tranlators updated to 1.11.0.
  src/translator_br.h
  src/translator_pt.h
Labels: bug

#10634 Fix out of bounds issue in aliases.cpp
  src/aliases.cpp
Labels: bug

#10635 issue #10631 Spurious .PP on Value headings in Macro Definition Documentation in man page
  src/mangen.cpp
  src/mangen.h
  src/rtfgen.cpp
  src/rtfgen.h
Labels: bug, RTF, Man

#10633 Issue #10623 Unexpected "code block" formatting for detailed description of enum values using C++ style comments
  src/scanner.l
Labels: bug, C/C++

#10632 Enable `this` again as argument of `\snippet{doc}`
  src/commentcnv.l
Labels: bug

#10638 issue #10636 weird behavior with `\hideinheritancegraph`
  src/commentscan.l
  src/doxygen.cpp
  src/entry.cpp
  src/entry.h
Labels: enhancement

#10646 issue #10643 doxygen --version shows GIT-NOTFOUND
  libversion/gitversion.cpp.in
Labels: bug

#10652 Prevent `size_t` constructs to wrap around
  src/markdown.cpp
Labels: bug, Markdown

#10653 issue #10642 Group titles not carried over into External Search
  src/searchindex.cpp
Labels: bug, HTML

#10658 Check validity of Doxyfile.xml against all possible names of the settings
  src/config.h
  src/configimpl.h
  src/configimpl.l
  src/xmlgen.cpp
  templates/xml/doxyfile.xsd
Labels: bug, XML

#10657 issue #10655 Class Member List does not show friend operator parameter list
  src/classdef.cpp
Labels: bug, C/C++

#10659 Added missing possible `type`s in the external search description
  doc/extsearch.dox
Labels: bug, documentation

#10662 Spelling error
  doc/extsearch.dox
Labels: bug, documentation

#10664 Incorrect link references to GitHub in changelog
  doc/changelog.dox
Labels: bug, documentation

#10665 Spelling error
  src/symbolresolver.cpp
Labels: bug

#10667 Fix table overlaping footer
  templates/latex/longtable_doxygen.sty
Labels: bug, LaTeX

#10673 Refactoring: Fixing warnings like: Use the "nullptr" literal (3)
  addon/doxyparse/doxyparse.cpp
  addon/doxywizard/config_doxyw.l
  addon/doxywizard/doxywizard.cpp
  addon/doxywizard/expert.cpp
  addon/doxywizard/inputstring.cpp
  addon/doxywizard/inputstrlist.cpp
  addon/doxywizard/wizard.cpp
  src/clangparser.cpp
  src/dirdef.cpp
  src/doxygen.cpp
  src/index.cpp
  src/membergroup.cpp
  src/memberlist.cpp
  src/perlmodgen.cpp
  src/portable.cpp
  src/rtfgen.cpp
  src/sqlite3gen.cpp
  src/symbolresolver.cpp
  src/util.cpp
  src/vhdljjparser.cpp
  src/xmldocvisitor.cpp
  src/xmlgen.cpp
Labels: install/build, beautify

#10674 Correcting links in documentation
  doc/faq.dox
  doc/install.dox
  doc/xmlcmds.dox
  src/config.xml
Labels: bug, documentation

#10680 Missing items in doxygen internal search
  src/searchindex_js.cpp
Labels: bug, HTML

#10681 Prevent automatic upper case conversion in doxygen internal search
  src/searchindex_js.cpp
Labels: bug, HTML

#10685 Incorrect `searchdata.xml` for `mainpage` in case of external search
  src/doxygen.cpp
  src/index.cpp
  src/pagedef.cpp
Labels: bug, HTML

#10686 issue #7948 "ilinebr" on every link broke my entire project
  src/commentcnv.l
Labels: bug, C/C++

#10689 Spelling correction Dutch translation
  src/translator_nl.h
Labels: bug

#10683 Revised and updated Chinese translation to 1.11.0
  src/translator_cn.h
Labels: bug

#10690 Consistency of arguments with other translator functions
  src/datetime.cpp
  src/translator.h
  src/translator_adapter.h
  src/translator_am.h
  src/translator_ar.h
  src/translator_bg.h
  src/translator_br.h
  src/translator_ca.h
  src/translator_cn.h
  src/translator_cz.h
  src/translator_de.h
  src/translator_dk.h
  src/translator_en.h
  src/translator_eo.h
  src/translator_es.h
  src/translator_fa.h
  src/translator_fi.h
  src/translator_fr.h
  src/translator_gr.h
  src/translator_hi.h
  src/translator_hr.h
  src/translator_hu.h
  src/translator_id.h
  src/translator_it.h
  src/translator_jp.h
  src/translator_kr.h
  src/translator_lt.h
  src/translator_lv.h
  src/translator_mk.h
  src/translator_nl.h
  src/translator_no.h
  src/translator_pl.h
  src/translator_pt.h
  src/translator_ro.h
  src/translator_ru.h
  src/translator_sc.h
  src/translator_si.h
  src/translator_sk.h
  src/translator_sr.h
  src/translator_sv.h
  src/translator_tr.h
  src/translator_tw.h
  src/translator_ua.h
  src/translator_vi.h
  src/translator_za.h
Labels: install/build

#10691 Inconsistency in handling space at end of translated string.
  src/classdef.cpp
  src/htmldocvisitor.cpp
  src/translator_am.h
  src/translator_ar.h
  src/translator_bg.h
  src/translator_br.h
  src/translator_ca.h
  src/translator_cn.h
  src/translator_cz.h
  src/translator_de.h
  src/translator_dk.h
  src/translator_en.h
  src/translator_eo.h
  src/translator_es.h
  src/translator_fa.h
  src/translator_fi.h
  src/translator_fr.h
  src/translator_gr.h
  src/translator_hu.h
  src/translator_id.h
  src/translator_it.h
  src/translator_jp.h
  src/translator_kr.h
  src/translator_lt.h
  src/translator_lv.h
  src/translator_mk.h
  src/translator_nl.h
  src/translator_no.h
  src/translator_pl.h
  src/translator_pt.h
  src/translator_ro.h
  src/translator_ru.h
  src/translator_sc.h
  src/translator_si.h
  src/translator_sk.h
  src/translator_sr.h
  src/translator_sv.h
  src/translator_tr.h
  src/translator_vi.h
  src/translator_za.h
Labels: bug

#10695 Warning in internal documentation
  src/commentcnv.h
Labels: bug, documentation

#10692 Warnings in PDF build of doxygen documentation build
  doc/commands.dox
Labels: install/build, documentation, LaTeX

#10647 cmake: always install man pages, only install for the binaries installed
  CMakeLists.txt
  doc/CMakeLists.txt
Labels: install/build
