Repository doxygen/doxygen, pull requests merged in 2024-07, with the labels that each got.

#10974 issue #10962 std:: hypertext link if a class documents std() function
  src/code.l
Labels: bug, C/C++

#10975 issue #10973 attribute is repeated twice in python
  src/doxygen.cpp
Labels: bug, Python

#10979 issue #10977 dontinclude pattern find itself
  src/docnode.cpp
Labels: bug

#10986 made top and bottom row of asterisks same length to align them
  doc/docblocks.dox
  examples/javadoc-banner.h
Labels: documentation, beautify

#10993 issue #10959 Capability to render GitHub flavor Markdown comments
  src/commentcnv.l
Labels: bug

#10996 issue #10995 Build issue: Build picks up wrong git info
  cmake/git_watcher.cmake
  libversion/CMakeLists.txt
Labels: enhancement, install/build

#8266 issue #8256 Possible to get enum values in the Enumeration Type documentation
  doc/commands.dox
  src/commentscan.l
  src/config.xml
  src/docbookgen.cpp
  src/docbookgen.h
  src/doxygen.cpp
  src/entry.h
  src/htmlgen.cpp
  src/htmlgen.h
  src/latexgen.cpp
  src/latexgen.h
  src/mangen.cpp
  src/mangen.h
  src/memberdef.cpp
  src/memberdef.h
  src/outputgen.h
  src/outputlist.h
  src/rtfgen.cpp
  src/rtfgen.h
  src/util.cpp
  templates/html/doxygen.css
  templates/latex/doxygen.sty
Labels: enhancement

#10988 Python class variables type and initial value
  src/pyscanner.l
Labels: bug, Python

#11004 Wrong bracket test
  src/code.l
Labels: bug

#10999 issue #6473 Plantuml parse error
  doc/commands.dox
  doc_internal/commands_internal.md
  src/scanner.l
  src/util.cpp
Labels: bug, Markdown

#11009 Adding "engine" chen and chronology for plantuml
  doc/commands.dox
  src/docnode.cpp
Labels: enhancement

#10985 issue #10835 Two relates group generates warning: found multiple \relates, \relatesalso or \memberof commands in a comment block, using last definition
  src/docgroup.cpp
Labels: bug

#11014 issue #11013 compound.xsd is missing types for some elements
  addon/doxmlparser/doxmlparser/compound.py
  templates/xml/compound.xsd
Labels: bug, XML

#11038 Debug output for layout file
  src/debug.cpp
  src/debug.h
  src/doxygen.cpp
  src/layout.h
Labels: enhancement

#11030 Message about style redefinition in RTF
  src/rtfgen.cpp
  src/rtfstyle.cpp
Labels: bug, RTF

#11028 issue #10989 Incorrect linking in C++ code
  src/code.l
  src/scopedtypevariant.h
Labels: bug, C/C++

#11026 Missing filename for tag warnings
  src/tagreader.cpp
Labels: bug
