Repository doxygen/doxygen, pull requests merged in 2024-06, with the labels that each got.

#10910 markdown: fix emphasis with extra characters
  src/markdown.cpp
Labels: bug, Markdown

#10905 issue #10904 Topics page lists modules but no descriptions
  src/commentscan.l
Labels: bug

#10908 issue #10906 Unable to resolve reference to 'some/path/README.md' for \ref command
  src/docnode.cpp
Labels: bug

#10914 issue #10912 Commands defined via ALIASES tag have an extra space after value
  src/commentcnv.l
Labels: bug

#10909 issue #10907 Cite command creates case sensitivity on name
  src/cite.cpp
  testing/012/citelist.xml
  testing/012/indexpage.xml
Labels: enhancement

#10919 Setting protection
  testing/012/citelist.xml
  testing/012/indexpage.xml
Labels: bug, install/build

#10916 issue #10606 include command via ALIASES does not work anymore (snippetdoc)
  src/commentcnv.l
Labels: bug

#10903 issue #10902 Improve Markdown Support - blockquotes with special markers parse wrongly
  src/markdown.cpp
Labels: bug, Markdown

#10923 issue #10922 Doxywizard Font Size Rendering Problem on 4k HiRes Monitors
  addon/doxywizard/doxywizard.cpp
Labels: bug, doxywizard

#10921 issue #10606 include command via ALIASES does not work anymore (2)
  src/commentcnv.l
Labels: bug

#10926 Files stayed in RTF directory
  src/rtfgen.cpp
Labels: bug, RTF

#10929 issue #10928 Setting JAVACC_CHAR_TYPE
  src/qcstring.h
Labels: bug, install/build

#10927 Document all possible values of the `dir` attribute within the `param` command
  doc/commands.dox
Labels: bug, documentation

#10920 issue #10902 Improve Markdown Support - blockquotes with special markers parse wrongly (2)
  src/markdown.cpp
Labels: bug, Markdown

#10933 issue #10932 message: [generated]:8: warning: invalid argument for command '\iline'
  src/doctokenizer.l
Labels: bug

#10934 Spelling correction
  doc/extsearch.dox
  doc/faq.dox
  doc/features.dox
  doc/formulas.dox
  doc/grouping.dox
  doc/install.dox
  doc/markdown.dox
  src/config.xml
Labels: bug, documentation

#10939 issue #10937 unexpected token TK_COMMAND_BS as the argument of `\ifile`
  src/definition.cpp
Labels: bug

#10940 issue #10937 unexpected token TK_COMMAND_BS as the argument of `\ifile`
  src/docparser.cpp
Labels: bug

#10966 issue #10959 Support of special HTML comments
  doc/htmlcmds.dox
  src/commentcnv.l
Labels: enhancement

#10967 issue #10949 Doxygen replaces # by ::
  src/docparser.cpp
Labels: bug

#10958 issue #10955 HTML comment affects output
  src/commentscan.l
Labels: bug, HTML, Man
