Repository doxygen/doxygen, pull requests merged in 2025-02, with the labels that each got.

#11332 Flexibility of number of labels along edges in UNL_LOOK diagram
  src/config.xml
  src/dotclassgraph.cpp
Labels: enhancement

#11336 Layout labels on edges
  src/dotnode.cpp
  src/dotnode.h
Labels: bug

#11388 issue #11387 commit 152ad343c can break verbatim
  src/mandocvisitor.cpp
  src/mandocvisitor.h
Labels: bug, Man

#11394 issue #11393 With `EXPAND_ONLY_PREDEF`, Doxygen won't expand `PREDEFINED` macro that's defined in an included header file.
  src/pre.l
Labels: bug

#11390 Correcting python scripts in respect to style
  addon/doxmlparser/examples/metrics/metrics.py
  addon/doxmlparser/generateDS_post.py
  addon/doxypysql/search.py
  doc/translator.py
  doc_internal/cmds_tags.py
  src/caseconvert.py
  src/configgen.py
  src/post_lex.py
  src/res2cc_cmd.py
  testing/runtests.py
  testing/testsqlite3.py
Labels: install/build, beautify

#11389 Create possibility to have also man pages generated in test suite
  .github/workflows/build_cmake.yml
  testing/README.txt
  testing/runtests.py
Labels: enhancement, Man

#11402 issue #11401 Unexpected html tag `<span>` found within `<dt>` context
  src/docparser.cpp
Labels: enhancement

#11385 issue #11310 "^^" in aliases not proper evaluated
  src/commentcnv.l
  src/markdown.cpp
Labels: bug

#11404 Incorrect field when ampersand in URL
  src/htmldocvisitor.cpp
Labels: bug, HTML

#11435 Dangerous trailing context in commentcnv.l
  src/commentcnv.l
Labels: bug, install/build

#11437 issue #11420 Triple underscores in Markdown mode not supported
  src/markdown.cpp
Labels: bug, Markdown

#11441 issue #11420 Add documentation about triple underscore emphasis
  doc/markdown.dox
Labels: bug, documentation, Markdown

#11443 issue #11416 CMake: Error in doc_internal/CMakeLists.txt:22 Problem configuring file
  cmake/WindowsEncoding.cmake
  doc_internal/CMakeLists.txt
  doc_internal/Doxyfile.in
Labels: bug, install/build

#11442 issue #11416 CMake: Error in doc_internal/CMakeLists.txt:22 Problem configuring file
  deps/libmscgen/mscgen_config.h
Labels: bug, install/build

#11447 issue #11415 doxywizard replaces < and > in aliases with &lt; / &gt;
  addon/doxywizard/config.h
  addon/doxywizard/config_doxyw.l
  addon/doxywizard/doxywizard.cpp
  addon/doxywizard/expert.cpp
  addon/doxywizard/expert.h
  addon/doxywizard/input.h
  addon/doxywizard/inputbool.cpp
  addon/doxywizard/inputbool.h
  addon/doxywizard/inputint.cpp
  addon/doxywizard/inputint.h
  addon/doxywizard/inputobsolete.h
  addon/doxywizard/inputstring.cpp
  addon/doxywizard/inputstring.h
  addon/doxywizard/inputstrlist.cpp
  addon/doxywizard/inputstrlist.h
Labels: bug, doxywizard

#11446 Incorrect substitute pattern in header / footer
  src/htmlgen.cpp
  src/latexgen.cpp
  src/util.cpp
  src/util.h
Labels: bug, HTML, LaTeX

#11452 Fix wrong links created in search box for external documentations with absolute paths
  templates/html/search.js
Labels: bug, HTML

#11457 Spelling correction
  src/clangparser.cpp
Labels: bug

#11456 Prevent code duplication for enum
  src/defgen.cpp
  src/message.h
  src/perlmodgen.cpp
  src/types.h
  src/util.cpp
  src/xmlgen.cpp
Labels: enhancement, beautify

#11450 issue #11421 `SHOW_GROUPED_MEMB_INC` does not respect `STRIP_FROM_INC_PATH`
  src/memberdef.cpp
Labels: bug

#11449 Don't repeat the exact same warning messages
  src/message.cpp
Labels: enhancement

#11464 issue #11400 python documentation fails with "::bool" and "::str" warnings
  src/pyscanner.l
Labels: bug, Python

#11460 issue #11454 Since version 1.12.0 alias tags cause tables to break
  src/commentscan.l
Labels: bug

#11459 issue #11458 Confusing error message if snippet command misses blockmarkers
  src/commentcnv.l
Labels: bug

#11462 issue #11436 External SVG images not loaded with image-command
  src/htmldocvisitor.cpp
Labels: enhancement, HTML

#11465 issue #11419 static keyword appearing as function prefix but not inline
  src/memberdef.cpp
Labels: enhancement
