Repository doxygen/doxygen, pull requests merged in 2025-03, with the labels that each got.

#11470 bump minimal ci runner version to Ubuntu 22.04
  .github/workflows/build_cmake.yml
  .github/workflows/coverity.yml
Labels: bug, install/build

#11468 Add Linux ARM to CI
  .github/workflows/build_cmake.yml
Labels: enhancement, install/build

#11487 Messages could land in different files
  src/doxygen.cpp
Labels: bug

#11485 Small consistency improvement
  src/commentscan.l
Labels: enhancement

#11480 issue #9437,#11179 Add docs about markdown page exceptions
  doc/markdown.dox
Labels: enhancement, documentation

#11475 Update docker base os from focal to jammy
  Dockerfile
Labels: bug, install/build

#11474 Warning when more `#if` than `#endif` statements
  src/pre.l
Labels: bug

#11481 Small correction to warn message
  src/docnode.cpp
Labels: bug, beautify

#11513 Adding "loading" attribute to dtd
  testing/dtd/xhtml1-transitional.dtd
Labels: bug, HTML

#11506 issue #11504 References not generated when tilde and dot in directory name
  src/definition.cpp
Labels: bug

#11514 Small correction to internal documentation
  src/regex.h
Labels: bug, documentation

#11482 Consistency of use of `HIDE_COMPOUND_REFERENCE`
  src/classdef.cpp
  src/conceptdef.cpp
  src/dirdef.cpp
  src/filedef.cpp
  src/moduledef.cpp
  src/namespacedef.cpp
Labels: bug

#11519 Handling of case sensitive file / directory names
  src/util.cpp
Labels: bug
