Repository doxygen/doxygen, pull requests merged in 2025-01, with the labels that each got.

#11306 Add module part to customize documentation
  doc/customize.dox
Labels: bug, documentation

#11311 Documentation corrections.
  doc/changelog.dox
Labels: bug, documentation

#11303 issue #11210 Support for Plus sign code fence directives - GitHub flavor
  doc/markdown.dox
  src/doctokenizer.l
  src/markdown.cpp
Labels: enhancement

#11312 String representation at "show configuration" in doxywizard
  addon/doxywizard/config_doxyw.l
Labels: bug, doxywizard

#11324 issue #11308 SVG dot graphs have added padding
  src/config.xml
  src/configimpl.l
  src/dotfilepatcher.cpp
Labels: enhancement

#11318 Adding debug and version information to doxycommentview
  addon/doxycommentview/README.md
  addon/doxycommentview/doxycommentview.py
Labels: enhancement

#11331 issue #11330 Snippet trimleft option does not handle newlines well
  src/codefragment.cpp
Labels: enhancement

#11334 Remove redundant 'visible' attrs in layout
  templates/general/layout_default.xml
Labels: bug

#11356 issue #7522 Source code browser does not distinguish between same-named functions
  src/fortrancode.l
Labels: bug, Fortran

#11353 Consistent translation of `//!` comments
  src/commentcnv.l
Labels: bug

#11343 Fix typos in src/config.xml
  src/config.xml
Labels: bug, documentation

#11351 issue #11350 [C#] Documentation Generation Fails for Members Following a Property Getter with Curly Braces in char
  src/scanner.l
Labels: bug, C#

#11346 issue #11246 Markdown links to headings are not handled by doxygen like by GitHub or azure
  src/markdown.cpp
Labels: bug, Markdown

#11348 issue #11342 The code is incorrectly formatted in `@code` command
  src/outputlist.cpp
Labels: bug

#11357 Remove macro defines from C++ scoped enum values
  src/doxygen.cpp
  testing/107/107__define__in__enums_8cpp.xml
  testing/107_define_in_enums.cpp
Labels: bug, C/C++

#11360 Incorrect number of doxygen htmlentities
  src/htmlentity.cpp
Labels: bug

#11363 Page anchor of directory description
  src/markdown.cpp
Labels: bug, Markdown

#11347 bug 683051 Template parameter cannot be commented inline
  src/arguments.cpp
  src/arguments.h
  src/classdef.cpp
  src/memberdef.cpp
  src/scanner.l
  src/util.cpp
  src/util.h
  src/xmlgen.cpp
Labels: enhancement, C/C++

#11366 Section information lost in case of `IMPLICIT_DIR_DOCS=YES` and `Readme.md`
  src/markdown.cpp
Labels: bug, Markdown

#11378 issue #11377 [in,out] param dir ignored for inline documentation
  src/util.cpp
Labels: bug

#11376 Issue #11371 Odd behavior of line breaks in double quotes
  src/mandocvisitor.cpp
Labels: bug, Man
