Repository doxygen/doxygen, pull requests merged in 2025-05, with the labels that each got.

#11559 issue #8731 grouping variables requires an empty line before closing `@}`
  src/commentcnv.l
Labels: bug, C/C++

#11558 Issue #9843 Incomplete call graph when using curly brackets in constructor call (C++)
  src/code.l
Labels: bug, C/C++

#11570 Translation german update
  src/translator_de.h
Labels: bug

#11573 Linking doxygen under Cygwin
  CMakeLists.txt
Labels: bug, install/build

#11494 Flexibility of `\cite` command
  doc/commands.dox
  src/cite.cpp
  src/cite.h
  src/commentscan.l
  src/docbookvisitor.cpp
  src/docnode.cpp
  src/docnode.h
  src/htmldocvisitor.cpp
  src/latexdocvisitor.cpp
  src/mandocvisitor.cpp
  src/perlmodgen.cpp
  src/printdocvisitor.h
  src/rtfdocvisitor.cpp
  src/textdocvisitor.cpp
  src/xmldocvisitor.cpp
  templates/html/bib2xhtml.pl
  templates/latex/doxygen.sty
Labels: enhancement

#11577 Spelling correction
  src/docnode.cpp
Labels: bug

#11575 issue #11279 longtabu inside DoxyEnumFields breaks
  src/latexdocvisitor.cpp
Labels: bug, LaTeX

#11580 Tables without any rows result in error in LaTeX
  src/docnode.cpp
Labels: bug, HTML, LaTeX, DocBook

#11585 Spelling correction
  doc/changelog.dox
Labels: bug, documentation

#11591 Correction some quotes in changelog
  doc/changelog.dox
Labels: bug, documentation
