Repository doxygen/doxygen, pull requests merged in 2025-04, with the labels that each got.

#11526 issue #11525 Translation error Dutch
  src/translator_nl.h
Labels: bug

#11545 Update doxygen.css for CSS validation
  templates/html/doxygen.css
Labels: bug, HTML

#11544 Spelling corrections
  src/lexscanner.l
  src/scanner.l
Labels: bug

#11546 Update doxygen.css to fix validation issue (II)
  doc/doxygen_manual_chm.css
  templates/html/doxygen.css
Labels: bug, HTML

#11536 use correct definitions in debug mode with libc++ and libstdc++
  CMakeLists.txt
Labels: install/build

#11537 use c++20 as the standard for the project
  CMakeLists.txt
  deps/fmt/include/fmt/core.h
  deps/spdlog/include/spdlog/fmt/bundled/core.h
  vhdlparser/VhdlParserErrorHandler.hpp
Labels: enhancement, install/build

#11532 issue #11528 `\example{lineno}` does not generate the example
  src/types.h
Labels: bug

#11550 issue #11549 Leftover variable in CSS (validation and possible logic issue)
  src/resourcemgr.cpp
  src/resourcemgr.h
  templates/html/navtree.css
Labels: bug, HTML

#11552 CSS resource files don't need special treatment
  src/res2cc_cmd.py
  src/resourcemgr.cpp
  src/resourcemgr.h
Labels: bug, HTML

#11529 issue #11001 \copydoc does not respect section hierarchy in table of contents
  src/docnode.cpp
  src/util.cpp
Labels: bug
